### ISSUE TITLE
Logos Actions

### ISSUE THREAD

**Issue by IxAalexI** [skotlex/ffxiv-material-ui#101]
![Logos](https://user-images.githubusercontent.com/8403780/67443815-06ef7280-f5cc-11e9-9962-201bc02ad6fb.PNG)

Bar on the left doesn't go all the way up, looks off-center or not full? The two vertical lines off the top look odd anyway. Same at any scaling. Thanks!

**Comment by skotlex** [comment]
![Untitled-1](https://user-images.githubusercontent.com/31692408/67610591-ec391b80-f7ce-11e9-9d53-42fed42be1c6.jpg)
I'm sorry. I don't understand the content well, do you mean this?

**Comment by IxAalexI** [comment]
![image](https://user-images.githubusercontent.com/8403780/67613616-2544a200-f775-11e9-909e-7159990fabd3.png)
Sorry, this part here.

**Comment by skotlex** [comment]
The image looks just as I intended. 
Can you give me a sample picture of what you think with a paint program?

**Comment by IxAalexI** [comment]
![Current](https://user-images.githubusercontent.com/8403780/67613942-94bc9080-f779-11e9-9c70-7fbd6888392d.PNG)
Currently it looks like this for full and empty slots, which leaves the whole  bar looking off center, like this:
![logos current](https://user-images.githubusercontent.com/8403780/67613949-abfb7e00-f779-11e9-88da-e5355cf24081.PNG)

If possible, I'd like it to look something like this for full and empty slots:
![Desired](https://user-images.githubusercontent.com/8403780/67613951-bf0e4e00-f779-11e9-8114-4e5f8a92189e.PNG)

**Comment by skotlex** [comment]
That may be possible. I'll give you an answer within the weekend.

**Comment by IxAalexI** [comment]
Thanks!

**Comment by skotlex** [comment]
![주석 2019-10-27 231505](https://user-images.githubusercontent.com/31692408/67636083-1b0adb00-f910-11e9-9c31-75b036b2d78c.png)
[EurekaLogsAetherList_Icon.zip](https://github.com/skotlex/ffxiv-material-ui/files/3775924/EurekaLogsAetherList_Icon.zip)
I modified what you requested and the icon frame :p

**Comment by IxAalexI** [comment]
Thank you so much!
