### ISSUE TITLE
5.1 new Gathering "not yet collected" icon missing

### ISSUE THREAD

**Issue by ividyon** [skotlex/ffxiv-material-ui#102]
**Is your feature request related to a problem? Please describe.**
In 5.1, a new feature for Gathering was added which shows a small icon next to an item that is not yet in your Gathering Log (i.e. you're harvesting for the first time).

This icon seems to be missing when using Material UI (Black).

**Additional context**
![image](https://user-images.githubusercontent.com/1077140/67959562-4126c880-fbf9-11e9-9f09-b1e6c38bbea0.png)

![image](https://user-images.githubusercontent.com/1077140/67959575-4552e600-fbf9-11e9-94b4-9c4c275654b6.png)

**Comment by skotlex** [comment]
This part can only be modified if the textool in 5.1 patches is updated. 
I am also waiting for an update of textool, so please forgive me.
