### ISSUE TITLE
5.1 - Map Icons Are Normal and a Circle Appears in the Square Map

### ISSUE THREAD

**Issue by BValon** [skotlex/ffxiv-material-ui#103]
![image](https://user-images.githubusercontent.com/57301312/68076558-3f3d4080-fd84-11e9-882a-445cf5c2a7d3.png)

**Comment by skotlex** [comment]
Do you use a mix of two options? 
If you want a square map + normal icon combination, I have to make a new option.

**Comment by BValon** [comment]
Apparently I was, but did not realize it. I've fixed the install and the
map is now returned to how I wished it to be.

[image: image.png]

My apologies for my own mix up.
