### ISSUE TITLE
5.1 Favorites Icon in Market Board Item Search is missing/broken

### ISSUE THREAD

**Issue by BValon** [skotlex/ffxiv-material-ui#104]
![image](https://user-images.githubusercontent.com/57301312/68076571-5845f180-fd84-11e9-8e69-9136ab561794.png)

**Comment by skotlex** [comment]
This part can only be modified if the textool in 5.1 patches is updated. 
I am also waiting for an update of textool, so please forgive me.

**Comment by BValon** [comment]
Of course. There are simply to bring to your attention, and I eagerly
await your next update. Thank you for your hard work.
