### ISSUE TITLE
'PvP Profile' and 'Character (PvP)' Windows Not Styled

### ISSUE THREAD

**Issue by natyusha** [skotlex/ffxiv-material-ui#111]
The PvP Profile and Character windows are both unstyled. Ideally both would have squared corners and 1px borders like the rest of the UI. A nice light grey color would do nicely. The PvP window textures can be found at `ui/uld/windowpvp_*.tex`.

The attached image shows both PvP windows next to the duty finder descriptions which they should likely match.
![ffxiv_dx11_2019-11-11_00-49-16](https://user-images.githubusercontent.com/985941/68564000-5ed80700-041d-11ea-994e-c2ded64c2c4f.png)

**Comment by skotlex** [comment]
Thank you for your suggestion. I'll reflect it in the next version.

**Comment by skotlex** [comment]
[PVPwindow.zip](https://github.com/skotlex/ffxiv-material-ui/files/3855158/PVPwindow.zip)
Created based on black version
Let me know if there's anything you need to change.
![주석 2019-11-17 112231](https://user-images.githubusercontent.com/31692408/69002094-e3022100-092c-11ea-80bb-aab481251b84.png)

**Comment by natyusha** [comment]
Nice job, it looks really good.

The only issue I can find is on the 'Additional' Page of the 'PvP Profile' window. The checkboxes will be white and hard to see when changing actions.

![ffxiv_dx11_2019-11-17_06-57-53](https://user-images.githubusercontent.com/985941/69007165-3b72f780-0908-11ea-97a6-757240e33da0.png)

**Comment by skotlex** [comment]
![주석 2019-11-23 155141](https://user-images.githubusercontent.com/31692408/69475004-16e8b500-0e0b-11ea-86b9-2a153b18cb75.png)
Window frame of discord (round border)

![주석 2019-11-23 160519](https://user-images.githubusercontent.com/31692408/69475016-3849a100-0e0b-11ea-8d87-cae2a6777e33.png)
And then I changed the part of the check box.
