### ISSUE TITLE
transparency window

### ISSUE THREAD

**Issue by itstajiri** [skotlex/ffxiv-material-ui#114]
Hello, is it possible to make transparency for inactive window? it was great optional mod in old version.

**Comment by skotlex** [comment]
https://github.com/skotlex/ffxiv-material-ui#preview-options
This option already exists.
![preview](https://user-images.githubusercontent.com/31692408/69005130-b23bdf00-0960-11ea-88af-53b2cd5ef0b2.png)
![preview (1)](https://user-images.githubusercontent.com/31692408/69005132-b405a280-0960-11ea-90e2-348841d08e49.png)

**Comment by itstajiri** [comment]
oh, thanks, haven't seen it
