### ISSUE TITLE
Bard soul voice gauge doesn't look like the image as of 3.1.0

### ISSUE THREAD

**Issue by Alukah** [skotlex/ffxiv-material-ui#116]
How it looks in-game

![image](https://user-images.githubusercontent.com/19790219/69289176-0994b600-0bd2-11ea-8b41-c0f707b58858.png)

How it's supposed to look

![image](https://user-images.githubusercontent.com/19790219/69289183-10bbc400-0bd2-11ea-811f-da230db1e7ef.png)

I see this was flagged as fixed in October but it still happens https://github.com/skotlex/ffxiv-material-ui/issues/98

**Comment by skotlex** [comment]
Sorry for the inconvenience. I'll check.

**Comment by skotlex** [comment]
First of all, apply the compressed file in #98. I will correct this problem and apply it to the next patch.

**Comment by skotlex** [comment]
If you use the discord version, please apply the compressed file of #98 temporarily.
