### ISSUE TITLE
Change the Color scheme of Black UI

### ISSUE THREAD

**Issue by Kodaigan** [skotlex/ffxiv-material-ui#117]
Greetings Skotlex,

I have come across your Material UI recently, and I am happy to admit, that I fell in love with it. Together with a couple other Mods (such as HD Icons and whatnot), the game looks a lot crisp-ier over all. I love it. 

I enjoy the Black UI the most, as it has everything I want. With Discord I am not so happy, as the dialog box is not the square form as previewed in the black version. (As a sidenote, maybe add an option for Discord, to turn the dialog box to square as well. Unless my Mod install did something wrong, and didn't overwrite the dialog part, I don't know. Point me to that if so please.)

So here is my question about the Black Material UI. Is it possible to change the color scheme as in: Black & light blue? Or does changing colors in the UI mean, that you'd have to personally change it, repack it, and upload it? I'd rather not impose this on you, as this is a singular request and you haven't offered such an option in the ModPacks yet.

Thank you in advance.

Regards
Koda

**Comment by Vec7rex** [comment]
Hello,
you could use the square Dialog Box from the Black UI Version in the Discord UI Version if you want...
just install the Discord UI Version and then install only the "talk_basic" part from the Black UI ;)

**Comment by Kodaigan** [comment]
> Hello,
> you could use the square Dialog Box from the Black UI Version in the Discord UI Version if you want...
> just install the Discord UI Version and then install only the "talk_basic" part from the Black UI ;)
Never thought of that... I'ma try this out real quick. Thanks for the tip!

**Comment by Vec7rex** [comment]
If you want the square •shout• Dialog Box too, then Install "talk_other" as well

**Comment by Kodaigan** [comment]
Ah I see. Well, this tip technically just made this thread obsolete. :'D

Thank you for the headsup!
