### ISSUE TITLE
Day & Night Cycle icon visible in every square Map iteration

### ISSUE THREAD

**Issue by Kodaigan** [skotlex/ffxiv-material-ui#118]
![QrDRU91nHR](https://user-images.githubusercontent.com/8122862/69466664-4523b180-0d85-11ea-9c04-29f771891978.png)
The Day&Night Cycle icon is still visible in the square map iteration and is confusing at first glance.

Hiding it should solve the problem.

**Comment by skotlex** [comment]
But I don't think it's desirable because if you hide that, you'll give up one function of the mini-map.
But since it's what you want, I personally intend to get rid of it and provide it. However, I will not include it in the option, so please understand.

**Comment by Kodaigan** [comment]
I understand that this function is important for certain situations (such as fishing, where time of day and night matters. In general however, it is unecessary.
So you say that you will work on it, how will you provide it? Inside the main Discord Modpack?

**Comment by skotlex** [comment]
I will provide only the files that have been modified for you personally. However, it is not included in the main packing. If the modification is completed, I will upload the corresponding option modpack here.

**Comment by Kodaigan** [comment]
Ah, okay. Yeah sure, the file itself is all I can ask for. Thank you very much.

**Comment by skotlex** [comment]
[remove-EWSN-indicator.zip](https://github.com/skotlex/ffxiv-material-ui/files/3882335/remove-EWSN-indicator.zip)
Please download it and apply :p

**Comment by Kodaigan** [comment]
> 
> 
> [remove-EWSN-indicator.zip](https://github.com/skotlex/ffxiv-material-ui/files/3882335/remove-EWSN-indicator.zip)
> Please download it and apply :p

Done. It also works as intended. Thank you very much! :D
