### ISSUE TITLE
Have you thought about new a design beside the Black UI & Discord UI?

### ISSUE THREAD

**Issue by Kodaigan** [skotlex/ffxiv-material-ui#119]
Have you had thoughts about creating and adding a new design? Currently you offer 2 UIs that are very night friendly (dark mode in Discord).

Do you think you could work on a brighter design?

**Comment by skotlex** [comment]
Since support for the two versions is limited at the moment, we will have to think about it next year. And I want to make a bright theme if possible, but I am not sure yet. (At present, the bright theme is not structurally designed for me to set the color.)

**Comment by Kodaigan** [comment]
Ah, I see. Good to know, thanks!
