### ISSUE TITLE
Icons misaligned with selection border

### ISSUE THREAD

**Issue by nijow90** [skotlex/ffxiv-material-ui#122]
The new Icons look really neat as they are, but once you select a party member it looks really awkwardly misaligned with the highlighted border, is that intentional?

https://media.discordapp.net/attachments/605448347603566616/656516633782779934/unknown.png

**Comment by skotlex** [comment]
Unfortunately, it is not possible to adjust that location of the texture. 
It's a structural problem.

**Comment by skotlex** [comment]
Now that I checked again, it seems possible. I'll tell you again after the experiment.

**Comment by skotlex** [comment]
![주석 2019-12-22 032036](https://user-images.githubusercontent.com/31692408/71312380-74553d80-246d-11ea-98a0-d519a35da026.png)
[adjust-partylist-select-border-height.zip](https://github.com/skotlex/ffxiv-material-ui/files/3991703/adjust-partylist-select-border-height.zip)
