### ISSUE TITLE
Missing mount icon

### ISSUE THREAD

**Issue by AltanSipdrae** [skotlex/ffxiv-material-ui#123]
I like the icon design you made replacing the old one from the market board and NPCs. However I believe you missed one, it is the mount icon, when you can purchase one from an NPC, it's still the old "star in a square" icon. Following your style, a horse or a saddle would be more fitting. :)

EDIT: on a 2nd thought, I went to take you a screenshot to illustrate what I'm saying, this is when I realized that it's an icon for "miscellaneous items" including more than mount so... I dunno, but it still look strange nonetheless with all the other redesigned
https://i.imgur.com/lHSD6NX.png

**Comment by skotlex** [comment]
I corrected the issue in this version of 3.1.5. 
https://github.com/skotlex/ffxiv-material-ui/releases/tag/3.1.5
This is a patch note. Please check the latest version :p

**Comment by AltanSipdrae** [comment]
Still a star but at least it's cooler now :D
