### ISSUE TITLE
Option for DoH/DoL job icon color

### ISSUE THREAD

**Issue by AltanSipdrae** [skotlex/ffxiv-material-ui#124]
I think it'd be neat to add color to DoH/DoL job icons. Always found it kinda sad that they're just grey.
The pins they made actually use a job color for both, which would be purplish for a crafter and yellow for a gatherer.
https://cdn-prod.scalefast.com/public/assets/img/resized/squareenix-store-v2/83b70d1eea71e083ebeb14583e7f184d_KR_369.jpg
https://cdn-prod.scalefast.com/public/assets/img/resized/squareenix-store-v2/67a5fca0eed7860bb0cb60ecab4c11d9_KR_369.jpg

I really like it and would like to see this added in the mod, as option or not! :)

**Comment by skotlex** [comment]
This is what I thought too. I will add a different color as a default.

**Comment by Vec7rex** [comment]
Until it is ready, you can use these if you want.

![Hydaelyn UI](https://user-images.githubusercontent.com/57547484/71132104-deb07880-21f6-11ea-81d0-f4cf827f7426.png)

[Hydaelyn UI (Job Icons)](https://www.xivmodarchive.com/modid/9666)

**Comment by AltanSipdrae** [comment]
I have a question for you guys but I don't really know where to chat with you so I'm gonna ask here:
which index do you get all those icons from? There's so many I can't find it with FFXIVExplorer. I've been searching for mount icon and macro icon

**Comment by skotlex** [comment]
![round_background_job_icon](https://user-images.githubusercontent.com/31692408/71303691-813b4800-23ff-11ea-9593-be7f9e4382db.png)
Is this good for you? You can use what you like.
[round-background-job-icon.zip](https://github.com/skotlex/ffxiv-material-ui/files/3991093/round-background-job-icon.zip)

**Comment by skotlex** [comment]
Come to think of it, I don't know which one you use, round or edged. 
If you need an edged border, tell me.

**Comment by AltanSipdrae** [comment]
This is perfect thank you <3
