### ISSUE TITLE
Agro in alliance raid

### ISSUE THREAD

**Issue by AltanSipdrae** [skotlex/ffxiv-material-ui#125]
I like the new UI design for alliances. But the way agro is displayed right now doesn't catch the eye. I think the agro 'button" below debuff should be red instead of light yellow, you could spot it way faster.

**Comment by skotlex** [comment]
I am thinking of a way other than the current one to improve it. I'll give you an answer after the experiment, too

**Comment by lucande** [comment]
I have been following this mod for a while but I don’t like the new design.  The text for each of the alliance members look jarring and out of place imo and don’t fit the theme.  But maybe that is just my opinion.  The rest of the design changes are stellar though!

**Comment by lucande** [comment]
As in the debuff and aggro text:  I do like thinner up bar though!

**Comment by skotlex** [comment]
As you say, I am trying to express in small symbols rather than in text.

**Comment by skotlex** [comment]
What do you think about this?
![Untitled-1](https://user-images.githubusercontent.com/31692408/71448179-f8643980-277b-11ea-9740-09bd9dd3256f.png)

**Comment by Vec7rex** [comment]
it Looks cool !

but i would swap the Colors
debuff - blue (like the aggro indicator)
aggro - red

**Comment by AltanSipdrae** [comment]
I like it too, I would keep debuff purple but agro needs a bright red

**Comment by vaultor** [comment]
I'd like the same:
debuff - purple
aggro - bright red

**Comment by skotlex** [comment]
I've changed the color, but I think it's unnatural. I think blue is better than red. (aggro)
Besides, it is not good to have various colors because the indicator is blue.
![주석 2019-12-28 200112](https://user-images.githubusercontent.com/31692408/71542703-d56c9c00-29ac-11ea-9c6f-7da69ecf90b1.png)

> What do you think about this?
> ![Untitled-1](https://user-images.githubusercontent.com/31692408/71448179-f8643980-277b-11ea-9740-09bd9dd3256f.png)

**Comment by AltanSipdrae** [comment]
I personnally like it better red

**Comment by skotlex** [comment]
No, I don't want to separate the options with this. I'll run some more tests and say it again.

**Comment by skotlex** [comment]
Which would be better...
![Untitled-1](https://user-images.githubusercontent.com/31692408/71545965-f9dc6e80-29d4-11ea-9794-8a3cbad9748e.png)
![Untitled-2](https://user-images.githubusercontent.com/31692408/71545966-fb0d9b80-29d4-11ea-978e-b003a6893919.png)

**Comment by natyusha** [comment]
I like the red for aggro and blue for debuff since those colours match the rest of the ui.

**Comment by deonfoxfangs** [comment]
I also prefer the red aggro, blue debuff (top screenshot in latest post).
