### ISSUE TITLE
Quest market is not visible on the minimap if it points to the north

### ISSUE THREAD

**Issue by jairjy** [skotlex/ffxiv-material-ui#127]
Since this mod changes the way the minimap looks, the north edge is more obscure. If you have an orange quest marker that is pointing directly to the north, it will not be visible since the north edge is above it.

**To Reproduce**
1.- Accept any quest that requires you to go to any place.
2.- Go to the same map where the quest objective is.
3.- Place your character on the south of the quest's objective, far away so the minimap should create a marker pointing to the north.
4.- Notice how the market cannot be seen.

**Comment by borktastic** [comment]
Having an option for a true square map (again) would also be a welcome addition as this would solve the the above, unless the goal now is to move away from QoL and end up in fork hell?

**Comment by skotlex** [comment]
I'm trying many things, but I'm worried because I don't have a design that I like. Maybe it takes a lot of time. I apologize in advance.

**Comment by borktastic** [comment]
You could always stick to square (former) and circle and let people just pick their flavor. 
https://imgur.com/a/VdaTGac was already decent in my opinion. Not that I would ever use a circle minimap to begin with but I can see appeal. Perhaps have the option to hide the buttons/icons for those who hate it (like me) as well and you're good to go!

**Comment by skotlex** [comment]
Well, I'm sorry. I don't understand. Can you explain it to me more easily? 
The translator's not performing well. T_T

**Comment by borktastic** [comment]
Make 2 options: Circle and Square Minimap (like how it was in <v3.10). Then add the option to hide icons like how it was in <v3.10 by default(?). We get a clean looking minimap then.

**Comment by bonermobile** [comment]
I would also like an option for the previous style of square minimap, the one that changed the mask to a square and didn't simply add a square border. I would also like to request an option for the previous style, the thin 1 pixel border and not the new thick style border. I don't think the new thick border fits very well with the UI as nothing else seems to use that styling, all the UI panes are simple black 1 pixel borders for example.

**Comment by skotlex** [comment]
@borktastic Thank you for your brief explanation. Of course there is that way as well as you say. But I am worried because I want to refrain from unnecessarily increasing options as much as possible.

@bonermobile I respect your opinion because each person has different ideas. But now I don't have the intention to abandon this design. It may be inconvenient, but if you prefer the previous design, please apply the option below version 3.1.0. Sorry... :(

**Comment by skotlex** [comment]
I lost. I can't come up with a good idea, so I'll create a separate option to remove N.

**Comment by borktastic** [comment]
Maybe just have 2 "clean" minimap options then, circle and square?

**Comment by skotlex** [comment]
The four currently existing mini-map options will provide the option to remove N.

**Comment by ZeroMaki** [comment]
any chance to get the W E S back?

**Comment by ZeroMaki** [comment]
else any chance you can tell me what files are for minimap so I can just take from 3.0.0 I preferred that minimap

**Comment by skotlex** [comment]
What do you think about this? #132 
![주석 2020-01-11 112421](https://user-images.githubusercontent.com/31692408/72198025-94c05880-346b-11ea-8c32-a5d2c5162d59.png)
![주석 2020-01-11 115951](https://user-images.githubusercontent.com/31692408/72198026-968a1c00-346b-11ea-84f9-0c59922c319a.png)

**Comment by borktastic** [comment]
First seems nice but the square one... Could we have one without the circle border?

**Comment by ZeroMaki** [comment]
I like it, E clashes a little with the buttons tho, I liked having the buttons on the old original 3.0.0 design but in this circular design and such, their usefulness to me feels like its not worth how it drags the design down, the options on it is in the settings of the game so it wouldn't be locked out and you can zoom with scroll if I recall.

**Comment by skotlex** [comment]
round
![72198025-94c05880-346b-11ea-8c32-a5d2c5162d59](https://user-images.githubusercontent.com/31692408/72681606-91326e80-3b08-11ea-8416-0e0a9e6e0c68.png)

square
![주석 2020-01-19 220950](https://user-images.githubusercontent.com/31692408/72681607-94c5f580-3b08-11ea-97fd-9e0fe949134c.png)

I can't satisfy everyone, but I think this is appropriate.
And I will provide an option to remove EWSN.

**Comment by ZeroMaki** [comment]
I love the square one
