### ISSUE TITLE
(Discord) Party list border overlaps alliance/leader indicators

### ISSUE THREAD

**Issue by deonfoxfangs** [skotlex/ffxiv-material-ui#128]
https://i.imgur.com/58HJt6C.png

The "Alliance #/Party" label and the party leader marker are outside of the black border created by the party list in v3.1.5. Would like to see the border expanded to the left a little bit anyway since it's kind of a snug fit on the job icons but at least enough to accommodate these indicators would make it look a lot cleaner.

Thanks for your continued work on this.

**Comment by Vec7rex** [comment]
the boarder is as far as possible on the left side

**Comment by deonfoxfangs** [comment]
Hmm, alright, fair enough. For some reason this just gives me more of a sense of "this is outside the container" than the official or the 3.1.0 party list (though I do notice now those are at the same spot on the left). I think it's because it's a hard border instead of just a gradient fading out. Maybe just a personal preference thing.

**Comment by skotlex** [comment]
I have received several inquiries from various people about this, and I have made the following corrections. (In fact, there has not been much difference from the original.)
![Untitled-1](https://user-images.githubusercontent.com/31692408/71447931-b1c11000-2778-11ea-92e6-01b8625c8e80.png)

**Comment by deonfoxfangs** [comment]
That looks better to me, thanks!

**Comment by Vec7rex** [comment]
it Looks similar to the Background i created for my Job Icon pack ;)
