### ISSUE TITLE
Option to Remove Hexagons From Dialogue Box

### ISSUE THREAD

**Issue by deonfoxfangs** [skotlex/ffxiv-material-ui#129]
Would it be possible to have an option at least to remove the hexagons from dialogue boxes? In my opinion they feel a little out of place, not really used elsewhere in the game and I think a cleaner look would match everything else better.

![dialogue_hex](https://user-images.githubusercontent.com/52505891/71489048-b7a70780-27f1-11ea-82a2-de3e14df511c.png)

**Comment by vaultor** [comment]
I second this. I find the the hexagons to be out of place and slightly distracting.

**Comment by skotlex** [comment]
It's done
[round-talk-no-hexagon.zip](https://github.com/skotlex/ffxiv-material-ui/files/4007006/round-talk-no-hexagon.zip)

**Comment by skotlex** [comment]
I'm going to change this to the default specification for the next patch
