### ISSUE TITLE
Chat tab resize

### ISSUE THREAD

**Issue by ArutanSipdrae** [skotlex/ffxiv-material-ui#130]
A big issue I always forget to report is that with the transparency we don't see the resize "button" we can grab to resize the chat tab when we split a tab out
![Sans titre 2](https://user-images.githubusercontent.com/34192226/71593760-93229680-2b35-11ea-88ef-3219fcc60765.png)

**Comment by skotlex** [comment]
Like a mini-map, I hid it for beauty purpose, but I'll see if I can make it happen when I put my mouse up.

**Comment by AltanSipdrae** [comment]
The mini map has well defined border so it's not really an issue to find the corner contrary to the transparent chat log :p

**Comment by skotlex** [comment]
normal (discord)
![주석 2020-01-10 230732](https://user-images.githubusercontent.com/31692408/72158785-60fb1980-33fe-11ea-94b9-d6669f5c0ffd.png)

hover (discord)
![주석 2020-01-10 230749](https://user-images.githubusercontent.com/31692408/72158797-648ea080-33fe-11ea-9a7f-c2da81a285ce.png)

The color of the black version will be red for the color.

**Comment by AltanSipdrae** [comment]
What does it looks like with a transparent chat?

**Comment by skotlex** [comment]
Like this
![주석 2020-01-11 102513](https://user-images.githubusercontent.com/31692408/72196598-b6661380-345c-11ea-930d-66f808536d8c.png)
![주석 2020-01-11 102528](https://user-images.githubusercontent.com/31692408/72196601-b8c86d80-345c-11ea-8510-4f5778121bfd.png)

**Comment by ArutanSipdrae** [comment]
2nd one fit with the scrollbar it's more harmonious

**Comment by skotlex** [comment]
The second image is the color of the mouse hover, and the first is the image of the normal state. If you don't mind, I'll apply this to the next version and offer it as a separate option.

**Comment by ArutanSipdrae** [comment]
Fine with me, looks neat
