### ISSUE TITLE
Non-max HP Indicator

### ISSUE THREAD

**Issue by vaultor** [skotlex/ffxiv-material-ui#131]
The current icon used to indicate non-100% HP for party members seems a bit cluttered to me. The exclamation "!" symbol in such a small triangle doesn't stand out and adds visual noise to the already crowded party panel.

I would prefer a simple down-pointing arrow (like the original one) but slightly bigger and positioned right below the party number for aesthetic reasons. Any thoughts?

**Comment by AltanSipdrae** [comment]
I do think that the actual ! in the triangle is a bit obnoxious, makes me think of a construction site or road accident with the yellow color

**Comment by Siiper** [comment]
2nd this and imo the "!" symbol kinda out of place as well, would be nice to have an option to switch back to original one.

**Comment by FrUct1s** [comment]
Agreed.
I prefer the original arrow pointing down - can we make this an option in the Options Folder under Party?

**Comment by skotlex** [comment]
I've only changed the color.
![주석 2020-01-10 223155](https://user-images.githubusercontent.com/31692408/72156496-0ca16b00-33f9-11ea-812e-3bcc0abcf560.png)

**Comment by FrUct1s** [comment]
I'll check again tonight which ones from Options I am using or if I am using any and try with a color.
So it seems the Warning Sign is the information that it can't find the icon

**Comment by skotlex** [comment]
@FrUct1s Well, I'm sorry. I didn't understand you very well. The translator's not working T_T

**Comment by AltanSipdrae** [comment]
It's better but not best, same color as hp bar so not much visible

**Comment by FrUct1s** [comment]
![image](https://user-images.githubusercontent.com/58904408/72178319-fb4d6400-33e2-11ea-8b91-d459eede4fb1.png)
This is with glowing icons OPTIONS
I think it is missing the correct icon for the down arrow

**Comment by skotlex** [comment]
@FrUct1s 
The glowing icon and the non-hp max indicator are different options. It has nothing to do with this. (chocobo icon: 03_Icon / non-max HP indexer: 02_Partylist). Don't mind the job icon, but I'd appreciate it if you could just tell me about the indicator.

@AltanSipdrae 
So, do you have any good ideas? I don't think this is so bad. :p

**Comment by skotlex** [comment]
How about this one? 
PS.
For your information, it is no longer possible to move the indicator to the left.
![주석 2020-01-11 123553](https://user-images.githubusercontent.com/31692408/72198328-49a84480-346f-11ea-9688-580d92c2d707.png)

**Comment by FrUct1s** [comment]
All 4 Partylist_GaugeHP colors have the same problem for me
Options -> 02Partylist -> Emerald Green, Purple, Dark Red and Dark Blue

![image](https://user-images.githubusercontent.com/58904408/72203042-f631f880-3466-11ea-846a-1c7e8f641296.png)

**Comment by skotlex** [comment]
That will also apply in the next version.

**Comment by vaultor** [comment]
> How about this one?
> PS.
> For your information, it is no longer possible to move the indicator to the left.
> ![주석 2020-01-11 125005](https://user-images.githubusercontent.com/31692408/72198454-eb7c6100-3470-11ea-84c7-963dd39a1ab7.png)

This seems good :)
