### ISSUE TITLE
Minimap design

### ISSUE THREAD

**Issue by ZeroMaki** [skotlex/ffxiv-material-ui#132]
Is it possible to get a version with the W E S brought back please? I went back and took 3.0.0 design for now but would be nice if I didn't have to

**Comment by skotlex** [comment]
I'm currently thinking about it because I have a lot of suggestions about the mini-map. I think this will take some time...

**Comment by ZeroMaki** [comment]
as a raider having to remember east and west can be a delay that causes death

**Comment by skotlex** [comment]
I was overlooking that part. Thank you for telling me.

**Comment by ZeroMaki** [comment]
no worries thanks a lot =)

**Comment by Odjn1987** [comment]
And make a square one again as well ♥ loved it, otherwise awesome work as usual

**Comment by AltanSipdrae** [comment]
> as a raider having to remember east and west can be a delay that causes death

Wait but aren't you locking the map on the north? This is the best thing to do if you raid honestly.

**Comment by ZeroMaki** [comment]
@AltanSipdrae the map doesn't move but I do and I can't remember west or east as either side, I need to see the letter else I won't know fast enough, rather slow actually and that is a big issue

**Comment by Aida-Enna** [comment]
+1 for having E/W/S back for raid. Keep up the awesome work!

**Comment by skotlex** [comment]
Please let me know what you think of the topic #127

**Comment by skotlex** [comment]
Discussion seems better on that thread. I'll end the discussion here.
