### ISSUE TITLE
Selected "completed quest" category is not highlighted

### ISSUE THREAD

**Issue by AltanSipdrae** [skotlex/ffxiv-material-ui#133]
![dsfsdf](https://user-images.githubusercontent.com/34192226/71842906-0478c100-30c3-11ea-9f8d-83143e97623b.png)
 Here we can see that the chosen category doesn't highlight, contrary to other places like the armoire
![dsfsfds](https://user-images.githubusercontent.com/34192226/71842953-1e1a0880-30c3-11ea-9f11-8cd29e07033b.png)

**Comment by skotlex** [comment]
I already know the fact, but I have sacrificed "completed quest" for another UI (e.g., party finder, duty finder). These three UI interactions are interconnected, so it is impossible to modify only one side.
