### ISSUE TITLE
Incorrect Coloring of Inventory Preview

### ISSUE THREAD

**Issue by area402** [skotlex/ffxiv-material-ui#134]
**Screenshots**
![image](https://user-images.githubusercontent.com/46609758/72237530-24a60400-361e-11ea-8474-15dd5201136f.png)

**Describe the image**
At inventory preview, Equipments are usually colored with white or green depending on their own spiritbond progress (max or not).
Now they are all white even if brand new.

**Comment by skotlex** [comment]
fixed it. I'll reflect it on the next patch.
![Untitled-1](https://user-images.githubusercontent.com/31692408/72683808-f9d81600-3b1d-11ea-868a-a711ffba3d25.jpg)
