### ISSUE TITLE
How to remove border in party list?

### ISSUE THREAD

**Issue by jamesxiang11** [skotlex/ffxiv-material-ui#135]
I saw people in stream with a transparent border but mine has one. 
![image](https://user-images.githubusercontent.com/38471190/72280787-257f6b80-3607-11ea-82b8-bc442bf68688.png)

And this is what others have:
![image](https://user-images.githubusercontent.com/38471190/72280863-58c1fa80-3607-11ea-8820-ba7a8b782f1b.png)

**Comment by skotlex** [comment]
I will correct this through the #128 issue, but if this is not to your liking, you can disable that texture (texture name: partylist_bg).

**Comment by jamesxiang11** [comment]
Where can I disable that texture?

**Comment by skotlex** [comment]
![주석 2020-01-15 212427](https://user-images.githubusercontent.com/31692408/72433775-6f21af00-37dd-11ea-95d0-42f80deac8d5.png)

**Comment by jamesxiang11** [comment]
Thanks. After disabling, I am seeing this.
![image](https://user-images.githubusercontent.com/38471190/72436351-326a9f00-376e-11ea-8bd0-65b921c87773.png)
