### ISSUE TITLE
Disable hortbar skin

### ISSUE THREAD

**Issue by Rhess86** [skotlex/ffxiv-material-ui#137]
Hi, i loved your mod but one thing really bothered me was the hortbars, you add a little outline to it right, its cool but idk why it bothered me, i tried to find the specific file to disable on ffxivtools but i was unable to find. 
So i was wondering if you could help me disable just the hotbars skin, i want to keep the original.
I'm using the discord skin.
Thanks in advance.

EDIT: Oh and the chat also, i want to keep the original chat, please and thank you.

**Comment by skotlex** [comment]
:p
chat: chatlog
hotbar: iconA_Frame

**Comment by Rhess86** [comment]
Thanks!!
