### ISSUE TITLE
Unreadable dialogue boxes in new trial

### ISSUE THREAD

**Issue by Alukah** [skotlex/ffxiv-material-ui#138]
**Screenshots**
https://i.imgur.com/Oz0kzTB.png

**Describe the image**
Some pop up dialogue boxes show up like that in Ruby Weapon, might be the ones that are colored blue in the default theme?

**To Reproduce**
Please explain how you can access the menu:
Just run Ruby Weapon trial

**Comment by skotlex** [comment]
![주석 2020-03-05 013653](https://user-images.githubusercontent.com/31692408/75901670-3d929f00-5e82-11ea-9893-ec47701c385f.png)
![주석 2020-03-05 013641](https://user-images.githubusercontent.com/31692408/75901673-3f5c6280-5e82-11ea-9c9d-54b0d6ba36f2.png)

This is an image of the black version. Is this okay?

**Comment by Alukah** [comment]
Yeah that looks well, either the issue is with discord version or something bugged on my end when I installed it.

**Comment by skotlex** [comment]
![주석 2020-03-07 023006](https://user-images.githubusercontent.com/31692408/76107226-95b0d900-601b-11ea-9d1c-1e1a6a43e8cf.png)
discord ver
