### ISSUE TITLE
GPose Menu Icon Issues

### ISSUE THREAD

**Issue by ArynBlack** [skotlex/ffxiv-material-ui#139]
**Screenshots**
https://imgur.com/a/n3uZ4kW

**Describe the image**
Due to the new additions to the Gpose system (saving settings and other presets) there's a number of offset images and the like when clicking on these features and within the menu itself.

**To Reproduce**
Simply open/enter gpose mode and access the menu settings (default R for some to show/hide the menu)

**Comment by skotlex** [comment]
black
![주석 2020-03-08 113729](https://user-images.githubusercontent.com/31692408/76156187-00f0cd00-613a-11ea-88c9-1de2b0a8884a.png)

discord
![주석 2020-03-08 121631](https://user-images.githubusercontent.com/31692408/76156189-051cea80-613a-11ea-9f57-0165bf238ef9.png)
