### ISSUE TITLE
Feedback on enemy list

### ISSUE THREAD

**Issue by Alukah** [skotlex/ffxiv-material-ui#140]
**Is your feature request related to a problem? Please describe.**

The new icons chosen for enemy list are fully a downgrade, the base colors going from blue, yellow, orange and red helped to quickly identify your current aggro, but the new change makes them all blue except for the last, with different icons that are hard to tell apart mid combat. 

If the goal is to keep it simple I think the old simple shapes with easily identifiable colors is better than the current complex shapes that you can't tell apart mid battle.

**Comment by natyusha** [comment]
The icons are fine since they are the same as the threat level of monsters and add a nice visual element to the enmity list. I do agree on the coloration though.

**Comment by Felys1998** [comment]
Would be nice to break this out into an option.

**Comment by skotlex** [comment]
![주석 2020-03-07 025301](https://user-images.githubusercontent.com/31692408/76108925-d100d700-601e-11ea-889c-a7c795db17a7.png)
I tried to make a color similar to the original. 
Unless there is a big problem, I will change this to the basics.

**Comment by natyusha** [comment]
Perfect!

**Comment by Alukah** [comment]
That looks pretty good.

**Comment by Felys1998** [comment]
That looks good.
