### ISSUE TITLE
Mod preview

### ISSUE THREAD

**Issue by AmenneHolelane** [skotlex/ffxiv-material-ui#144]
Readme says that it’s a work in progress. What needs to happen to get that section working? If it isn’t too code heavy, I can write documentation and provide screenshots, I’m just a beginner with coding and can’t really do that...

**Comment by skotlex** [comment]
Are you talking about the "preview option" in README?

**Comment by AmenneHolelane** [comment]
Correct

**Comment by AmenneHolelane** [comment]
Basically, I’m wondering how can I help make that section?

**Comment by skotlex** [comment]
It's just a list of images, so you don't have to help. However, I have neglected it until now because it is not important, but I will try to finish it within this month.

**Comment by AmenneHolelane** [comment]
One last question. On some of the options there’s a note that says DISCORD ONLY or BLACK ONLY. Are those the only options that require use of a specific style or should I assume they all must use the same style. For example, the discord circle minimap. Can that be used on both discord and black styles or just discord?

**Comment by skotlex** [comment]
'minimap' can be chosen according to preference, but 'window selected border' must be the version specified in the note.

**Comment by AmenneHolelane** [comment]
Adjusted the PR to reflect that :)

**Comment by skotlex** [comment]
I'm sorry for the delay in answering. I checked the PR, but the contents got too long and I'm going to revise it. Therefore, you did a great job, but approval will be difficult. But I will write a new document based on your PR, so please do not delete the PR.

**Comment by skotlex** [comment]
Document creation is complete. Thank you for your help.
