### ISSUE TITLE
(Discord Theme) Recipe Tree Hover Issue

### ISSUE THREAD

**Issue by robotbrain** [skotlex/ffxiv-material-ui#146]
**Screenshots**
![image](https://user-images.githubusercontent.com/3117019/76023333-f98db180-5ef6-11ea-8c2b-72bc82891f89.png)

**Describe the image**
Highlighted items in the recipe tree look wrong/bad

**To Reproduce**
1. Open the crafting log and pick a recipe
2. Right click and click recipe tree
3. Hover over any item in the tree

**Comment by AmenneHolelane** [comment]
@robotbrain #142 mentions recipe tree so I’m assuming that it’s covered but I’m not sure

**Comment by skotlex** [comment]
Same as the content in #142. This will be revised.

**Comment by skotlex** [comment]
black
![주석 2020-03-08 101549](https://user-images.githubusercontent.com/31692408/76154789-d72dab00-6125-11ea-97b8-56b5bce3f10b.png)

discord
![주석 2020-03-08 092727](https://user-images.githubusercontent.com/31692408/76154792-dd238c00-6125-11ea-9746-da331584d3f6.png)
