### ISSUE TITLE
I'm looking for someone to make a material UI with me

### ISSUE THREAD

**Issue by skotlex** [skotlex/ffxiv-material-ui#148]
I'm still enjoying FF14, and as long as I keep playing this, I want to keep developing this mod. But I've reached the limit of my skills, so I'd like to get someone to develop the UI with me.

I don't ask for grandiose things, but I want someone who knows how to use image editing programs like Photoshop and can express the icons to fit the UI's Theme. 

There's no pressure on deadlines because it's a hobby.
I look forward to the participation of people who want to develop material UI together.

Contacts
- Twitter: @skotlex 
- Discord: SKOTLEX#3060

**Comment by herjoyfulness** [comment]
I've added you through Discord, I might be able to help with my skillset.

**Comment by skotlex** [comment]
Thank you for your help. I accepted your request.
