### ISSUE TITLE
Enemy List, threat logo

### ISSUE THREAD

**Issue by reketoUMA** [skotlex/ffxiv-material-ui#149]
Amazing theme.
But I think the threat logo in enemy list is not so obvious than original logo.
When playing TANK, it’s very important, but I think it’s not enough conspicuous.

**Comment by reketoUMA** [comment]
Maybe simply use square and triangle is easier to notice it when threat change.

**Comment by skotlex** [comment]
I have already made changes to this in issue #140, in the 3.1.7 patch. 
Do you think this is not enough?

**Comment by reketoUMA** [comment]
While, maybe your icons is good enough but I cannot adapt the change. I think it’s my personal problem and you needn’t modify it in master branch. Just keep it is OK. I can disable this feature by myself.
Anyway, thank you for you hard work to this theme!

**Comment by skotlex** [comment]
It seems to be the limit of my ability. I'll see if there's a better way.
