### ISSUE TITLE
Map Icon Option

### ISSUE THREAD

**Issue by AustinTillotson** [skotlex/ffxiv-material-ui#150]
Is there an option for the minimap icons that does not have the rotating yellow dotted line surrounding important icons like quest markers. I find it distracting but have been unable to personally edit it so that TexTools will accept it. If not, no problem, I can go use a previous verision's NaviMap.

**Comment by skotlex** [comment]
Oh, I'm sorry. This is my mistake. It was only used briefly in the test version, but I forgot to restore it. 
I'm going to release the next new version in a few days, and I'll revise it and upload it.
