### ISSUE TITLE
(BLACK) Window borders different color than body

### ISSUE THREAD

**Issue by deonfoxfangs** [skotlex/ffxiv-material-ui#151]
With the release of v3.2.0, the BLACK version of the UI has windows with slightly different border colors (#161516) than the color of the body (#161416). It seems like a small difference but on my monitor at least there is a noticeable "line" between them.

![image](https://user-images.githubusercontent.com/52505891/77864533-11efa400-71f7-11ea-9303-0b527d20f4e2.png)

**Comment by skotlex** [comment]
It's different from what I thought, but it's my intention that the border and body color are different anyway. This is not only black but also discord. This was also applied in previous versions, not just 3.2.0 changes.

**Comment by skotlex** [comment]
My intention is that the color of the border should be darker than the body, and if this is wrong it should be corrected.

**Comment by deonfoxfangs** [comment]
I think the result ends up that the body is a little more.. magenta? And the value of the body is actually slightly lower since you're just dropping a little green but keeping r/b the same.

Border:
![image](https://user-images.githubusercontent.com/52505891/77868245-7cf5a680-7208-11ea-986f-3537e1c4a6c8.png)

Body:
![image](https://user-images.githubusercontent.com/52505891/77868320-ce059a80-7208-11ea-86d1-5216162416a1.png)

To my eyes as I'm looking at it I see the body as more "red" which is why I brought it up as an issue. I had switched over to black from discord with this release so maybe it was correct in discord before hence why I thought it was just a 3.2.0 issue.

**Comment by deonfoxfangs** [comment]
I'm also comparing it to this screenshot from the examples that doesn't exhibit this effect:

![image](https://user-images.githubusercontent.com/52505891/77869312-0b1f5c00-720c-11ea-84cb-d91901fddda9.png)

**Comment by skotlex** [comment]
I need to check this out. I'm away for a few days for personal reasons, so I hope you'll excuse me if I have delay have an answer.

**Comment by skotlex** [comment]
(※ The image is a 1000% increase in screenshot)
border
![주석 2020-04-07 212456](https://user-images.githubusercontent.com/31692408/78668862-54f7f880-7916-11ea-9ced-14433915ed5c.png)

body
![주석 2020-04-07 212510](https://user-images.githubusercontent.com/31692408/78668875-59241600-7916-11ea-96cb-187b11537141.png)

The colors I intended were border (#1111111) and body (#212121) but I ask for your understanding because there is a loss in the dds.
![주석 2020-04-07 212656](https://user-images.githubusercontent.com/31692408/78668972-87095a80-7916-11ea-9b5d-78a58c4c3841.png)

**Comment by deonfoxfangs** [comment]
That should work. I'm not sure of the technical aspects of compression (I'm assuming) in the dds in terms of how it will end up in-game but the two I see should work better I think.

Thanks!
