### ISSUE TITLE
Gearset Icons

### ISSUE THREAD

**Issue by PolarBroOmega** [skotlex/ffxiv-material-ui#152]
My suggestion is to update the gearset icons that you place on your hotbar, I absolutely love all the options to change the appearance of the job icons and would love to be able to view them on the hotbars to be able to see every time I switch to that job!

 Unless that's an option that I somehow missed, but I haven't been able to find it. Thank you for your work, your UI is by far my favorite!

**Comment by skotlex** [comment]
Thank you for using my work. I didn't work on it because I thought it would be unnatural, but I'll try it this time.

**Comment by PolarBroOmega** [comment]
Thank you! I would be overjoyed to be able to see them! :D Amazing work
thus far!

**Comment by natyusha** [comment]
Personally, I just swapped the gearset icons with their respective job crystals. That still leaves classes and DoH/ DoL with the default though.

**Comment by PolarBroOmega** [comment]
> Personally, I just swapped the gearset icons with their respective job crystals. That still leaves classes and DoH/ DoL with the default though.

It's one way yeah, I just feel it's a bit too difficult to see which is which for some of them.

**Comment by skotlex** [comment]
![주석 2020-08-09 175335](https://user-images.githubusercontent.com/31692408/89728775-c08bd700-da6a-11ea-83f4-2512588fb834.png)
It will be included in option "contents-glow-job-icon" of the next patch.
