### ISSUE TITLE
White text dialogue

### ISSUE THREAD

**Issue by ArutanSipdrae** [skotlex/ffxiv-material-ui#153]
**Screenshot**
![ffxiv_02042020_162015_276](https://user-images.githubusercontent.com/34192226/78578567-fce6c680-782f-11ea-820f-2a7f885b4425.png)

**Describe the image**
As you can see, the text is in white, but the dialogue box is also white. I don't think I need to say more than that :p

**To Reproduce**
Do Ruby Weapon fight and reach P2.

**Comment by skotlex** [comment]
I will revise and reflect this as soon as possible.

**Comment by skotlex** [comment]
Are you using the latest version? This issue has been corrected in v3.1.7 (#138) and the same problem will occur in versions below.

**Comment by ChaoticSi1ence** [comment]
Not an issue for me on 3.2.0

> Are you using the latest version? This issue has been corrected in v3.1.7 (#138) and the same problem will occur in versions below.

**Comment by skotlex** [comment]
I'm closing the issue because I haven't received a response for days.
