### ISSUE TITLE
Color coordinated cardinal directions on the compass

### ISSUE THREAD

**Issue by PolarBroOmega** [skotlex/ffxiv-material-ui#154]
For people who play with the compass unlocked, when its spinning, "north" gets hidden behind the options to the side of the compass, so if you're looking for West and you want to do that by finding north first, you have to spin your compass to find north, then go west; My thought was changing E/S/W to colors as well so you can just go "West, oh I need green", find it and go there, instead of looking for north first.

**Comment by skotlex** [comment]
![주석 2020-08-09 1832216](https://user-images.githubusercontent.com/31692408/89729295-2f6b2f00-da6f-11ea-8943-74258fb9928c.png)
Which do you think is better?

**Comment by PolarBroOmega** [comment]
In my personal opinion the left is better, higher contrast colors stick out
a bit more!

**Comment by skotlex** [comment]
![주석 2020-08-09 185337](https://user-images.githubusercontent.com/31692408/89729550-c33dfa80-da71-11ea-85c3-0a7409f79561.png)
![icon_35](https://user-images.githubusercontent.com/31692408/89729563-ef597b80-da71-11ea-897c-274f49b614bf.gif)

**Comment by PolarBroOmega** [comment]
Yeah that's perfect, i also love that South is that way, makes it so every
direction is easily identified
