### ISSUE TITLE
Add a description/information somewhere for each mod and what files it needs.

### ISSUE THREAD

**Issue by Rietty** [skotlex/ffxiv-material-ui#155]
Hi, so this is a simplistic problem but I would appreciate it if we can have either one of the two options:

1. Add extra/optional bundled files of the UI that affect only certain things, for example just replacing the icons for the classes for example, that should be possible without having to guess which stuff to import/not import in the modpack, which can be non-intuitive at times.

2. If the above isn't possible just a list of the filenames for each relevant part of the UI so we can enable what we want and not the entire UI replacement.

Thank you!

**Comment by skotlex** [comment]
If I understand correctly, I am already doing so. Options change only the associated texture; non-relevant ones do not. For example, if you apply the options in Navimap, it internally changes only two textures. (Is this what you are saying right?)

**Comment by Rietty** [comment]
Hi, it's more so for example like a mapping of the files to what parts of the UI they are doing. In some list or something somewhere. For example just saying which files change what, if possible. Like PartyListTargetBase, is a bit weird and unclear exactly what it affects, but if we had a simple readme file that had a simple description of what part of the UI it is, it would be great.

**Comment by skotlex** [comment]
I'm sorry but I don't feel the need for it. It is necessary for the ui developer, but for general users, I think the information is useless. :3c

**Comment by Rietty** [comment]
I disagree, would be easier for general users to only enable what features/parts of the UI they wanted but that's okay.
