### ISSUE TITLE
Problem with 3.2.0

### ISSUE THREAD

**Issue by Azuraprincess** [skotlex/ffxiv-material-ui#156]
so ive downloaded and set up the ui as was intended but when i go to the inventory and character profile screens it didnt change anything. is there something im suppose to do that i am forgetting to do? the minimap worked and some of the other stuff but there are still quite a few things that didnt switch.

**Comment by skotlex** [comment]
I think there might be some other problem. If there really were such problems, I would have received a lot of inquiries, but there is no such part at this time. Using the start over function of textool, I recommend resetting and applying it again. And if this doesn't improve, please post a screenshot.

**Comment by Azuraprincess** [comment]
I mean this is my first time using these ui mods and such so is there something I could of done wrong through textool or such?

**Comment by skotlex** [comment]
If this is the first time, there shouldn't be a problem. Is it correct to download Material-UI.v3.2.0.zip file and apply Material-UI (DISCORD) v3.2.0 or Material-UI (BLACK) v3.2.0?

**Comment by Azuraprincess** [comment]
I tried both sides and their are some that just wont change like the job hud for one

**Comment by skotlex** [comment]
I want to know your current condition. Please upload a screenshot.

**Comment by skotlex** [comment]
I'm busy at the moment, so I'll check it out later.

**Comment by Azuraprincess** [comment]
![ffxiv_04192020_210604_975](https://user-images.githubusercontent.com/50385859/79705023-19e4b600-8282-11ea-8cf9-a23831520af3.png)
![ffxiv_04192020_210600_574](https://user-images.githubusercontent.com/50385859/79705026-210bc400-8282-11ea-83d8-88d38addc7c2.png)
![ffxiv_04192020_210554_174](https://user-images.githubusercontent.com/50385859/79705034-2b2dc280-8282-11ea-8462-f1509e0e5ebc.png)
![ffxiv_04192020_210549_557](https://user-images.githubusercontent.com/50385859/79705037-32ed6700-8282-11ea-8e36-2e641d817d20.png)
also showing where other ones did work so that way its not just stuff that didnt work

**Comment by skotlex** [comment]
UI mods only works in dark theme... :p

**Comment by Azuraprincess** [comment]
oh is there a way to switch to this dark theme?

**Comment by skotlex** [comment]
I don't remember the details, but you can change them in character or system settings.

**Comment by Azuraprincess** [comment]
okay thanks sorry about this ill send another post with a close if this works out

**Comment by skotlex** [comment]
Thank you :3
