### ISSUE TITLE
Accessibility add-on

### ISSUE THREAD

**Issue by bekaness** [skotlex/ffxiv-material-ui#157]
**Is your feature request related to a problem? Please describe.**
Would like to add a feature for people who have accessibility issues with certain battle effects, like Charbydis

**Additional context**
I've been trying to complete the BLU#25 quest for over a year, at one point I quit the game over the frustration. I'm a minion collector but I'm hard of hearing and autistic. I get overwhelmed by too much going on, on my screen. I would really appreciate being able to tone down battle effects somehow. I don't even know if this is possible, I've asked everywhere, even gpose doesn't really help with it. I've even tried using the sound alerts that are on the screen. I do not want to beat every challenge, I am just a minion collector and wanted the one that's locked behind #25. I don't have any RL friends who play FFXIV to help me as I have usually asked someone to do it for me in the past in ff11 when I had a hard time. So I can't complete this. It's an accessibility issue for me. Sorry if my explanation is too long, I overshare sometimes. Thank you for your beautiful UI. And thank you for reading my request. If you can't, I understand. :)

**Comment by skotlex** [comment]
Unfortunately, I do not have the authority to modify the effect. You can adjust it through the image below in the game, but this is the best you can do. I'm sorry I didn't help you.
![RUHVix4hSbOdokpqy2tDBizwSO7acZo2kfK9W7yWJ3U](https://user-images.githubusercontent.com/31692408/79975819-89eb7a00-84d6-11ea-9cf2-7ba1cafdd13b.png)

**Comment by bekaness** [comment]
Thank you, this doesn't work for me. I appreciate your reply.
