### ISSUE TITLE
Close Button not Centered Within Border

### ISSUE THREAD

**Issue by natyusha** [skotlex/ffxiv-material-ui#159]
![ffxiv_dx11_2020-04-25_13-00-10](https://user-images.githubusercontent.com/985941/80285737-f3e16a80-86f4-11ea-880b-0ab595144dfb.png)
![ffxiv_dx11_2020-04-25_12-57-02](https://user-images.githubusercontent.com/985941/80285739-f8a61e80-86f4-11ea-843a-36777d9076ae.png)
![ffxiv_dx11_2020-04-25_12-58-53](https://user-images.githubusercontent.com/985941/80285740-fc39a580-86f4-11ea-903e-f242d4a650c5.png)
![ffxiv_dx11_2020-04-25_14-31-29](https://user-images.githubusercontent.com/985941/80287817-8d167e00-8701-11ea-8ab4-b9cce4f76e62.png)

**Describe the image**
The close window button is not aligned in certain windows. The above screenshots are from Eureka's Magia Melder, timeworn maps, the Doman Enclave turn-in screen and Wondrous Tales (though there may be more instances of this issue).

**To Reproduce**
Open windows that have a circle around the close window button and observe the slight misalignment.

**Comment by skotlex** [comment]
![주석 2020-08-09 141254](https://user-images.githubusercontent.com/31692408/89725457-c83b8380-da4a-11ea-83dd-ed87c634ab44.png)
