### ISSUE TITLE
a bug?

### ISSUE THREAD

**Issue by zhouhuichen741** [skotlex/ffxiv-material-ui#161]
I don't know if that's a bug
![4XGU3)FUK) N3A`(BBE G2](https://user-images.githubusercontent.com/50648819/80473073-349ce600-8978-11ea-98bd-55ee055c03f0.png)
![5AL5{A1I5RULN`AG7L5YHGX](https://user-images.githubusercontent.com/50648819/80473079-3797d680-8978-11ea-8f72-4fae8c48c480.png)
![8_C8(40Z~8%LBBMOV5635TI](https://user-images.githubusercontent.com/50648819/80473089-39fa3080-8978-11ea-90a8-45da583a1d6c.png)

**Comment by zhouhuichen741** [comment]
![4XGU3)FUK) N3A`(BBE G2](https://user-images.githubusercontent.com/50648819/80473174-57c79580-8978-11ea-86a9-3817fe5d33e7.png)

**Comment by skotlex** [comment]
I'm sorry for the late reply. I'm not playing games right now, so I'll check later.

**Comment by zhouhuichen741** [comment]
> I'm sorry for the late reply. I'm not playing games right now, so I'll check later.

thanks

**Comment by skotlex** [comment]
![주석 2020-08-09 140500](https://user-images.githubusercontent.com/31692408/89725346-8100c300-da49-11ea-9425-2c564eb94087.png)
I can't change it because it's purposely made to make a difference in height in SQEX.
