### ISSUE TITLE
Changing an UI icon by an another

### ISSUE THREAD

**Issue by Mara-Li** [skotlex/ffxiv-material-ui#163]
Hello !
I want just edit my UI just a bit : i want to change the icon (macro icon) from 066183 by another I made on photoshop. Importing work well, but my game crash after. 
So, I want to know how i can edit icon UI (like you) without crashing my game ?

My icon is just the darkest night with a 2.

**Comment by skotlex** [comment]
There is usually no problem if it is stored according to the format of the original image. 066183 has a format of 8.8.8.8(ARGB) and a size of 40x40. You can save it in this format.
