### ISSUE TITLE
Silver gauge bar background not stretching completely for Bard

### ISSUE THREAD

**Issue by insarius** [skotlex/ffxiv-material-ui#164]
See screenshot, bottom gauge's background doesn't fill up completely. 
It's not really noticeable on 100% or even 120%, but at 140% (see screenshot) and higher it's quite noticeable.
https://i.imgur.com/jfApmRy.png

**Comment by skotlex** [comment]
![주석 2020-08-09 133722](https://user-images.githubusercontent.com/31692408/89725237-48141e80-da48-11ea-951f-693382445573.png)
