### ISSUE TITLE
How to change the icon option between two styles?

### ISSUE THREAD

**Issue by konmoe** [skotlex/ffxiv-material-ui#166]
Hi! I really like these mods! And I want to use the discord style but I prefer the "Glowing icons but ranged DPS have different color" in black style, could you please teach me how to change the icons?

**Comment by skotlex** [comment]
1. apply material-ui(discord).ttmp2
2. apply partylist-glow-job-icon-diff-range-dps-color.ttmp2 in OPTIONS.zip

**Comment by konmoe** [comment]
Thank you!
