### ISSUE TITLE
Red version back

### ISSUE THREAD

**Issue by Postalityjr-hub** [skotlex/ffxiv-material-ui#167]
Any way I can get the red version back? It was awesome and fit my stream theme very well, I recently had to reinstall and noticed it was the sky blue instead :[

**Comment by greevir** [comment]
I second this. I would love to have the red border option.

**Comment by TomoE6826** [comment]
+1 l like red

**Comment by skotlex** [comment]
I'd prefer to accept the demand as much as possible, but the current number of themes I can manage is limited to two. I'd appreciate it if you could understand this. Sorry :(
