### ISSUE TITLE
Rested EXP - Discord Version

### ISSUE THREAD

**Issue by xapher19** [skotlex/ffxiv-material-ui#168]
The rested exp doesn't seem to be showing on the exp gauge. Wondering if this was intentional or a bug, thanks!

**Comment by skotlex** [comment]
![2020-05-01_072339](https://user-images.githubusercontent.com/31692408/82154502-646d4880-98a9-11ea-964c-1016db1f903c.png)
EXP - white
Bonus - white, transparent
