### ISSUE TITLE
SAM Sen Gauge Simple Mode Order Change

### ISSUE THREAD

**Issue by SableCentaur** [skotlex/ffxiv-material-ui#170]
I'm not sure if this is even possible but I thought I'd ask in case it is!
I would like to suggest a change to the simple mode of the Samurai Sen gauge to swap the order of Setsu and Getsu, so that Getsu is on the left and Setsu is in the middle like it is in the normal mode of the Sen gauge. 
![image](https://user-images.githubusercontent.com/20386522/89078800-4eb4de80-d342-11ea-9a6b-83c703ec7424.png)
In the above, the order is Setsu - Getsu - Ka

![image](https://user-images.githubusercontent.com/20386522/89078837-5e342780-d342-11ea-9684-9be55a1f4384.png)
In the above, the order is Getsu (left) - Setsu (top) - Ka (right)

Thank you for your time!

**Comment by skotlex** [comment]
I don't like it either, but unfortunately the only thing that can change it is SQEX. :(
