### ISSUE TITLE
Prelim Notice for 5.3

### ISSUE THREAD

**Issue by Zyian** [skotlex/ffxiv-material-ui#171]
With the announcement of the preliminary patch notes in 5.3 it looks like we have some new UI elements and changes to existing elements coming in the patch.

Available here: https://na.finalfantasyxiv.com/lodestone/topics/detail/4f18bc98879389862f5d3dd61e3b3da623e3670d (NA)

Since it still seems like @skotlex is still taking a break, I do not know the timeline if/when we can expect any updates. But having an issue for other awareness is a good start.

> Thank you for all of your work!

**Comment by skotlex** [comment]
I think I rested for a long time. First of all, thank you for waiting for me. I've already seen the patch preview, and I'm thinking about it. 

For people who still use my work, I'm thinking of responding to patches if possible, but it can take longer than you think. If you take that into consideration, you will be satisfied with your expectations.
