### ISSUE TITLE
Broken Lakeland map

### ISSUE THREAD

**Issue by VitalSuit** [skotlex/ffxiv-material-ui#181]
After uninstalling the previous edition and installing the new 5.3 update the Lakeland map now looks like a bunch of puzzle pieces. This is the only mod I have installed but I don't see anything on textools about a map file being edited.

https://i.imgur.com/Sn0CNFO.png

Edit: This seems to be the only map affected in the open world, unsure of any instanced maps.

Edit #2: actually seems to be a problem with the backup index files as I "started over" and Lakeland is still messed up.

Edit #3: Yeah it was a corrupted index file, nevermind this "issue"

**Comment by skotlex** [comment]
I had the same problem right after the patch. Eventually, I installed ff14 again and uploaded the index backup to https://github.com/skotlex/ffxiv-material-ui/tree/master/Index_Backups. If you haven't solved the problem yet, you can try to recover the index from the address I uploaded. But if this doesn't work, you have no choice but to reinstall the game. The same symptoms as yours were solved after I re-installed the game.
