### ISSUE TITLE
Is it possible to change the right part (it's color white) and also the text below to black? :D 

### ISSUE THREAD

**Issue by oneandonlywm3** [skotlex/ffxiv-material-ui#182]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. Please change the image of a specific UI [...]

**Additional context**

![117881486_1266083850399656_6087512972117742420_n](https://user-images.githubusercontent.com/70119108/90993750-ae707380-e5e8-11ea-8a85-a496bb9a3d89.jpg)

![photo_2020-08-24_09-09-04](https://user-images.githubusercontent.com/70119108/90993960-9d743200-e5e9-11ea-9c7a-96fbc3b89ccb.jpg)

**Comment by oneandonlywm3** [comment]
![118032216_634154124144861_8327626886625331250_n](https://user-images.githubusercontent.com/70119108/90993784-c7792480-e5e8-11ea-95ea-d6f53c8387d4.jpg)

**Comment by skotlex** [comment]
If change the color of the window to dark, we can't see the letters. I have no authority to change the color of the text.
