### ISSUE TITLE
Black X on Duty Finder frame.

### ISSUE THREAD

**Issue by ChaoticSi1ence** [skotlex/ffxiv-material-ui#183]
![image](https://user-images.githubusercontent.com/40935105/91647114-b5521880-ea24-11ea-8778-64ef487c0875.png)

**Comment by ChaoticSi1ence** [comment]
IT's hard to see but if you look closely at the class icon there is an X behind it.

**Comment by zhouhuichen741** [comment]
![QQ截图20200911203011](https://user-images.githubusercontent.com/50648819/93006248-81cace80-f58c-11ea-82bc-0e087cbbd7c4.png)

**Comment by skotlex** [comment]
[Material-UI_v3.3.1.zip](https://github.com/skotlex/ffxiv-material-ui/files/5213729/Material-UI_v3.3.1.zip)
The error has been corrected.
