### ISSUE TITLE
Consistent styles for class/job icons?

### ISSUE THREAD

**Issue by Sabiha-del** [skotlex/ffxiv-material-ui#185]
Currently, there are two separate categories of style options for class/job icons. One style option shows up in the Character window and the party list. The other style option shows up in gear set list and party finder.

However, the style options across these two categories are not consistent. There are four styles for the first category: "Rounded corner", "Squared corner", "Glowing", and "Glowing but ranged DPS have different color". And there are two styles for the last category: "Glow" and "Default".

Would it be possible to make it so that these two categories of class/job icons have consistent style options?

Additionally, if the same style options could apply to the "job macro icon" category that's newly added in v3.3.0 (from #152), it'd be awesome.

**Comment by skotlex** [comment]
It seems necessary to clean up the options for the icons once again. It'll take some time, but please wait.

**Comment by nihilisticpandemonium** [comment]
While I await an official update, I like using the "Glowing but ranged DPS have different color" so I created a custom modpack that includes the different ranged dps colors to use with the gear set list and party finder.  I can also confirm this modpack also changes the icons seen on the hotbar gear sets as well.
[contents-glow-job-icon-ranged-different-color.zip](https://github.com/skotlex/ffxiv-material-ui/files/5602874/contents-glow-job-icon-ranged-different-color.zip)

**Comment by skotlex** [comment]
I tested this and found the following problem.
![화면 캡처 2021-01-17 021737](https://user-images.githubusercontent.com/31692408/104818323-3d1cb000-586a-11eb-8657-c35b15a323af.png)
![화면 캡처 2021-01-17 023055](https://user-images.githubusercontent.com/31692408/104818616-00ea4f00-586c-11eb-84c0-a13543a5ddfd.png)
When icon's have background, this ugly image comes out. 
So I decided to offer only two options this time. ("Glowing", "Glowing but ranged DPS have different color") 
I ask for your understanding about this. Or if you have any other ideas, please tell me.
