### ISSUE TITLE
Glowing Gearset Icons from 3.3.0

### ISSUE THREAD

**Issue by A-Sparowe** [skotlex/ffxiv-material-ui#186]
> ![주석 2020-08-09 175335](https://user-images.githubusercontent.com/31692408/89728775-c08bd700-da6a-11ea-83f4-2512588fb834.png)
> It will be included in option "contents-glow-job-icon" of the next patch.

I just updated to 3.3.0 today and I'm in the process of applying the 3.3.1 hot-fix right now and I was wondering how these new icons are implemented? After Installing 3.3.0 and trying each of the files from folders 5 & 6 that were located in the "Options" folder I wasn't able to get them to show up. When viewing them in TexTools they just show up as the glowing icons with transparent background, instead of them being glowing and on the background shown in the preview picture. Now it could honestly just be the way I have my UI mods installed. What I'm trying to achieve on my setup is by combining elements from both the "Discord and Black". I love the Black UI but I also liked a lot of the accents you used for the Discord version as well as leaving some of the "gold/bronze?" accents in from the default UI. While I haven't gone and started the whole process of combining them just yet I am in the process of making most of my UI elements semi-transparent. My favorite thing about what you did with the UI is how you made the windows partially transparent when they weren't focused. It's the perfect amount in my opinion. Goes really well with the glowing icons. 

Instead of asking you to do it for me and considering I know how to do this sort of stuff on my own in Photoshop I figured I'd tinker with it on my own and then share the results with you on here to see what people think of it? I know I've seen some posts regarding adding more options to the mod, either by adding more options or color schemes to both the Discord and Black versions as they are or by adding another completely new version all together. Honestly I just wanted to have the option for myself to use lol.

I was wondering what the file names are that deal with adding background to the GUI? Namely the GUI windows that any average player like myself would be using all the time? From looking at the files it seems they all share these or some of these files with each other so if I make one window semitransparent then I'd be making another one transparent as well? 

![actioncross - Copy 02 - Copy](https://user-images.githubusercontent.com/11279897/93029344-009d2700-f5e0-11ea-90b2-9163e8f1ac91.png) ![actioncross - Copy](https://user-images.githubusercontent.com/11279897/93029358-114d9d00-f5e0-11ea-98e9-9d16782fcb08.png)

As you can see from the two files I added at the end I made the background for the "Cross Hotbar/XHB" transparent for when it pops up whenever you activate an action on the hotbar. At first I thought by doing this is what caused the the new gearset icons to not display like they do in the picture but the tan/white background pictured above only appears on the cross hotbars during a keypress.

**Comment by skotlex** [comment]
I think it's good to offer a lot of options and have a lot of choices for users. Personally, however, the number of options is limited because it becomes difficult to manage. For your information, please see option '05_Window -> 02_discord-non-selected-window-trans...' for window opacity. For Windows, this implementation is possible because the textures of selection and non-selection are separated, but for the rest of the textures, it is not separated.

I was not good at English, so I couldn't understand everything you said, so I ask for your understanding. If there's anything I missed out on, I'd appreciate it if you could tell me again.

**Comment by A-Sparowe** [comment]
Thanks for the reply. Sorry I write so much. My apologies. =)
