### ISSUE TITLE
Mixing themes

### ISSUE THREAD

**Issue by rsigim** [skotlex/ffxiv-material-ui#188]
Hello, Theres a easy way to use the dark theme with round corners?
I know its possible but cant figure out which assets I should select while importing

**Comment by Aireil** [comment]
If you want something like this: https://i.imgur.com/QLRj52T.png
You can apply the theme, then use what skotlex linked here: https://github.com/skotlex/ffxiv-material-ui/issues/92#issuecomment-529067605
Still using it since, works perfectly. Thank you again skotlex ♥.

**Comment by rsigim** [comment]
Oh yeah, thats really what I was looking for. Thank you Aireil <3
Also Skotlex for you hard work here.

**Comment by skotlex** [comment]
It depends on which item you want to change to round. It can be an icon border or a window border. If you are referring to the border of the icon, you can use what @Aireil suggested. But Windows needs a new job.

**Comment by rsigim** [comment]
Well, a dark theme with round corners looks really cool ngl, but yeah, I was looking into the files and saw that the window corners comes with part of the style, mixing that part will mess with discord and dark colors, Im not looking for more work to you Skotlex,  Aireil got what I was looking for. Thank you again!
