### ISSUE TITLE
TexTools "advanced" modpack

### ISSUE THREAD

**Issue by bbeenn1** [skotlex/ffxiv-material-ui#190]
Due to the number of Options added, it would make is substantially easier if an "advanced" modpack could be generated for TexTools for Material-UI.

I am unsure if there are programmatic methods to creating the pack, but I do know that it would make it easier during game patches to see what you are applying before importing each individual option.
I believe that once you have created it once, updating can use previous versions as a starting point as well.

The screenshots provided and folder structure I believe can be recreated in the advanced modpack builder with a bit of restructure.
Recommendation for this as well: create one for Discord and another for Black as a "top-level split.

**Comment by skotlex** [comment]
I didn't know textool had this function lol
But I don't know how to use it. Do you have a link to the manual?

**Comment by bbeenn1** [comment]
I was unable to find documentation on the advanced modpack, but can ask around in the Discord if it exists anywhere

**Comment by bbeenn1** [comment]
From: FFXIV TexTools & Modding Discord
https://discord.com/channels/279130736806592513/576175339328372747/771481275047215175 

Ͳհҽ చօղ Ͳօղ ↻ąէ -the multitasker Yesterday at 2:11 PM
so what you need to do is click on the advanced modpack and then in the Options list of the first window, you would want to make one for Discord theme and once you click Add it will take you to the settings page.
in the top you may want to enter in the name of the theme and add its files, then when it comes to the optional items like square minimap, minimap without NSWE and others like that, you can then add a preview of the option and then select from the list on where that item replaces the UI and click texture and either Add from existing install or Add New to add a file from its raw .dds images. 

it will take a while to make one with all the options for the themes but when you have completed it and it needs an update in the future, you can reupload the modpack in the advanced window and make the later edits in the future. the Load From... only works on modpack wizard packs

i was sure there was a updated guide in the helpful guides on this but its not there anymore or i am not looking further up the list

or pulled down to be updated later

**Comment by skotlex** [comment]
Thank you very much for checking.
I'll refer to it the next time I work!

**Comment by skotlex** [comment]
I've done some experiments for this and consequently decided not to apply it.
There are two main reasons, as below:

1. It is very inefficient to search and enter a large number of textures for the application of mod. I think it would have been nice if there was a "select active" function of basic modpack.
2. For the biggest reason, the preview image provided is too small. Small images such as mini maps are fine, but larger ones like the ones below become hard for users to see.
![화면 캡처 2021-01-11 001349](https://user-images.githubusercontent.com/31692408/104127007-fb3fc580-53a2-11eb-83e8-9cb7c6190b98.png)

Nevertheless, I am very grateful for your suggestion and would like to ask for your attention in the future.
Thank you :)
