### ISSUE TITLE
Enemy list Default agro icons

### ISSUE THREAD

**Issue by Mad-Guns22** [skotlex/ffxiv-material-ui#191]
Reposting as a new Suggestion In Reference to issue #177. 

I have made my own edits to both the Discord and Black Variants of the mod restoring the default Icons for agro indicators.
Perhaps they can be included as an Option in future packs?

[Enemylist MaterialUI Default icons.zip](https://github.com/skotlex/ffxiv-material-ui/files/5436673/Enemylist.MaterialUI.Default.icons.zip)
![image](https://user-images.githubusercontent.com/64067323/97131547-29dcd580-1790-11eb-9209-aad676416a8a.png)
![image](https://user-images.githubusercontent.com/64067323/97131590-3f51ff80-1790-11eb-9cd7-306cedf49954.png)

**Comment by skotlex** [comment]
I'll consider it. Thank you for your opinion.
