### ISSUE TITLE
5.4 Patch Optimization and Future Planning (delay)

### ISSUE THREAD

**Issue by skotlex** [skotlex/ffxiv-material-ui#194]
![icon_17](https://user-images.githubusercontent.com/31692408/101299703-7844c000-3876-11eb-978a-3c63f687eeee.png)
Hello, everyone. It's been a while, but thank you for still using my work. I'm sorry I couldn't handle the update and the request. I had many things to do since September, so it was hard to pay attention to here.

I will write down briefly about 5.4 patch optimization and future direction.

- Adjustment Schedule
> ~20.12.13 | Patch 5.4 Preliminary - Primary adjustment to avoid breaking the texture, not optimizing.
> <s>~21.01.03</s> ~21.01.17 | Patch 5.4 Optimization - Optimize 5.4 patches and apply github issue contents.
> <b>※ I'm sorry for the delay in the schedule. I'm late because I don't have enough time to work.</b>

- Future Plan
> My goal is to make one more theme before the 6.0 patch comes out. The concept hasn't been decided yet, and although it's a future matter, I'd like to try. I will post two or three concept shots and propose them to you and finally decide and produce one. Please give me a lot of support to make this a success.

- Discord(?)
> I doubt this will be necessary, but I'm thinking about it. Even if I do, it will take some time because I have no knowledge of channel management. As I said earlier, the first thing to worry about is whether this is really necessary. If I do this, I think I can do things like uploading patches, guides, and sharing various options. Or I can ask your opinion about the new texture that will be applied.

I hope you have a great end of the year, and let's cheer up for 5.4!

**Comment by AkiOwO** [comment]
Hii, love your work!
I think the idea with the Discord server is great and I would join :D

**Comment by adelpha** [comment]
I'd join the Discord. Looking forward to the Patch 5.4 Preliminary, the default UI just isn't good enough anymore :D

**Comment by ArutanSipdrae** [comment]
You can always recruit someone who knows how to manage a discord server rather than doing it yourself

**Comment by zip2030** [comment]
HI
 I would like to join Discord server.
Love your work.

**Comment by ArutanSipdrae** [comment]
Speaking of the mod's state, where have the options gone to? I haven't updated for a while so I wanted to but this will override my options and I can't find the files to download anywhere anymore

**Comment by skotlex** [comment]
It will come with options added in this patch. It will be uploaded in a few hours, so please wait a moment.
