### ISSUE TITLE
HD version?

### ISSUE THREAD

**Issue by ArutanSipdrae** [skotlex/ffxiv-material-ui#195]
**Additional context**
So I like adding HD mod to the game, and mostly all the HD icon mods, it allows me to increase their size without them being blurry. I also love the discord UI you're creating, but it's using the same low quality as the game's UI and when I increase a window's size (mostly my character window) it looks all blurry. Would it be possible for you to provide a HD version of your mod?

**Comment by skotlex** [comment]
I didn't realize it because I didn't know how to do it. So I need to study the mod structure of HD icon. However, this will take a long time and requires a lot of patience.

**Comment by ArutanSipdrae** [comment]
I'm not one to push people to go faster when they already take of their free time to create something for others
