### ISSUE TITLE
Missing "Adventurer in Need" Icons in Duty Roulette

### ISSUE THREAD

**Issue by poysama** [skotlex/ffxiv-material-ui#196]
With patch 5.4, the Duty Roulette now displays an icon on what adventurer role is needed.

Images below

![image](https://user-images.githubusercontent.com/596463/101984906-5c4e7d80-3cbf-11eb-9770-a2ec1915483d.png)

![image](https://user-images.githubusercontent.com/596463/101984912-6a9c9980-3cbf-11eb-85e6-2e157d62d131.png)

**Comment by skotlex** [comment]
The changes in 5.4 will be checked overall. And I'm going to sort out the issues about it separately.
