### ISSUE TITLE
Material UI Option

### ISSUE THREAD

**Issue by mrcoco0264** [skotlex/ffxiv-material-ui#198]
Hello,
What can i do to change the option that the Discord UI provide.
The option that i didn't find.
 - Job icon inside Classes/Jobs tab inside the Character windows.
 - The shield color option for the party list.
Thank you.

**Comment by skotlex** [comment]
Download OPTIONS.zip here
https://github.com/skotlex/ffxiv-material-ui/releases/tag/3.3.0

You can then enter the following path from the downloaded zip and apply it:
* Job icon: OPTIONS\03_Icon
* Shield color: OPTIONS\02_PartyList
