### ISSUE TITLE
Unable to get JobHud bars to work

### ISSUE THREAD

**Issue by Suiously** [skotlex/ffxiv-material-ui#199]
Heya! 

 First off, I love your UI and the effort you have to put into it!

Is there anything specific that needs to be done to get the simple JobHud bars to work? I have been using the UI for awhile and have never had the JobHud reskin work. Is there extra steps that need to be taken? I attempted to go through the Issues page but did not see anyone with a similar issue or question. 

Thanks!

**Comment by skotlex** [comment]
If you are asking about activation of simple bar, please refer to the following site:
https://na.finalfantasyxiv.com/blog/002175.html

**Comment by Suiously** [comment]
Oh my gosh I feel so stupid.

Thanks for taking the time to respond!
