### ISSUE TITLE
A minor change to "Hide Macro Gear Icon in Iconframe"

### ISSUE THREAD

**Issue by zhouhuichen741** [skotlex/ffxiv-material-ui#200]
"Hide macro gear icon in IconFrame",This is great,But I couldn't tell which was the macro icon and which was the normal icon, so I made some changes 
![QQ截图20210118211518](https://user-images.githubusercontent.com/50648819/104920179-5f314200-59d2-11eb-8546-8e48f99bdd07.jpg)

**Comment by zhouhuichen741** [comment]
[The gear on the macro icon has been changed to blue dot.zip](https://github.com/skotlex/ffxiv-material-ui/files/5826424/The.gear.on.the.macro.icon.has.been.changed.to.blue.dot.zip)

**Comment by zhouhuichen741** [comment]
only Discord

**Comment by skotlex** [comment]
I think this is an option that can depending on individual tastes. Thank you for your hard work, but it's hard to add to the official option. I'm sorry.
