### ISSUE TITLE
Transparent PartyFinder Job Icons Background

### ISSUE THREAD

**Issue by sunxyw** [skotlex/ffxiv-material-ui#201]
**Is your feature request related to a problem? Please describe.**
I want to know if it is possible to remove the background of the job icons in PartyFinder.
It will be great that you can add a new option to make partyfinder job icons transparent.

**Additional context**
From: ![image](https://user-images.githubusercontent.com/31698606/107131179-3a642680-690f-11eb-9c23-81d9a54651d8.png)
To: ![image](https://user-images.githubusercontent.com/31698606/107131209-6da6b580-690f-11eb-8bec-f3252ebfca79.png)

**Comment by skotlex** [comment]
![화면 캡처 2021-05-01 124947](https://user-images.githubusercontent.com/31692408/116770186-aa043080-aa7c-11eb-81d9-6c28e8ae19fd.png)
![화면 캡처 2021-05-01 125116](https://user-images.githubusercontent.com/31692408/116770180-a83a6d00-aa7c-11eb-97ef-cb17974db9bd.png)

I've tested it and I don't think it's a highly recommended option. So it won't be added to the option, but I'll give it to you if you want to use it personally.

[Transparent PartyFinder JobIcons Background.zip](https://github.com/skotlex/ffxiv-material-ui/files/6408838/Transparent.PartyFinder.JobIcons.Background.zip)

**Comment by sunxyw** [comment]
Ah yes, it doesn't seem to be as good as I thought. Anyway, thank you for your time.
