### ISSUE TITLE
"Adventurer in Need" is not indicated by a job icon in duty finder

### ISSUE THREAD

**Issue by Chymai** [skotlex/ffxiv-material-ui#204]
Hello, 

As of patch 5.4, icons were added in the daily roulette tab in Duty Finder that indicates the Adventurer in Need bonus. However, with your UI mod, those icons are not there. I was hoping you could help me with this. I perhaps have an old version of the mod since I downloaded the mod many months ago. 

This first image is what it should look like:
![image](https://user-images.githubusercontent.com/79292407/108445225-03a0e100-722a-11eb-85c5-966daf581dfd.png)

And this is what I see in the game: 
![image](https://user-images.githubusercontent.com/79292407/108445321-2fbc6200-722a-11eb-8bb5-5f057bbf036d.png)

I would really greatly appreciate the assistance if you can spare the time. I love your mod very much, and I want to continue using it. Having these icons included would be a big help for me.

**Comment by skotlex** [comment]
The patch for this content is included in version 5.4 (Complete). Please patch the new version at the address below.
https://github.com/skotlex/ffxiv-material-ui/releases/tag/3.4.0

**Comment by Chymai** [comment]
Thank you for answering! I originally downloaded various different files from the OPTIONS folder, rather than downloading the large encompassing file. Should I re-download the new files for the options I chose? Will TexTools just update those old files or will it be recognized as a different mod?

**Comment by Chymai** [comment]
I apologize, I was able to figure out how to properly download it. Thank you for your help! ^^/
