### ISSUE TITLE
Job icon enhance in skillbar

### ISSUE THREAD

**Issue by ArkhLink** [skotlex/ffxiv-material-ui#205]
Would it be possible to add an option to get job icon selector (in our skillbar) as same as character's menu style ?

**Comment by skotlex** [comment]
I'm sorry, but I don't understand what you're saying. If you don't mind, can you explain it with an image?

**Comment by ArkhLink** [comment]
Don't need to apologize ! :)

This kind of icon (skill bar) :
![image](https://user-images.githubusercontent.com/11856129/108506662-760cd200-72b9-11eb-9cca-66981e48295b.png)

With this style (custom skin from material-ui) :
![image](https://user-images.githubusercontent.com/11856129/108506776-a5bbda00-72b9-11eb-849d-3ee0ba07bc46.png)

Is it more understandable or do you need more information ?

**Comment by skotlex** [comment]
I understand. Thank you for the detailed image. I already received this request from another user. 
This is what the issue is about. #185 
In conclusion, I couldn't include that in the option of the discord because of the above reasons. 
I ask for your understanding on this.

**Comment by ArkhLink** [comment]
All good then.
Thank you for your time !
