### ISSUE TITLE
What is the icon with the human icon and arrow down (blue)?

### ISSUE THREAD

**Issue by Kumicoo** [skotlex/ffxiv-material-ui#206]

**Comment by skotlex** [comment]
Are you talking about the minimap icon? If that's right, it represents the direction you're looking at. I'm sorry if it's not that, but I'd appreciate it if you could explain it with an image. I'm sorry for my poor English.

**Comment by Kumicoo** [comment]
hey skotlex, first of all thanks for the reply. I mean the mannequin icon in the alliance list. if you still dont know i'll get into a raid and make a screenshot

**Comment by skotlex** [comment]
If what I understand is correct, it is an icon that shows the status of the debuff.

**Comment by Kumicoo** [comment]
What debuff? here i mean this one. 
![image](https://user-images.githubusercontent.com/35538818/109227106-14200100-77c0-11eb-83e0-5466796e0b81.png)

**Comment by skotlex** [comment]
It means more than a state of slowing down or stun.

**Comment by skotlex** [comment]
I'm not ignoring you, but if it's a dictionary definition of debuff, you can refer to the site below.
http://www.self.gutenberg.org/articles/debuff_(mmorpg_terminology)

**Comment by Kumicoo** [comment]
Nah i just thought you meant a specific debuff. Never said youre ignoring me. really appreciate the replies. Love your ui. Hope you come back soon :) <3
