### ISSUE TITLE
About Patch 5.5

### ISSUE THREAD

**Issue by skotlex** [skotlex/ffxiv-material-ui#208]
For 5.5 patch response, I will pay for the game for a while. It may take some time, but please understand.

> **Thanks to your usual sponsorship, I can continue this work even though I don't play games. Thank you to everyone.**

![1592196266](https://user-images.githubusercontent.com/31692408/114579303-b20c5400-9cb8-11eb-907d-86c4240c18f9.png)

**Comment by skotlex** [comment]
- Adjustment Schedule
> ~21.04.18 | Patch 5.5 Preliminary - Primary adjustment to avoid breaking the texture, not optimizing.
> ~21.05.02 | Patch 5.5 Optimization - Optimize 5.5 patches and apply github issue contents.

**Comment by rowanlauron1017** [comment]
Love your work!  Take your time :)

**Comment by ShadowtheUltimate** [comment]
Take your time! I do wonder if you'd be able to get it working with the HD GUI setting enabled. Hope you can! :D

**Comment by ArutanSipdrae** [comment]
Will you support the new 4k setting?

**Comment by aaceace** [comment]
I just want to take a few minute to tell you how much I appreciate this mod.. I've been using it for a long time and now i feel naked without it.. lol Thank you so much for all that you do!

**Comment by Azurealistic** [comment]
Thank you so much for making this, and coming back to support it! We all deeply appreciate it as well as all your efforts!

**Comment by Maxunit** [comment]
Thank you so much for the continued support for Material UI. It is my must-have UI Mod by now ^^

**Comment by tobeyStraitjacket** [comment]
I adore this mod - thank you so much for continuing to update it <3

**Comment by ShinsoTheOnion** [comment]
Does the latest preliminary version not include updated assets for the 4K UI? I've updated and reapplied but it still looks the same as before.

Sorry if I missed this somewhere, absolutely love your work just wanted to be sure I'm not missing something.

**Comment by micsnik** [comment]
Hey thanks for the updated version! However seems like the 4K UI option seems to not work with the preliminary version.

**Comment by skotlex** [comment]
I am answering a lot of questions about 4K UI. I want to do it if possible, but I don't know how to do it in the current situation. Textool doesn't seem to provide any functions related to this, but if anyone knows, please let me know.

**Comment by micsnik** [comment]
> I am answering a lot of questions about 4K UI. I want to do it if possible, but I don't know how to do it in the current situation. Textool doesn't seem to provide any functions related to this, but if anyone knows, please let me know.

I heard from someone that textools seem to not provide any access to 4K because it apparently crashes it? I have no idea, that's just the word i heard, guess we'll have to wait for it!

**Comment by CyberiumShadow** [comment]
Yeah at this time, TexTools don't have access to the 4K assets in the game, I believe they are working on a workaround atm for it.

So atm, you'll have to disable the 4K UI option to use material_ui etc

**Comment by SkylerMews** [comment]
@skotlex TexTools just got an update allowing users to change and view the 4k UI now. It's live and seems to work great.

**Comment by FromTheGrayve** [comment]
Thanks so much for keeping this updated. I was wondering if it would be possible to make a compass with the lock, zoom in, and zoom out icons? They take up space and I don't need them.  (I would like it best on the square, discord version, with NESW included) 

Thanks for your time!

**Comment by firedrake150** [comment]
Love the work, but for me, even after starting TexTools over fresh, it doesn't work on 4k, Dunno if I'm doing something wrong but it works on standard edition.

**Comment by tobeyStraitjacket** [comment]
@firedrake150 Material UI hasn't been built yet for 4k. TexTools just released an update to allow 4k texture support, but Material UI has not since been updated to make use of this new support.

**Comment by firedrake150** [comment]
> @firedrake150 Material UI hasn't been built yet for 4k. TexTools just released an update to allow 4k texture support, but Material UI has not since been updated to make use of this new support.

Thank you, I somehow missed this.  I blame sleepiness with no coffee.  :)
