### ISSUE TITLE
Mod not working in 5.5

### ISSUE THREAD

**Issue by Moregaze** [skotlex/ffxiv-material-ui#209]
I reset my FFXIV index after patching due to some issues (mods where disabled while patching).  I reinstalled all of my mods but this one seems to not load at all.  I got HD skill icons to load no problem but Material UI not a single one of the imported and enabled mod packs loads into the game. 

Let me know what info you need to help diagnose this.

**Comment by skotlex** [comment]
5.5 Optimization patch not yet created. If what you're talking about is a problem with the game's execution, there may be a problem with the index file. But if it's just some of the textures that aren't visible, please wait until the 5.5 optimization patch.

**Comment by Moregaze** [comment]
Will do.  Didn't know if it was related or not so I thought it was best to ask.

**Comment by Alukah** [comment]
Open textools and under help pick download index backups, and then press start over, it should let you install the mod and should work fine minus some missing icons. You'll have to reinstall all mods.

**Comment by CyberiumShadow** [comment]
SE also added HD/4K UI interface to the game as of 5.5 as well, You probably don't need HD Skill Icons etc anymore as well @Moregaze

**Comment by YuleXiv** [comment]
> 
> 
> Open textools and under help pick download index backups, and then press start over, it should let you install the mod and should work fine minus some missing icons. You'll have to reinstall all mods.

the game considers the default UI and the optional HD 4k UI as "separate", so because this mod doesn't yet replace the 4k version, then you won't see the mod with the 4k enabled.

**Comment by Moregaze** [comment]
> the game considers the default UI and the optional HD 4k UI as "separate", so because this mod doesn't yet replace the 4k version, then you won't see the mod with the 4k enabled.

This is exactly what was going wrong.  I had the 4k enabled to save some mod slots as the item icons looked just as good as the modded ones I had been using.  However, the ability icons looked worse than the mod I was using so I put that one back on.  Once I switched it back to normal the UI loaded in no problems that I have seen yet.
