### ISSUE TITLE
UI Not Working at 4k UI Resolution Settings

### ISSUE THREAD

**Issue by RadOcta** [skotlex/ffxiv-material-ui#212]
**Screenshots**
![image](https://user-images.githubusercontent.com/20705005/115176691-85e04100-a0c5-11eb-9869-360cb4b5f1d0.png)
![image](https://user-images.githubusercontent.com/20705005/115177085-55e56d80-a0c6-11eb-95ac-4718da34942f.png)

**Description:**
As shown in the screenshot above the mod itself is enabled. I have added stuff from the options resource and it is enabled as well. However, once I open the game and login to my character, no changes have been made to the UI.

**To Reproduce:**
On system configuration -> graphics the UI Resolution settings must be at Standard for it to work. If it is at 4k none of the changes work (I am assuming due to the use of different assets)

**Comment by Zyian** [comment]
This is duplicate issue, the 4k resolution and normal UI are separate files. Please track this issue for updates https://github.com/skotlex/ffxiv-material-ui/issues/208

**Comment by RadOcta** [comment]
My bad thank you
