### ISSUE TITLE
Wrong/Missing Icons

### ISSUE THREAD

**Issue by RadOcta** [skotlex/ffxiv-material-ui#213]
**Screenshots**
![image](https://user-images.githubusercontent.com/20705005/115179511-60eecc80-a0cb-11eb-8323-d960956c384a.png)

**Description**
I havent tested with the discord version. This is happening to me in the Black UI version. The clock is using the wrong icons.

**Comment by RadOcta** [comment]
**Screenshots**
![image](https://user-images.githubusercontent.com/20705005/115214630-9fe84680-a0fa-11eb-89a4-d5dd588e9b6e.png)

**Description:**
Flourishing Cascade is not using the correct Icon.

**Comment by skotlex** [comment]
![화면 캡처 2021-04-19 192018](https://user-images.githubusercontent.com/31692408/115221608-d34fc300-a144-11eb-8d0a-8e2c7b3d75b2.png)
![화면 캡처 2021-04-19 192330](https://user-images.githubusercontent.com/31692408/115221614-d5198680-a144-11eb-920d-9568e136a30a.png)
![화면 캡처 2021-04-19 192203](https://user-images.githubusercontent.com/31692408/115221634-d8ad0d80-a144-11eb-91da-005598afb02e.png)
There seems to be no problem when testing based on the current version. But in your case, the index file may be broken. Usually, mods must be removed before the game is patched, but this may occur if you fail to do so. 

After you back up your index, you may need to test it by overwriting the files here at https://github.com/skotlex/ffxiv-material-ui/tree/master/Index_Backups, or reinstall the game if you still can't.

**Comment by RadOcta** [comment]
oooh gotcha! My bad. I thought that it was a mod issue. I will test it our further on my end. Thank you.

**Comment by RadOcta** [comment]
After disabling all the mods and replacing the file with the ones from the backups everything was normal. I now enabled all of the UI options I had previously and no problem so far with uses of wrong icons. Thank you again for your patience! Appreciated.
