### ISSUE TITLE
Notice for 4K UI support

### ISSUE THREAD

**Issue by skotlex** [skotlex/ffxiv-material-ui#214]
As SQEX officially supports 4K UI, many inquiries about this are being received. As already briefly mentioned in #208, I would like to guide you on the current situation and future plans.

As a result, 4K support of Material UI is possible. (XIVLauncher's goat did a great job. Thank you very much!)

But at the same time, there is a big problem. There are too many textures to work on...  Need to upscaling, so I need to create all the textures from beginning. The combined texture of Discord, Black and Options is over 800. Unfortunately, I don't have much time to spare unlike before, so it will take quite a long time.

Personally, it aims to complete the 6.0 patch before it is released. It is really dangerous to exceed 6.0, so no matter what happens, I don't intend to pass this deadline. I think this schedule is very late, and I think you will be disappointed to read this article. Nevertheless, I say it is inevitable because I lack my ability and time.

I'm sorry to all of you who've been looking forward to supporting 4K.
When the 4K support UI is completed in the future, I will do our best to satisfy you.

Thank you for reading this.

## Added. 21/05/01
With support from @Tatsu941, it was provided with an upscaled texture that could be used temporarily, enabling 4K. But this is only temporary, and OPTIONS are not available (working with options takes a lot of time.)

**Comment by Zyian** [comment]
Since the HD textures are directly 2x resolution from what I've noticed, I tried out http://waifu2x.udp.jp/ which is a known image upscaler. Taking a random texture from the repository, I tried upscaling it on the 2x setting on highest. So far I got some good results.

### Original bank.dds
![bank](https://user-images.githubusercontent.com/5796109/115315372-2d508880-a145-11eb-8854-32c5b84805ac.png)


### 2x Upscaled
![bank_waifu2x_art_noise3_scale_tta_1](https://user-images.githubusercontent.com/5796109/115315450-5cff9080-a145-11eb-996c-051abdc8b11c.png)

And honestly doesn't look too bad, there are some minor imperfections, but overall not too bad. So the textures could be all batched together (definitely not by hand through the website but running it locally), which will still require a bit of work, but there is that option

**Comment by Felix941** [comment]
@Zyian I upscaled all the 800 textures with ESRGAN and the Faithful-Lite 2x Preset which is made for pixelart and sent it back to @skotlex
He will update us as soon as he looked thru them and decided how to move forward

**Comment by skotlex** [comment]
While performing the 4K task, changes may occur and such issues I will write them down here. (In this process, people who are interested in my work may be asked to vote.) As many as dozens of posts can be created, if you don't want to receive an alarm, press the "Unsubscribe" button on the right. Conversely, if you are interested in this issue, please "Subscribe."

**Comment by CyberiumShadow** [comment]
> 
> 
> Since the HD textures are directly 2x resolution from what I've noticed, I tried out http://waifu2x.udp.jp/ which is a known image upscaler. Taking a random texture from the repository, I tried upscaling it on the 2x setting on highest. So far I got some good results.
> ### Original bank.dds
> 
> ![bank](https://user-images.githubusercontent.com/5796109/115315372-2d508880-a145-11eb-8854-32c5b84805ac.png)
> ### 2x Upscaled
> 
> ![bank_waifu2x_art_noise3_scale_tta_1](https://user-images.githubusercontent.com/5796109/115315450-5cff9080-a145-11eb-996c-051abdc8b11c.png)
> 
> And honestly doesn't look too bad, there are some minor imperfections, but overall not too bad. So the textures could be all batched together (definitely not by hand through the website but running it locally), which will still require a bit of work, but there is that option

There is a paid service (which is prepaid per time used) found here: https://mng.waifu2x.me/

It's essentially waifu2x but you get your own instance/server to use it on and it also allows batch uploading / processing as well.

Cheapest instance type you can get with that service is about $0.05 USD per minute which has 8 vCPUs, 15GB memory and 8GB GPU memory.

Although, with 800+ textures as per @skotlex 's original message, it may take a fair bit of time + the costs would add up.

**Comment by skotlex** [comment]
> > Since the HD textures are directly 2x resolution from what I've noticed, I tried out http://waifu2x.udp.jp/ which is a known image upscaler. Taking a random texture from the repository, I tried upscaling it on the 2x setting on highest. So far I got some good results.
> > ### Original bank.dds
> > ![bank](https://user-images.githubusercontent.com/5796109/115315372-2d508880-a145-11eb-8854-32c5b84805ac.png)
> > ### 2x Upscaled
> > ![bank_waifu2x_art_noise3_scale_tta_1](https://user-images.githubusercontent.com/5796109/115315450-5cff9080-a145-11eb-996c-051abdc8b11c.png)
> > And honestly doesn't look too bad, there are some minor imperfections, but overall not too bad. So the textures could be all batched together (definitely not by hand through the website but running it locally), which will still require a bit of work, but there is that option
> 
> There is a paid service (which is prepaid per time used) found here: https://mng.waifu2x.me/
> 
> It's essentially waifu2x but you get your own instance/server to use it on and it also allows batch uploading / processing as well.
> 
> Cheapest instance type you can get with that service is about $0.05 USD per minute which has 8 vCPUs, 15GB memory and 8GB GPU memory.
> 
> Although, with 800+ textures as per @skotlex 's original message, it may take a fair bit of time + the costs would add up.

Since @Tatsu941 has already provided an upscale texture, I will test this first and then think about next. Since I already have money donated, paid services are not impossible. However, there are some aspects that are afraid to try, given that it is difficult to check the satisfaction of the quality and the exact amount.

**Comment by viion** [comment]
> > Since the HD textures are directly 2x resolution from what I've noticed, I tried out http://waifu2x.udp.jp/ which is a known image upscaler. Taking a random texture from the repository, I tried upscaling it on the 2x setting on highest. So far I got some good results.
> > ### Original bank.dds
> > ![bank](https://user-images.githubusercontent.com/5796109/115315372-2d508880-a145-11eb-8854-32c5b84805ac.png)
> > ### 2x Upscaled
> > ![bank_waifu2x_art_noise3_scale_tta_1](https://user-images.githubusercontent.com/5796109/115315450-5cff9080-a145-11eb-996c-051abdc8b11c.png)
> > And honestly doesn't look too bad, there are some minor imperfections, but overall not too bad. So the textures could be all batched together (definitely not by hand through the website but running it locally), which will still require a bit of work, but there is that option
> 
> There is a paid service (which is prepaid per time used) found here: https://mng.waifu2x.me/
> 
> It's essentially waifu2x but you get your own instance/server to use it on and it also allows batch uploading / processing as well.
> 
> Cheapest instance type you can get with that service is about $0.05 USD per minute which has 8 vCPUs, 15GB memory and 8GB GPU memory.
> 
> Although, with 800+ textures as per @skotlex 's original message, it may take a fair bit of time + the costs would add up.

You can use https://github.com/lltcggie/waifu2x-caffe/releases

It's a windows app that performs waifu2x in bulk, it also has more options, and is free.

**Comment by 86Atlas** [comment]
> 
> 
> > > Since the HD textures are directly 2x resolution from what I've noticed, I tried out http://waifu2x.udp.jp/ which is a known image upscaler. Taking a random texture from the repository, I tried upscaling it on the 2x setting on highest. So far I got some good results.
> > > ### Original bank.dds
> > > ![bank](https://user-images.githubusercontent.com/5796109/115315372-2d508880-a145-11eb-8854-32c5b84805ac.png)
> > > ### 2x Upscaled
> > > ![bank_waifu2x_art_noise3_scale_tta_1](https://user-images.githubusercontent.com/5796109/115315450-5cff9080-a145-11eb-996c-051abdc8b11c.png)
> > > And honestly doesn't look too bad, there are some minor imperfections, but overall not too bad. So the textures could be all batched together (definitely not by hand through the website but running it locally), which will still require a bit of work, but there is that option
> > 
> > 
> > There is a paid service (which is prepaid per time used) found here: https://mng.waifu2x.me/
> > It's essentially waifu2x but you get your own instance/server to use it on and it also allows batch uploading / processing as well.
> > Cheapest instance type you can get with that service is about $0.05 USD per minute which has 8 vCPUs, 15GB memory and 8GB GPU memory.
> > Although, with 800+ textures as per @skotlex 's original message, it may take a fair bit of time + the costs would add up.
> 
> You can use https://github.com/lltcggie/waifu2x-caffe/releases
> 
> It's a windows app that performs waifu2x in bulk, it also has more options, and is free.
> 
> I used it to 2x the icons a long time ago from GarlandTools and it came out decent.

I want to try this, do you have pointers what the best settings regarding less quality loss in the porcess of upscaling would be?

**Comment by Tatsu941** [comment]
> 
> 
> > > > Since the HD textures are directly 2x resolution from what I've noticed, I tried out http://waifu2x.udp.jp/ which is a known image upscaler. Taking a random texture from the repository, I tried upscaling it on the 2x setting on highest. So far I got some good results.
> > > > ### Original bank.dds
> > > > ![bank](https://user-images.githubusercontent.com/5796109/115315372-2d508880-a145-11eb-8854-32c5b84805ac.png)
> > > > ### 2x Upscaled
> > > > ![bank_waifu2x_art_noise3_scale_tta_1](https://user-images.githubusercontent.com/5796109/115315450-5cff9080-a145-11eb-996c-051abdc8b11c.png)
> > > > And honestly doesn't look too bad, there are some minor imperfections, but overall not too bad. So the textures could be all batched together (definitely not by hand through the website but running it locally), which will still require a bit of work, but there is that option
> > > 
> > > 
> > > There is a paid service (which is prepaid per time used) found here: https://mng.waifu2x.me/
> > > It's essentially waifu2x but you get your own instance/server to use it on and it also allows batch uploading / processing as well.
> > > Cheapest instance type you can get with that service is about $0.05 USD per minute which has 8 vCPUs, 15GB memory and 8GB GPU memory.
> > > Although, with 800+ textures as per @skotlex 's original message, it may take a fair bit of time + the costs would add up.
> > 
> > 
> > You can use https://github.com/lltcggie/waifu2x-caffe/releases
> > It's a windows app that performs waifu2x in bulk, it also has more options, and is free.
> > I used it to 2x the icons a long time ago from GarlandTools and it came out decent.
> 
> I want to try this, do you have pointers what the best settings regarding less quality loss in the porcess of upscaling would be?

@86Atlas You do know we already upscaled everything right?

**Comment by imphilxd** [comment]
Thank you for your work on Material UI. Started using it recently and it looks amazing. If possible, please consider adding an option to have transparent simple job huds. Instead of having a filled in gray color when not in use. I was using rien-doll/minimal-ui before this. I enjoyed having transparent job huds and health bars. Thank you.

**Comment by skotlex** [comment]
[Material-UI v3.5.0 Upscale 4K.zip](https://github.com/skotlex/ffxiv-material-ui/files/6371161/Material-UI.v3.5.0.Upscale.4K.zip)

I have created a 4K support file using the texture provided by @Tatsu941. I see some flaws, but I don't think it's bad for temporary use. However, even if this is distributed, I will not provide the part about the options. Please understand that the work of this is quite time consuming.

I'd like to hear your opinion on whether it's okay to distribute this. <i>It should be noted that no further modification is possible from this.</i> This is a temporary version, and I don't have enough time because I have to make a 4K supported version before 6.0.

If distributed, it will be included in next week's Complete version and @Tatsu941 will have to help one more time.

**Comment by darovic** [comment]
I'm using it right now @skotlex and it does appear to be perfectly functional. I haven't found any obvious issues. I'd say it's perfectly useable until you finish your extensive rework for 6.0.

**Comment by viion** [comment]
I am also using the new Upscale 4K you posted and agree with @darovic it looks perfect, I cannot see a single thing wrong, but in some specific areas? But in-game it looks perfect.

**Comment by Tatsu941** [comment]
Thank you soo much for doing that I am sure alot of people will really be thankful to have this temporary solution!

**Comment by 86Atlas** [comment]
> 
> 
> [Material-UI v3.5.0 Upscale 4K.zip](https://github.com/skotlex/ffxiv-material-ui/files/6371161/Material-UI.v3.5.0.Upscale.4K.zip)
> 
> I have created a 4K support file using the texture provided by @Tatsu941. I see some flaws, but I don't think it's bad for temporary use. However, even if this is distributed, I will not provide the part about the options. Please understand that the work of this is quite time consuming.
> 
> I'd like to hear your opinion on whether it's okay to distribute this. It should be noted that no further modification is possible from this. This is a temporary version, and I don't have enough time because I have to make a 4K supported version before 6.0.
> 
> If distributed, it will be included in next week's Complete version and @Tatsu941 will have to help one more time.

Works perfect, i changed a few things for my own liking but otherwise i cant find a single fault ingame

**Comment by ArutanSipdrae** [comment]
> @Zyian I upscaled all the 800 textures with ESRGAN and the Faithful-Lite 2x Preset which is made for pixelart and sent it back to @skotlex
> He will update us as soon as he looked thru them and decided how to move forward

think you can upscale the options too? that would be lovely

**Comment by skotlex** [comment]
> > @Zyian I upscaled all the 800 textures with ESRGAN and the Faithful-Lite 2x Preset which is made for pixelart and sent it back to @skotlex
> > He will update us as soon as he looked thru them and decided how to move forward
> 
> think you can upscale the options too? that would be lovely

@Tatsu941 has already provided me with an upscale of all possible textures. But as I said before, please understand that I couldn't offer 4K option because of my schedule.

**Comment by kesada1313** [comment]
> [Material-UI v3.5.0 Upscale 4K.zip](https://github.com/skotlex/ffxiv-material-ui/files/6371161/Material-UI.v3.5.0.Upscale.4K.zip)
> 
> I have created a 4K support file using the texture provided by @Tatsu941. I see some flaws, but I don't think it's bad for temporary use. However, even if this is distributed, I will not provide the part about the options. Please understand that the work of this is quite time consuming.
> 
> I'd like to hear your opinion on whether it's okay to distribute this. It should be noted that no further modification is possible from this. This is a temporary version, and I don't have enough time because I have to make a 4K supported version before 6.0.
> 
> If distributed, it will be included in next week's Complete version and @Tatsu941 will have to help one more time.

![image](https://user-images.githubusercontent.com/83317420/116323319-9b630400-a772-11eb-9d4c-0282c489a8e9.png)
@skotlex I have this strange cross patterns in the 4k discord ui you uploaded there

**Comment by skotlex** [comment]
> > [Material-UI v3.5.0 Upscale 4K.zip](https://github.com/skotlex/ffxiv-material-ui/files/6371161/Material-UI.v3.5.0.Upscale.4K.zip)
> > I have created a 4K support file using the texture provided by @Tatsu941. I see some flaws, but I don't think it's bad for temporary use. However, even if this is distributed, I will not provide the part about the options. Please understand that the work of this is quite time consuming.
> > I'd like to hear your opinion on whether it's okay to distribute this. It should be noted that no further modification is possible from this. This is a temporary version, and I don't have enough time because I have to make a 4K supported version before 6.0.
> > If distributed, it will be included in next week's Complete version and @Tatsu941 will have to help one more time.
> 
> ![image](https://user-images.githubusercontent.com/83317420/116323319-9b630400-a772-11eb-9d4c-0282c489a8e9.png)
> @skotlex I have this strange cross patterns in the 4k discord ui you uploaded there

I will correct this problem. Thanks for letting me know.

**Comment by katawajojo** [comment]
> [Material-UI v3.5.0 Upscale 4K.zip](https://github.com/skotlex/ffxiv-material-ui/files/6371161/Material-UI.v3.5.0.Upscale.4K.zip)
> 
> I have created a 4K support file using the texture provided by @Tatsu941. I see some flaws, but I don't think it's bad for temporary use. However, even if this is distributed, I will not provide the part about the options. Please understand that the work of this is quite time consuming.
> 
> I'd like to hear your opinion on whether it's okay to distribute this. It should be noted that no further modification is possible from this. This is a temporary version, and I don't have enough time because I have to make a 4K supported version before 6.0.
> 
> If distributed, it will be included in next week's Complete version and @Tatsu941 will have to help one more time.

The dialogue boxes have some issues in this release.

Normal:

<img alt="ffxiv_dx11_2021-05-01_10-47-23" src="https://user-images.githubusercontent.com/13071927/116790758-dca52d80-aa6a-11eb-80ec-7144323f8a91.png">


Dragon: 

<img alt="ffxiv_dx11_2021-05-01_10-47-46" src="https://user-images.githubusercontent.com/13071927/116790769-e890ef80-aa6a-11eb-8279-939192c4428c.png">


Allagan:

<img alt="ffxiv_dx11_2021-05-01_10-48-11" src="https://user-images.githubusercontent.com/13071927/116790779-fc3c5600-aa6a-11eb-9eee-d2c4650400cc.png">


System:

<img alt="ffxiv_dx11_2021-05-01_10-46-54" src="https://user-images.githubusercontent.com/13071927/116790796-1aa25180-aa6b-11eb-804b-24c7bbf59c16.png">


All the background colors for the borders differ from the actual background colors for the text.
While I understand these were all up-rez'd with Waifu2x, the "Dragon" and "Allagan" speech borders got eaten alive with regards to quality.

**Comment by Tatsu941** [comment]
They were not uprezzed with Waifu2x that would look alot worse. I upscaled them with ERSGAN and the FaithLite preset after testing about 30 different ones. You have this one as a temporary one until @skotlex is done with the full rework. If he is gonna fix every file again the real one will take alot longer so please just live with it for now or don't use it.

**Comment by katawajojo** [comment]
> They were not uprezzed with Waifu2x that would look alot worse. I upscaled them with ERSGAN and the FaithLite preset after testing about 30 different ones. You have this one as a temporary one until @skotlex is done with the full rework. If he is gonna fix every file again the real one will take alot longer so please just life with it for now or don't use it.

I was mainly bringing to view that the colors were off in the text boxes. I'm sorry I got the uprez method wrong. However, you don't have to be rude about a mention about something being off with something that's commonly seen.

**Comment by skotlex** [comment]
> > They were not uprezzed with Waifu2x that would look alot worse. I upscaled them with ERSGAN and the FaithLite preset after testing about 30 different ones. You have this one as a temporary one until @skotlex is done with the full rework. If he is gonna fix every file again the real one will take alot longer so please just life with it for now or don't use it.
> 
> I was mainly bringing to view that the colors were off in the text boxes. I'm sorry I got the uprez method wrong. However, you don't have to be rude about a mention about something being off with something that's commonly seen.

Let's take a look at that before I distribute it today. If it can be modified simply, I will try to apply it. However, it may be difficult to modify due to time issues. As I said before, I do not have enough time to process all inquiries about temporary files, so I ask for your understanding.

**Comment by Tatsu941** [comment]
> 
> 
> > > They were not uprezzed with Waifu2x that would look alot worse. I upscaled them with ERSGAN and the FaithLite preset after testing about 30 different ones. You have this one as a temporary one until @skotlex is done with the full rework. If he is gonna fix every file again the real one will take alot longer so please just life with it for now or don't use it.
> > 
> > 
> > I was mainly bringing to view that the colors were off in the text boxes. I'm sorry I got the uprez method wrong. However, you don't have to be rude about a mention about something being off with something that's commonly seen.
> 
> Let's take a look at that before I distribute it today. If it can be modified simply, I will try to modify it. However, it may be difficult to modify due to time issues. As I said before, I do not have enough time to process all inquiries about temporary files, so I ask for your understanding.

If you want, send me the files which got uprezzed wrong and I am gonna try to upscale those again with different methods that may work better

**Comment by skotlex** [comment]
> > > > They were not uprezzed with Waifu2x that would look alot worse. I upscaled them with ERSGAN and the FaithLite preset after testing about 30 different ones. You have this one as a temporary one until @skotlex is done with the full rework. If he is gonna fix every file again the real one will take alot longer so please just life with it for now or don't use it.
> > > 
> > > 
> > > I was mainly bringing to view that the colors were off in the text boxes. I'm sorry I got the uprez method wrong. However, you don't have to be rude about a mention about something being off with something that's commonly seen.
> > 
> > 
> > Let's take a look at that before I distribute it today. If it can be modified simply, I will try to modify it. However, it may be difficult to modify due to time issues. As I said before, I do not have enough time to process all inquiries about temporary files, so I ask for your understanding.
> 
> If you want, send me the files which got uprezzed wrong and I am gonna try to upscale those again with different methods that may work better for these special ones

In fact, I think that that problem is the same reason as that of https://github.com/skotlex/ffxiv-material-ui/issues/214#issuecomment-829685038. I appreciate your suggestion, but I think it will probably be possible with some modifications. If I'm having a hard time, I'll ask you later.
