### ISSUE TITLE
Deep Dungeon UI

### ISSUE THREAD

**Issue by birds-are-corrupted** [skotlex/ffxiv-material-ui#215]
I wanted to ask if we can get a better looking ui for the Deep Dungeon UI whos Blue and doesent get affected by material mod

Something like the minimal UI did before.
I can send some screenshots, blue one is original second  picture is the modded one.

just wanted to ask if its to much work or you dont want its also alright.

![Bild_2021-04-20_113520](https://user-images.githubusercontent.com/69503678/115373781-7bf53580-a1cc-11eb-8afe-a870a6cef2e3.png)
![39210_20210306153726_1](https://user-images.githubusercontent.com/69503678/115373826-86afca80-a1cc-11eb-8011-b06ba59abcc8.png)

**Comment by skotlex** [comment]
Deep-Dungeon didn't touch the basic UI because I thought it wasn't bad, but I'll try it later. However, please understand this part as this will be carried out with 6.0 response work.

**Comment by skotlex** [comment]
I tested this while working on 4K, but as a result, I concluded that the existing UI (blue) is suitable. Sorry for the late response and not a satisfactory result for you.
