### ISSUE TITLE
Can't seem to get it to work

### ISSUE THREAD

**Issue by Dima6767** [skotlex/ffxiv-material-ui#216]
Ever since 5.5 I can't seem to get the UI mod to work. I've download the latest update for 5.5.
I've tried reinstalling the mod, reinstalling textools, using the start over option in textools. 
Am I missing something or doing something wrong?

**Comment by skotlex** [comment]
Please check if you have checked the use of 4K UI or if you have a theme other than dark.

**Comment by Dima6767** [comment]
Oh, I did not realize having 4k breaks it. It works now. Thank you very much
