### ISSUE TITLE
Glowing icon macros

### ISSUE THREAD

**Issue by PolarBroOmega** [skotlex/ffxiv-material-ui#219]
So I was just wondering, as with a previous version, the saved gearset icons for jobs had the same glowing icons, I was wondering if I missed how to enable that, if it's temporarily not done, or if that's been depricated? :] Thank you for all your work, the second I got the notification for this I downloaded it :D

**Comment by skotlex** [comment]
Available through the `~OPTIONS/03_Icon/05_content-glow-job-icon`

![contents-glow-job-icon](https://user-images.githubusercontent.com/31692408/116808399-7e17a680-ab73-11eb-8148-547b8d5f4f92.png)
 option.

**Comment by PolarBroOmega** [comment]
> Available through the `~OPTIONS/03_Icon/05_contents-glow-job-icon` option.
> 
> ![contents-glow-job-icon](https://user-images.githubusercontent.com/31692408/116808399-7e17a680-ab73-11eb-8148-547b8d5f4f92.png)

Ah perfect, thank you! I assumed I just wasn't seeing it, my brain couldn't distinguish the different options, so thank you! Thank you again for your hard and consistent work on this, it's by far in a way my go to UI mod :D
