### ISSUE TITLE
Square Minimap doesn't work.

### ISSUE THREAD

**Issue by shinxiv** [skotlex/ffxiv-material-ui#220]
Heya! I used the Material Mod before and I like it a lot, especially with the square minimap. I recently tried out the Material UI 3.5 but for some reason whenever I try to change the minimap to a square one (I tried both black, discord, with or without the NESW markers), the minimap stays as a circle minimap instead of a square.

Is there something I am missing or is it a problem that just hasn't been addressed yet?

**Comment by skotlex** [comment]
If you are using 4K UI, the option is not applicable. This is stated in the notice.

![화면 캡처 2021-05-04 171514](https://user-images.githubusercontent.com/31692408/116976579-5273f800-acfc-11eb-91da-b924ddd355f5.png)

**Comment by Crescr** [comment]
https://drive.google.com/file/d/17mm3syCxTUafHRC5cXzTC8qLNhbEX29x/view?usp=sharing
Some there is a strange point.
It doesn't affect me so I'm not going to fix it.
Please at your own risk.
