### ISSUE TITLE
macro icon remover is not working

### ISSUE THREAD

**Issue by hmyers91** [skotlex/ffxiv-material-ui#222]
hello thank you for the UI, it seems that the files uploaded are the same ones as the regular discord/black icon reskins and retain the macro icon on the action bar. the preview image included in the download shows it without, but the file names are the same and ive redownloaded/installed quite a few times and its not working. thank you!

**Comment by skotlex** [comment]
I checked, but there is nothing wrong with the file. Please check if you are using 4K UI resolution. Option files do not support 4K UI resolution.

**Comment by Minescence** [comment]
Will it be possible to have the macro wheel removed with the 4k UI resolution someday?

**Comment by AmenneHolelane** [comment]
4k options will be supported when the developer has both the time and energy to work on it. to quote them on the original 4k issue, "[working with options takes a lot of time." so it might be a while. initial 4k support was planned for 6.0 so it might be until then for options support. if not longer
