### ISSUE TITLE
Gearset icons on hotbar no longer glow as they did previously?

### ISSUE THREAD

**Issue by PolarBroOmega** [skotlex/ffxiv-material-ui#223]
![asdgfa](https://user-images.githubusercontent.com/63207274/118643306-fdc38900-b7a1-11eb-8759-08aa8bf85137.png)
Previously the gearset icons for jobs when dragged to a hotbar would glow, is this no longer the case? I have the glowing content with different job colors as well as the one for party list, but no matter which combo, the gearset icons no longer glow like the prior patch?

**Comment by AmenneHolelane** [comment]
If you are using the 4k icons, OPTION files aren't supported.

**Comment by PolarBroOmega** [comment]
> If you are using the 4k icons, OPTION files aren't supported.

ah I see, bummer :(
