### ISSUE TITLE
Fix color and adjust "+/-" buttons on black-square-minimap

### ISSUE THREAD

**Issue by vmwinckler** [skotlex/ffxiv-material-ui#225]
OPTIONS.zip > 01_Minimap > 07_black-square-minimap

- Fix border color for same black from UI;
- Remove border(or fix size/color) from buttons "+", "-" and padlock
-  Increase the spacing between the "+" and "-" buttons so that the letter "E" is visible

**Comment by skotlex** [comment]
The design of the mini-map will be changed, so the issue will be closed.
