### ISSUE TITLE
Install Sqaure Mini Map but still not working

### ISSUE THREAD

**Issue by SchwartzLizer** [skotlex/ffxiv-material-ui#228]
**Screenshots**
![image](https://user-images.githubusercontent.com/54163797/124057453-b4798100-da51-11eb-8eb8-ed2572e352ee.png)
![image](https://user-images.githubusercontent.com/54163797/124057531-d4a94000-da51-11eb-8f58-e2d47d9997d7.png)

**Describe the image**
on follow photo everything in option is working bur sqaure map isn't working

**Comment by AmenneHolelane** [comment]
if the section in this [image](https://i.imgur.com/hnzxHrl.png) is not set to standard HD/full HD, please change it to that. logout and log back in, and see if the issue is resolved
