### ISSUE TITLE
Hey there, I hate to be that guy, but this is my first time using a UI mod. But options just don't work for me.

### ISSUE THREAD

**Issue by ThatArmi** [skotlex/ffxiv-material-ui#231]
So, at first I install the complete UI itself, and that works for me in game, but then when I open the Options.zip and I choose each option I'd like to have, none of them actually apply to the UI itself. Am I dumb, or am I doing something wrong? Or maybe both. Thanks in advance!

**Comment by AmenneHolelane** [comment]
if the section in this [image](https://i.imgur.com/hnzxHrl.png) is not set to standard HD/full HD, please change it to that. 
close the game and relaunch, and see if the issue is resolved

**Comment by ThatArmi** [comment]
Alrighty, lemme try this out!

**Comment by ThatArmi** [comment]
That worked, thank you so much! Closing the thing now right?

**Comment by AmenneHolelane** [comment]
if you want to use the options and use the 4k settings, the BLACK theme should be coming out either shortly before or after the 6.0 release with full options support
