### ISSUE TITLE
Anyone have original map pack?

### ISSUE THREAD

**Issue by viion** [skotlex/ffxiv-material-ui#233]
Hello! 

Like an idiot, I didn't read or do this:
> Back up the following files in advance before you work (This is a preparation for mode failure)

I was messing with some OPTIONS and I installed `treasure-map-coordinate.ttmp2` however, I think I prefer the original maps

Does anyone have the original maps file they can upload? Or what is the best way to restore (just reinstall the game?)

Regards

**Comment by skotlex** [comment]
Click `Mods -> Mod List -> Manage Mod List` menu in TexTools, and disable `treasure-map-coordinate.ttmp2` mods

**Comment by viion** [comment]
Thank you so much @skotlex !!!
