### ISSUE TITLE
[Suggestion] An option to hide the size buttons and lock button on minimap

### ISSUE THREAD

**Issue by wheatbread** [skotlex/ffxiv-material-ui#234]
It would look extremely clean and minimalist if we hide those. <3  (with the same design that also hides the NSEW letters)

**Comment by Mad-Guns22** [comment]
If you make use of the FFXIVQuickLauncher, you'll be able to hide those UI elements using the tweeks mod as a part of that as well.
![image](https://user-images.githubusercontent.com/64067323/129498645-c4ff1540-e60e-4c4c-9284-bb35ff91f4d1.png)
