### ISSUE TITLE
Icon backgrouds

### ISSUE THREAD

**Issue by enderneko** [skotlex/ffxiv-material-ui#235]
Imported Material-UI(DISCORD) v3.5.0 (Complete).ttmp2 then partylist-glow-job-icon-diff-range-dps-color.ttmp2.
![icons](https://user-images.githubusercontent.com/16433215/129444859-e45f5997-4947-4989-a1e2-ddfb5386e3fb.png)
These icon backgrounds are still there.
Everything goes well when I change to BLACK.
This issue only occurs on DISCORD theme.

**Comment by skotlex** [comment]
https://github.com/skotlex/ffxiv-material-ui/issues/221
duplicated

**Comment by enderneko** [comment]
Thank you!
Thanks for your great work!
