### ISSUE TITLE
Realm icon/package icon being weird

### ISSUE THREAD

**Issue by Rekal87** [skotlex/ffxiv-material-ui#237]
Hello, I just recently yesterday installed the Material UI and everything works perfectly except the icons that are for the server(realm) and the wifi icon is doing some weird things.
I've tried looking through the files to see whats being put there, so i can try and disable it, but I cant find anything that's supposed to be there.
![ffxiv_dx11_jqLry789Bq](https://user-images.githubusercontent.com/89319370/130333646-b8568d63-ed26-40b8-bbef-d76ff988b11f.png)

**Comment by skotlex** [comment]
If the existing texture is broken, the index file may be corrupted with high probability. In this case, you may need to restore the index from the link below and try again, or in the worst case, reinstall the game.

For now, you can try the following process:

Open TexTools
Help > Download Index Backups
Help > Start Over
Mods > Import ModPacks > Import Material UI

**Comment by AmenneHolelane** [comment]
If the above steps don't work, you'll need to reinstall the game. While updating the game with mods active is not recommended, it usually was fine. Recent updates have started to cause this so make sure you disable all mods before updating the game

**Comment by Rekal87** [comment]
Thanks! Doing the Start Over process worked!
