### ISSUE TITLE
Optional not working

### ISSUE THREAD

**Issue by dacryphiliac** [skotlex/ffxiv-material-ui#238]
Optional UI installs not working. i.e I download the Square minimap and it won't replace, same goes with all the other options.

**Comment by AkiroKatashi** [comment]
Hey dacryphiliac,

Did you find a fix for this as it's doing the same thing for me on Upscaled 4K UI.

Would appreciate a response.

Thank you,
Akiro :)

**Comment by AmenneHolelane** [comment]
@AkiroKatashi Please look at the first paragraph of the readme.
