### ISSUE TITLE
Penumbra support

### ISSUE THREAD

**Issue by GunB** [skotlex/ffxiv-material-ui#240]
I've been trying to install this on my penumbra plugin since I don't really want to modify my game's files as textools has damaged them a bunch of times already.

I tried over-writing different features of the Material UI but some of them just refuse to change. In this case, is the map. I tried installing one over the other with different priorities. I tried creating a customer meta.json so I could choose in between the different minimap options. I even copy-pasted and replaced the files of the default theme and none of them seem to change the default style of the theme.

Doesn't matter what option I use it looks like this:
### Default
![ffxiv_dx11_d5nC1yEJn8](https://user-images.githubusercontent.com/3722960/131906804-f5067d59-257c-44be-b3dc-24628e3a007c.png)
### discord-square-minimap-remove-NESW
![ffxiv_dx11_rBf8u29OYn](https://user-images.githubusercontent.com/3722960/131906824-9c7ddfbb-1d57-4563-9bc6-2bd615bcd53b.png)

As if I don't include the files in red, the style comes back to the FFXIV built-in theme.
### No theme
![ffxiv_dx11_9gi8yEJVqY](https://user-images.githubusercontent.com/3722960/131906854-ad8e437f-b2ff-47f7-8c39-083231ac4045.png)

I'm wondering what's the reason for this to happen but I honestly don't know. I'd like to ask you if there is a possibility to give this theme the support on penumbra.

Thank you so much for your hard work. This is an amazing theme and design.

**Comment by skotlex** [comment]
I think you should contact the community of xlvlauncher, not me. I can't figure out the cause because I don't know how Penumbra works.

**Comment by GunB** [comment]
So... someone at the goat-place discord pointed me to a solution. The issue is... I'm using the 4K UI. If that's the case then the minimap doesn't change and some options just don't vary.
Thank you for your quick response!
