### ISSUE TITLE
Some issue with the glow job icon in discord version

### ISSUE THREAD

**Issue by rosario1510** [skotlex/ffxiv-material-ui#242]
Hello, I have just installed the material ui and I realize the glow job icon doesn't fully match with the discord verion
but I don't know if I got anything wrong because I only found 1 option in the glow job icon file
![ui](https://user-images.githubusercontent.com/90167285/132156253-2c29f420-8463-4894-a35c-f88e44fd6f11.jpg)

**Comment by skotlex** [comment]
#221 duplicated

**Comment by AmenneHolelane** [comment]
closed as duplicate of #221
