### ISSUE TITLE
Map coordinates above minimap

### ISSUE THREAD

**Issue by Dekartea** [skotlex/ffxiv-material-ui#243]
Hey there, I've been using Material UI for a few days now and I love it. I was wondering if it would be possible to upload variants of the minimaps so that the coordinates are located above the minimap itself? I'm specifically using the black square no-NESW variant but I'm sure this is something a lot of users would appreciate. Maybe not, but I can't imagine it'd be extremely hard to do and it would make my UI that little bit cleaner/neater!

Cheers

**Comment by AmenneHolelane** [comment]
you might be better served asking in the quicklauncher/xivlauncher community. moving one specific part of a UI element is not as easily said than done with a mod. it's most likely easier done with a plugin

**Comment by skotlex** [comment]
I can't make such adjustments. Please contact the xivlauncher community.
