### ISSUE TITLE
XP Bar doesn't have rested XP indication

### ISSUE THREAD

**Issue by JamieBunpup** [skotlex/ffxiv-material-ui#244]
![image](https://user-images.githubusercontent.com/71115700/132925708-2a679a37-5267-4a7d-8fde-41eee8bb400d.png)

![image](https://user-images.githubusercontent.com/71115700/132925721-666fa650-512a-449b-9d67-525b435b2fff.png)

Comparison between the base UI and Material UI, I was confused and wondering if I don't accumulate rested XP once I have a class at 80 but that didn't make sense. There's no way to tell if you've run out of rested XP using the UI.

**Comment by sunxyw** [comment]
Material UI's rested XP is gray, maybe this confuses you.
The rest of the entire XP bar is rested XP, which is gray.  The normal XP is black.
The XP bar in the first picture you showed is blue, which means that your rested XP will carry over to the next level. Therefore, you cannot see the normal black XP here.

**Comment by skotlex** [comment]
Since gray can be confusing, I will add colors for additional experiences in the next version.

**Comment by JamieBunpup** [comment]
Fantastic! Thanks for explaining Sunxyw and I'm glad my input has been helpful Skotlex. Keep up the great work!
