### ISSUE TITLE
Job icons only change for Character window, despite "content-glowing-job-icons" being installed & enabled

### ISSUE THREAD

**Issue by haziqtheunique** [skotlex/ffxiv-material-ui#245]
![Screenshot 2021-09-11 031855](https://user-images.githubusercontent.com/89909147/132944644-723b4994-7c64-49e2-b485-4aa64e990c3e.png)
![ffxiv_09112021_031357_683](https://user-images.githubusercontent.com/89909147/132944661-4fb87d95-bd37-48a2-838b-cee1ca2957a1.png)
![ffxiv_09112021_031439_251](https://user-images.githubusercontent.com/89909147/132944664-be0e36ce-43a3-49fe-aa6b-c58d5b215509.png)
![ffxiv_09112021_031502_538](https://user-images.githubusercontent.com/89909147/132944666-b9760386-cf34-4780-b2d3-4b669c7f7a6c.png)

The "content-glowing-jobs-icon" is imported & enabled (clicked Enable All Mods), but the mods in Party Finder & on macro icons are still in the old style.

I tried running TexTools as admin, in case that would help the mods get installed correctly, but the same thing happened.

**Comment by skotlex** [comment]
The option must be in HD in order to apply. Prior to 6.0, the option will also support 4K support, but it is not currently supported.
![unknown](https://user-images.githubusercontent.com/31692408/132945969-9e8e0bce-90cf-4f08-9d5f-283a699276cc.png)

**Comment by Evolutious** [comment]
I am adding comment that I am having the same issue. I have installed the mods but when in game and looking at the gear sets, it is still using the default icons

![24a1f481aa4e687ff597485e343f358d](https://user-images.githubusercontent.com/49498530/132970533-54c5aae7-07d6-415a-95ea-9008a416d3b2.png)

![ddd68c952946109faffc46d5891345d0](https://user-images.githubusercontent.com/49498530/132970520-a6ac8ec7-9ebf-4987-b05c-1d3c1e4e2eed.png)

Hoping it may help get it corrected.

**Comment by haziqtheunique** [comment]
Looks like changing the UI resolution fixed it. It's weird that XIV has two different setting for UI: one for scaling & the other for pixel count.

Thanks for your help, though.
