### ISSUE TITLE
Custom mouse cursors to match Material UI

### ISSUE THREAD

**Issue by misshandel** [skotlex/ffxiv-material-ui#261]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. Please change the image of a specific UI [...]
I do not know if you are able to modify the in game cursors but it would be cool to see matching / custom cursors to go along with the Material UI.
**Additional context**

**Comment by skotlex** [comment]
Unfortunately, it's beyond my authority.
