### ISSUE TITLE
Add additional optional LFG icons for those wanting less glow.

### ISSUE THREAD

**Issue by rudenix** [skotlex/ffxiv-material-ui#263]
I've created an icon set that matches the existing PartyList Edge style from OPTIONS and would like to share.

![LFG_Clean_preview](https://user-images.githubusercontent.com/1915182/141405231-a278a5b7-d2ff-480e-9451-eac255765a87.png)
[LFG_Clean.zip](https://github.com/skotlex/ffxiv-material-ui/files/7524706/LFG_Clean.zip)

**Comment by skotlex** [comment]
If you don't mind, please upload it from our Discord channel to the user mods channel. More people can use your work
![화면 캡처 2021-11-11 185536](https://user-images.githubusercontent.com/31692408/141277757-ad4e36a5-c1a8-4263-bd80-521e4c5c4bd5.png)
.

**Comment by rudenix** [comment]
Uploaded this to discord as well.
