### ISSUE TITLE
Housing Furnishing Icons

### ISSUE THREAD

**Issue by Sevii77** [skotlex/ffxiv-material-ui#264]
The icons for furniture category seems to be missing.
![image](https://user-images.githubusercontent.com/20374966/141679704-390c39c8-b778-4207-95a4-1efd21910551.png)

Any housing (normal, free-company chamber, apartment) > `/housing` > Indoor Furnishings

The texture for it is `ui/uld/housinggoods_hr1.tex`

**Comment by skotlex** [comment]
Icon modified it, but could not find the border texture. The `SupplyMasterPiece` texture was also not. 🤔 
![화면 캡처 2021-12-26 075428](https://user-images.githubusercontent.com/31692408/147395009-a8954415-a184-4162-8fc1-05165b76eae5.png)

**Comment by skotlex** [comment]
Find it. `Journal_hr1.tex`
![화면 캡처 2021-12-26 085147](https://user-images.githubusercontent.com/31692408/147395667-6bb52892-7cb1-460e-bf3e-73f7a97f5f80.png)
