### ISSUE TITLE
MSQ Icon has a weird question mark

### ISSUE THREAD

**Issue by cglatot** [skotlex/ffxiv-material-ui#265]
**Screenshots**
![image](https://user-images.githubusercontent.com/10439257/141794213-1904f789-6863-4bb6-8b9c-0e0ed81dcad7.png)

You can see on the top right side of the icon is the ? in a diamond. It is attached to the MSQ icon, if you click the question mark, it clicks the entire MSQ icon.

**To Reproduce**
Install the latest release of the Material UI. The MSQ icon is like that. Same happened with my friend as well.

**Comment by skotlex** [comment]
The texture may be confused, but there is no meaning for that symbol.

**Comment by cglatot** [comment]
Apologies for the delayed response to this.

I don't know what you mean by "texture may be confused" - but it's in your actual texture pack, whereas it should not be:

![image](https://user-images.githubusercontent.com/10439257/143590793-95b88b19-b1d5-4d24-8d6e-87f0071932ec.png)

If you look at the original texture in the game, there is nothing but the border for the MSQ there:

![image](https://user-images.githubusercontent.com/10439257/143591013-5413bb7d-f8bd-4358-93dd-788657338d0f.png)

The problematic files are here:

https://github.com/skotlex/ffxiv-material-ui/blob/master/4K%20resolution/Black/Saved/UI/HUD/ScenarioTree/scenariotree_hr1.psd

**Comment by skotlex** [comment]
What I want to say is that the question mark symbol is simply put in my taste.

**Comment by cglatot** [comment]
Ahhhhhhh okay, I get you now.

In my opinion it looks really out of place. Typically speaking, a question mark icon like that would be clicked on to give you help with something, but in this case it does not do that. So it just looks, to me, like a texture that has errored, or something has gone wrong.

I made a copy of the texture and patched it out myself, but I'm surprised that nobody else has brought it up.

Otherwise, I love everything else, and thank you very much for your work. Compared to everything else, this is just a minor annoyance 😅

**Comment by skotlex** [comment]
Since no one has mentioned the issue of this so far, I was not aware of it. Personally, I think it is reasonable to some extent because clicking on the question symbol displays the destinate position of the quest. 

If the same inquiry is received by multiple people in the future, I will think about expressing it in a different way. Thank you for your opinion.

**Comment by Niccer56** [comment]
I think it looks out of place myself. I get the idea but it's not really intuitive in my opinion. A big button with a quest name is already intuitive enough for people to know to click it for destination.

**Comment by Grinch** [comment]
I have to agree that it does appear out of place based on what the UI element as a whole does.

**Comment by skotlex** [comment]
The symbol was removed and the horizontal length was modified to be the same as the original.
![화면 캡처 2021-12-26 075641](https://user-images.githubusercontent.com/31692408/147395055-80d8c3fe-8f4a-4ffd-8d30-9f30ceeb387b.png)
