### ISSUE TITLE
EndWalker Plan

### ISSUE THREAD

**Issue by skotlex** [skotlex/ffxiv-material-ui#271]
Regarding the schedule after EW, (KST)
~21.12.05 | Patch 6.0 Preliminary - Hot-fixes for broken/missing textures.
~22.01.02 | Patch 6.0 Complete - Polish 6.0 contents and work on anything missed in the preliminary release.

6.0 Optimization may be advanced or delayed depending on the condition. I don't know how much it will change from the preliminary release and I also want to enjoy the game as a player, so please wait a little longer for the optimization.

**Comment by Iaotle** [comment]
Good luck! First thing I noticed when launching the game ;)

**Comment by haroldiedema** [comment]
Although probably some features will be incomplete/missing, can we still safely use the current/latest build in Endwalker without breaking important stuff?

**Comment by skotlex** [comment]
> Although probably some features will be incomplete/missing, can we still safely use the current/latest build in Endwalker without breaking important stuff?

It is not recommended to use Material UI 5.5.1 in Patch 6.0.

**Comment by dambros** [comment]
Thanks for the heads up. What is the best way to remove the Material UI prior to the new patch?

**Comment by skotlex** [comment]
> Thanks for the heads up. What is the best way to remove the Material UI prior to the new patch?

Please ensure you navigate to `help > start over` in `TexTools` before you update the game to prevent the release causing game file corruption.

**Comment by Zhumos** [comment]
First of all, thanks @skotlex for the awesome work on mod. The dark theme is absolutely stunning!

I've been using it in 6.0 with the initial textools 6.0 release (aware of the risk of potential issues) and the only oddity I've noticed so far is the scholar icon being the default and the reaper icon being the companion (chocobo) material icon. I'm not far in though.

**Comment by Azurealistic** [comment]
Thank you for all the work! Just a note but, on marketboard: 

![image](https://user-images.githubusercontent.com/5000092/144876903-ede51ed3-1cf0-4e4f-a85d-1634377a5b73.png)

Sage/Reaper icons are old/wrong?

Same with char window: (Unsure if this is because they are not unlocked for me yet?)

![image](https://user-images.githubusercontent.com/5000092/144876987-c5000a98-53b1-48b4-8e6f-4fa21f41f5de.png)

**Comment by AmenneHolelane** [comment]
> Thank you for all the work! Just a note but, on marketboard:
> 
> ![image](https://user-images.githubusercontent.com/5000092/144876903-ede51ed3-1cf0-4e4f-a85d-1634377a5b73.png)
> 
> Sage/Reaper icons are old/wrong?
> 
> Same with char window: (Unsure if this is because they are not unlocked for me yet?)
> 
> ![image](https://user-images.githubusercontent.com/5000092/144876987-c5000a98-53b1-48b4-8e6f-4fa21f41f5de.png)

these textures will be added with the release outlined in the original text, don't expect any official solution until at least January 2nd.

**Comment by Azurealistic** [comment]
Ah, thanks. I guess I misunderstood what was meant by that. Looking forward to it then.

**Comment by Chymai** [comment]
Is the rested Exp distinguishable from a blank exp bar? I have already leveled up, I shouldn't have very much rested exp left but the bar is only one color. 
![image](https://user-images.githubusercontent.com/79292407/145736252-7d90a1a6-ff54-4253-9064-91fc8756005a.png)

**Comment by skotlex** [comment]
> Is the rested Exp distinguishable from a blank exp bar? I have already leveled up, I shouldn't have very much rested exp left but the bar is only one color. ![image](https://user-images.githubusercontent.com/79292407/145736252-7d90a1a6-ff54-4253-9064-91fc8756005a.png)

https://github.com/skotlex/ffxiv-material-ui/issues/168

**Comment by Chymai** [comment]
> > Is the rested Exp distinguishable from a blank exp bar? I have already leveled up, I shouldn't have very much rested exp left but the bar is only one color. ![image](https://user-images.githubusercontent.com/79292407/145736252-7d90a1a6-ff54-4253-9064-91fc8756005a.png)
> 
> #168

I understand the 3 different colors. I have leveled up a few times, and never saw a 3rd color in the exp bar.

**Comment by skotlex** [comment]
> > > Is the rested Exp distinguishable from a blank exp bar? I have already leveled up, I shouldn't have very much rested exp left but the bar is only one color. ![image](https://user-images.githubusercontent.com/79292407/145736252-7d90a1a6-ff54-4253-9064-91fc8756005a.png)
> > 
> > 
> > #168
> 
> I understand the 3 different colors. I have leveled up a few times, and never saw a 3rd color in the exp bar.

If so, I think there are still additional experiences left. What is certain is to disable `exp_gauge_hr1.tex` and check your exp bar.

**Comment by Grinch** [comment]
> > > > Is the rested Exp distinguishable from a blank exp bar? I have already leveled up, I shouldn't have very much rested exp left but the bar is only one color. ![image](https://user-images.githubusercontent.com/79292407/145736252-7d90a1a6-ff54-4253-9064-91fc8756005a.png)
> > > 
> > > 
> > > #168
> > 
> > 
> > I understand the 3 different colors. I have leveled up a few times, and never saw a 3rd color in the exp bar.
> 
> If so, I think there are still additional experiences left. What is certain is to disable `exp_gauge_hr1.tex` and check your exp bar.

Personally I made this change for my own use which in my opinion keeps in the spirit of the original experience bar while still allowing the ability to see the various rested exp states.

![exp_gauge_hr1_modified](https://user-images.githubusercontent.com/963480/145748685-fc584bc0-24db-4590-b26e-915f36a3a595.png)

Blue = Rested overflows to next level
Orange = Rested ends on current level

**Comment by christo1997** [comment]
[is](https://github.com/skotlex/ffxiv-material-ui/issues/271#issuecomment-986934735)
are new textures released for new jobs ? because I still don't have them in .ttmp2 files.

**Comment by christo1997** [comment]
> > Thank you for all the work! Just a note but, on marketboard:
> > ![image](https://user-images.githubusercontent.com/5000092/144876903-ede51ed3-1cf0-4e4f-a85d-1634377a5b73.png)
> > Sage/Reaper icons are old/wrong?
> > Same with char window: (Unsure if this is because they are not unlocked for me yet?)
> > ![image](https://user-images.githubusercontent.com/5000092/144876987-c5000a98-53b1-48b4-8e6f-4fa21f41f5de.png)
> 
> these textures will be added with the release outlined in the original text, don't expect any official solution until at least January 2nd.

are new textures released for new jobs ? because I still don't have them in .ttmp2 files.

**Comment by skotlex** [comment]
The new job icon was newly added from the 6.0.1 version. If it still doesn't work, try applying it again after start over.

**Comment by christo1997** [comment]
> The new job icon was newly added from the 6.0.1 version. If it still doesn't work, try applying it again after start over.

it doesn't work at all with 6.0.2 or 6.0.1, I didn't have any job icons changed in game even if I uninstalled TexTool and restart from zero. But, it works fine with Penumbra.

**Comment by skotlex** [comment]
> > The new job icon was newly added from the 6.0.1 version. If it still doesn't work, try applying it again after start over.
> 
> it doesn't work at all with 6.0.2 or 6.0.1, I didn't have any job icons changed in game even if I uninstalled TexTool and restart from zero. But, it works fine with Penumbra.

It can be an index issue. Please refer to this. https://github.com/skotlex/ffxiv-material-ui/blob/master/FAQ.md#-icons-are-missing-or-displaying-incorrectly-after-patches

**Comment by AmenneHolelane** [comment]
> > The new job icon was newly added from the 6.0.1 version. If it still doesn't work, try applying it again after start over.
> 
> it doesn't work at all with 6.0.2 or 6.0.1, I didn't have any job icons changed in game even if I uninstalled TexTool and restart from zero. But, it works fine with Penumbra.

if you didn't specifically start over _**and**_ redownload the backup files, just uninstalling and reinstalling TexTools doesn't do *anything*

**Comment by KrayElesis** [comment]
The contents job icon occasionally show up,when clike any button the icon will change.it doesn't work all the time.
![H7N4E8R~1 NFLZM@FGGZ)CC](https://user-images.githubusercontent.com/98692753/151699610-4b122ece-b3b0-45df-9232-b479446802e0.png)
![CT`W SEARIOJV_8NVZ@@Z%X](https://user-images.githubusercontent.com/98692753/151699612-baac6a5f-a8fc-46a8-94a2-cd43d09c9f36.png)
![HM%6O3O8(%CB@Z95J5A6PAX](https://user-images.githubusercontent.com/98692753/151699615-6f9a2f38-12e0-47d0-822c-32a286ff7cc8.png)
![~906F$BCY0M68@Z LPMKKI](https://user-images.githubusercontent.com/98692753/151699617-cb6d98bc-a7ba-4d5c-bd5e-40d00afe18d0.png)
g

**Comment by AmenneHolelane** [comment]
https://github.com/skotlex/ffxiv-material-ui/blob/master/FAQ.md#-icons-are-missing-or-displaying-incorrectly-after-patches
specifically start over _and_ redownload the backup files
