### ISSUE TITLE
No issue--just a suggestion

### ISSUE THREAD

**Issue by allogator** [skotlex/ffxiv-material-ui#273]
Hi!  Been using your UI for a long time now as it is definitely the prettiest of the bunch. I was updating for Endwalker and that's when I realized why I sometimes had problems reapplying if an update broke Textools. I assumed you were supposed to open 1 in the Options, choose 1 or 2, then choose 1 or 2 or 3 or 4, etc, down the list. Sometimes if I wasn't using my head I'd, for example, open 03.Icon and think I was supposed to choose one of the 1-13.  Even though they're labeled differently I'd just see the numbers and look over everything else because the other folders are set up in substructures but Icon isn't.

This isn't a big deal and I may be the only one not looking at it the right way but any possibility future Releases have the folders split up?

Screenshot attached of what I think are the right splits and what I'm suggesting
![Current_Icon_folder](https://user-images.githubusercontent.com/19312403/145069523-c78f92eb-7f0c-4652-9004-e94b02b8034d.png)
![Icon_Folder_Split](https://user-images.githubusercontent.com/19312403/145069532-896aca10-58dc-4db2-bd01-72a66894aa3d.png)

**Comment by skotlex** [comment]
Thank you for the suggestion. I'll refer to it when I distribute options in the next version.

**Comment by cht47** [comment]
+1 for the idea. 
In addition to that I would recommend to add a prefix to the file names. 
![image](https://user-images.githubusercontent.com/2283180/146215518-07fe455e-6faa-4b05-9e8a-45931cd79dac.png)
I have a folder with all the texture replacements and it's hard to track what I always use and which I have to update. 
Maybe with the suggested numbers or an identifier like partylist_ , macro_ , maincmd_ etc.
