### ISSUE TITLE
new UI is not showing up

### ISSUE THREAD

**Issue by Karma1988** [skotlex/ffxiv-material-ui#274]
I installed like everytinme the new UI and it is not showing up. In FFTools it is enabled BUT nothing to see in Game. Is there something i missing?
![ffxiv_08122021_102205_999](https://user-images.githubusercontent.com/81153629/145182812-ba4922d5-5c95-4183-b789-65df8865f987.png)

**Comment by Karma1988** [comment]
> https://github.com/skotlex/ffxiv-material-ui#in-game-setting

already done and that is my standard UI. worked for endwalker but anymore

**Comment by Nitzowsky** [comment]
Same problem here, this is the screen you want?
![untiled](https://user-images.githubusercontent.com/20094216/145449240-3857217e-030d-4ca9-823e-f29fcfcb16c4.jpg)
e
