### ISSUE TITLE
NPC Text in Japanese Not English?

### ISSUE THREAD

**Issue by Dustyragon** [skotlex/ffxiv-material-ui#275]
I'm not sure what's going on here, if it's QuickLauncher or the UI mod. But my game is set to English, NPC text is in Japanese though and I can't.. read Japanese. I can't really progress the MSQ since I can't read the text.

**Comment by Caliel666** [comment]
remove the echoglossian plugin

**Comment by Dustyragon** [comment]
Huh, that was the cause, thank you.

**Comment by greevir** [comment]
It defaults to Cantonese, I believe. You can go into the settings and change it to english.

**Comment by Caliel666** [comment]
if you want to have the game on english you 100% don't need echoglossian, also this is irrelevant to material ui, could you please close this?
