### ISSUE TITLE
Will you be adding Circle Status as 4k?

### ISSUE THREAD

**Issue by Rinmini** [skotlex/ffxiv-material-ui#276]
I've been using Rien's (because I really like the Circle Status) and yours alternately for awhile. Since it looks so much better in UI 4k and as Rien's mods won't be updated anymore in 6.0, so it's a hard yes to use yours from now on. But apparently the Circle Status can't be replaced nor found anywhere, would you be adding them in the future?

**Comment by skotlex** [comment]
It is not planned in the future. I can't afford to make and manage it.
