### ISSUE TITLE
Macro Glow Job Icon does not change Sage and Reaper Icons

### ISSUE THREAD

**Issue by Chymai** [skotlex/ffxiv-material-ui#278]
**Screenshots**
![Job Icon Issue](https://user-images.githubusercontent.com/79292407/145721790-0d974331-9f54-40c0-848d-7a83aaa9ee84.PNG)

**Describe the image**
The job icon for Sage and Reaper is not the same as the rest of the job icons, as it is not transparent. 

**To Reproduce**
1. Download/Install "Material 4K-UI BLACK v6.0.0 (Preliminary).ttmp2"
2. Go to "Options.4k.zip"
2. Click on "03.Icon"
3. Click on "Macro Glow Job Icon Diff Range DPS Color.ttmp2"
4. Instal in texttools

**Additional context**
Please let me know if I did something wrong on my end.

**Comment by Chymai** [comment]
Apologies. forgot to add these images as well. 
![Job Icon Issue 2](https://user-images.githubusercontent.com/79292407/145722256-a41fabb8-b254-4921-b6e6-8e4a2533f1fc.PNG)
![Job Icon Issue 3](https://user-images.githubusercontent.com/79292407/145722380-befbb5fd-8180-4f6d-8d01-86788131a317.PNG)

**Comment by Sevii77** [comment]
https://github.com/skotlex/ffxiv-material-ui/issues/271#issuecomment-986934735
