### ISSUE TITLE
Sage Icon Issue

### ISSUE THREAD

**Issue by crazyace** [skotlex/ffxiv-material-ui#279]
![image](https://user-images.githubusercontent.com/573449/145730267-d49ad05b-4357-4d88-a453-1f1ba47e4d00.png)

Hello Team,

I'm not sure why the normal Sage Job Icon isn't showing here.

**Comment by UnstoppableKhaos** [comment]
Pretty sure Skotlex has not included anything in the pack that touches the SGE icon, could you have been messing around with something else? If you backed up the indexes, you can restore them by going to "Help > Start Over" in TexTools; you can then reapply Material UI after.

**Comment by Caliel666** [comment]
>  "Help > Start Over"
after doing that, download new indexes, as that is your issue, after getting new indexes install material ui again

**Comment by skotlex** [comment]
https://github.com/skotlex/ffxiv-material-ui/blob/master/FAQ.md#icons-are-missing-or-displaying-incorrectly-after-patches
