### ISSUE TITLE
SMN Icon Issues

### ISSUE THREAD

**Issue by Deckerz** [skotlex/ffxiv-material-ui#280]
**Screenshots**
![image](https://user-images.githubusercontent.com/2226816/145785027-58856b22-7915-4876-840d-59699eebbecd.png)

**Describe the image**
The SMN Icons aren't all Discord UI'ified

**To Reproduce**
I just installed discord mod after fresh install of FF

**Comment by skotlex** [comment]
Please wait 6.0 complete version
