### ISSUE TITLE
Graphical Glitch Job Hud: Dancer

### ISSUE THREAD

**Issue by cmgau** [skotlex/ffxiv-material-ui#281]
![image](https://user-images.githubusercontent.com/82530248/146094192-fab38d51-c8d7-43fb-a75b-390215f0dd67.png)

I'm getting a weird affect on the DNC job. I've tried reinstalling the mod several times.

**Comment by skotlex** [comment]
https://github.com/skotlex/ffxiv-material-ui/blob/master/FAQ.md#icons-are-missing-or-displaying-incorrectly-after-patches
