### ISSUE TITLE
When not accesible, show the lock icon in an accent color.

### ISSUE THREAD

**Issue by FFXIVRP-Developer** [skotlex/ffxiv-material-ui#283]
![image](https://user-images.githubusercontent.com/40615045/147119553-3f914a0b-ba89-46d5-aeac-7c52611440e7.png)
![image](https://user-images.githubusercontent.com/40615045/147119907-e2595248-e46b-430c-b6ff-0036fc1af1fd.png)

Right now the color of the text and the color of the lock is the same so it turns harder to read what's accessible,
This theme has an accent color already, being purple over the tabs and windows. Is it possible to add a purple lock so it's easier and faster to read what's locked? Also the same for the checkmark, so it's easier to know what's highlighted as part of the queue of duties selected.

Maybe something like you have already in the duty finder selection.
![image](https://user-images.githubusercontent.com/40615045/147120093-3abbfadd-4ac6-48e9-8c4b-05f137e87f6f.png)

Thank you for your fantastic job,

**Comment by skotlex** [comment]
![화면 캡처 2021-12-26 075107](https://user-images.githubusercontent.com/31692408/147394980-9d24a936-7285-4331-9bee-85e68a3d10b7.png)
