### ISSUE TITLE
Money font alignment

### ISSUE THREAD

**Issue by skotlex** [skotlex/ffxiv-material-ui#284]
From. `shikatsu`

![unknown](https://user-images.githubusercontent.com/31692408/147394735-3b773f34-4623-497e-af75-25495d2585d7.png)

**Comment by skotlex** [comment]
![unknown](https://user-images.githubusercontent.com/31692408/147394965-75a79fa5-221d-442c-b022-c914d75ebbd5.png)

**Comment by mtshika** [comment]
![money_number_hr1](https://user-images.githubusercontent.com/63021541/147470464-0d488bb1-d06c-491e-adf6-b3a23e10b609.png)
Redid alignments as balanced as possible using '2' as the base.
