### ISSUE TITLE
Nothing change.

### ISSUE THREAD

**Issue by KamishiroYuu** [skotlex/ffxiv-material-ui#286]
I installed the mod with TexTools but nothing change in the game.

**Comment by Caliel666** [comment]
![image](https://user-images.githubusercontent.com/38433434/147604878-26f3fda5-0c35-40de-a62f-d6da0666eb6f.png)

**Comment by KamishiroYuu** [comment]
Thanks, now it's working, I didn't see that part.

> ![image](https://user-images.githubusercontent.com/38433434/147604878-26f3fda5-0c35-40de-a62f-d6da0666eb6f.png)
