### ISSUE TITLE
FC rank administration buttons not themed

### ISSUE THREAD

**Issue by swaj** [skotlex/ffxiv-material-ui#287]
**Screenshots**
![rank-buttons-missing](https://user-images.githubusercontent.com/317609/147685492-461e5d5b-a05d-41ce-b585-8689fa01e36d.png)

**Describe the image**
I'm using the latest 6.01 update, installed via Penumbra.  I've noticed that the FC rank administration buttons are still using the default textures.  It's a small issue, and honestly it doesn't bug me at all.  But I figured I'd let you know, just in case.

**To Reproduce**
1. Open the FC menu (Social > Free Company)
2. Click the "Rank" tab on the left side.
3. Select any rank to view its authorizations.

**Comment by skotlex** [comment]
This can't be reflected in 6.0.2 patch because I need more experience, but I'll consider it later.

**Comment by skotlex** [comment]
Is this only available to the FC administrator? 
I don't see that kind of menu in the social window

![화면 캡처 2022-01-04 001134](https://user-images.githubusercontent.com/31692408/147947233-7ade3574-107c-4dcf-aafa-5528456c6b14.png)

**Comment by swaj** [comment]
It's not on the social window.  It's actually in the FC window.  It's not that critical, imo.  I just didn't know if it was missed since Endwalker.
![fc-ranks](https://user-images.githubusercontent.com/317609/148468720-7fe364db-c2fb-406c-a7fe-b02a620c1a5b.png)

**Comment by skotlex** [comment]
I checked, but it may take a long time or may not be able to modify because I don't know what that texture is. Please excuse me.

**Comment by alphaONE2** [comment]
I just checked which texture these buttons are on. They're all on `ui/uld/freecompany_hr1.tex`. The 5 gray buttons near the bottom of this texture.

**Comment by skotlex** [comment]
![화면 캡처 2022-05-01 011029](https://user-images.githubusercontent.com/31692408/166113415-629b49dc-d410-4d82-b936-e982fa220900.png)
