### ISSUE TITLE
Different Accent Color Options

### ISSUE THREAD

**Issue by mattarolla** [skotlex/ffxiv-material-ui#288]
Hello. It would be cool if there are some options for different accent colors aside from the default Purple accent. I know there is a Penumbra mod that can change this but I personally do not feel comfortable using Dalamud plugins in my game due to how intrusive it is with modifying the game's memory and packets.

**Comment by Caliel666** [comment]
and modifying the game's own files is okay? anyway this won't happen since it's way too much work for skotlex to make different color options for the entire ui like that

**Comment by mattarolla** [comment]
I mean I see what you mean but there is a little bit of a difference in modifying the game's files which are purely cosmetic and a plugin that directly injects into the game and can modify network packets and the way the game's code is run. I completely understand though. I was just hoping for a few popular color options lie red, blue, etc. There are options already for shield colors so I didn't think it was an intrusive request. My apologies.

**Comment by Ottermandias** [comment]
Just so you know, TexTools intrusively modifies pure data tables in ways that breaks how they're supposed to work, not just cosmetic files.

**Comment by AmenneHolelane** [comment]
https://goatcorp.github.io/faq/xl_troubleshooting#q-are-xivlauncher-dalamud-and-dalamud-plugins-safe-to-use

Unlike TexTools, Penumbra doesn't fuck up your client files, nor can it. Everything is done without touching the actual game files. Network Packet modification is not a part of this process, nor is it even done

**Comment by mattarolla** [comment]
Thank you all for the clarification. I definitely don't want to risk using TexTools if it has a similar level of instrusiveness. 

I understand though that most of the plugins on the official Dalamud repository are safe to use. I was under the impression that there is the existence of some that are not safe but Dalamud acts as a way to enable those is that doesn't sit right with me. I just personally am not comfortable with installing Dalamud. So sorry if I came off the wrong way with y'all.
