### ISSUE TITLE
achievements are not skinned

### ISSUE THREAD

**Issue by xuomi** [skotlex/ffxiv-material-ui#289]
**Screenshots**
![achievs](https://user-images.githubusercontent.com/96959456/147861018-ce7f53a2-dc56-4d73-9a21-21f1b9d92d4c.png)

**Describe the image**
So far this is the one thing I've found that seems to come with the default style...

**To Reproduce**
1. Go to 'Character'
2. Click on 'Achievements'

**Additional context**
Before I updated to the latest version, the skin for achievements worked. I ended up starting over and unloading all mods and then loading only the base of Material UI without any of the options just to see if maybe it was an option selection messing it up, but it still comes up as the base game skin. Not sure if I am somehow doing something wrong, but it worked prior to this updated version.

I am using TexTools.

**Comment by skotlex** [comment]
I decided that due to this reorganization, the achievements window no longer has to apply the material ui style. Above all, the existing style cannot be applied because the letters have been changed to black series.

**Comment by xuomi** [comment]
So, the achievement window will always look like the game default?

Also, I am not sure what you mean by "the letters have been changed to black series," sorry.

**Comment by skotlex** [comment]
So, the achievement window will always look like the game default?
> yes

Also, I am not sure what you mean by "the letters have been changed to black series," 
> Because the letters of achievement are black, I can't apply the material ui style as before.
