### ISSUE TITLE
Gear & Inventory Grid Displays Belt Slot [Release v6.0.1 Complete]

### ISSUE THREAD

**Issue by jonpertwee** [skotlex/ffxiv-material-ui#290]
**Screenshots**
![Default Gear/Inventory Grid](https://i.gyazo.com/6c84c31932a03d8e42c90d72663583c0.png)
![Material UI Gear/Inventory Grid](https://i.gyazo.com/aaf05a2d6f4e37450c20c59a0c5455a3.png)

**Describe the image**
If you look at the default vs the modded Gear & Inventory Grids, you can tell that there's an extra circle on the left-side gear, presumably from when the game had useable belts. Obviously an extremely minor thing, but figured it worth bringing up regardless?

**Comment by skotlex** [comment]
![화면 캡처 2022-01-16 205120](https://user-images.githubusercontent.com/31692408/149658775-83ef5f53-f642-4434-8248-9853945133b5.png)
