### ISSUE TITLE
Weird spacing in auto-translator box.

### ISSUE THREAD

**Issue by Wolfehart** [skotlex/ffxiv-material-ui#291]
Screenshot
![ffxiv_dx11_2022-01-05_10-22-37](https://user-images.githubusercontent.com/14332574/148152442-9faf21d7-ccf5-4a58-905c-0489dad664a0.png)
![brave_2022-01-05_10-40-09](https://user-images.githubusercontent.com/14332574/148152453-7b2079d7-3cd4-4dfd-946a-edc3081e1a40.png)

Describe the image
It's not really super important change, but the spacing above the first entry of the auto translator seems to be smaller than normal. The first image is the mod, the second is the vanilla.
I installed the ui mod via textool.

To reproduce:
1. Type any auto translation text. E.g Hello
2. Press Tab.

**Comment by skotlex** [comment]
![화면 캡처 2022-01-16 204710](https://user-images.githubusercontent.com/31692408/149658642-e3e41c61-a448-47d9-a71c-db16c1569780.png)
![화면 캡처 2022-01-16 204731](https://user-images.githubusercontent.com/31692408/149658645-fb44d6e4-f8fb-4604-8301-d8847073a325.png)
