### ISSUE TITLE
Some quest icons not showing up on map/minimap

### ISSUE THREAD

**Issue by ralinchan** [skotlex/ffxiv-material-ui#293]
I installed through Penumbra as per the recommended method. It seemed to be working fine yesterday. Penumbra had an auto update and as far as I can tell, there's no major changes and as the update instruction indicated, I rediscovered mods. Everything else appeared to be functioning but for whatever reason, some quest icons no longer appear on the map or minimap. They do appear on a map popup if I click the map button from the quest log but not on the general game map.

Here's an example with Ursandel with a purple quest icon for "Maniac Manor" - https://i.imgur.com/GD33jr2.png

It appears to not be related to whether or not I am actively tracking it on the showing duty list on the right as if I advance it beyond the "purple" icon step, the next step is a green check mark with gold trim and that shows up on the map and minimap without any issue. It seems specific to purple quest icons.

**Comment by skotlex** [comment]
Is there the same problem if you disable all of penumbra's plugins?

**Comment by ralinchan** [comment]
The only Penumbra plugin I have is Material UI

**Comment by skotlex** [comment]
UI plugin doesn't affect that. Please disable plugin and make sure there's no problem with the original.

**Comment by ralinchan** [comment]
I'm not sure what you're asking me to disable. The only things I have running besides stock is GShade (the shader) and Material UI through Penumbra.

You want me to uninstall GShade to see if that's what the issue is? Since GShade was not updated between yesterday and today.

**Comment by skotlex** [comment]
It means to disable the material ui of penumbra. It has nothing to do with gshade.

**Comment by skotlex** [comment]
I am sure that material ui has nothing to do with your current problem, but I wanted to see that the same symptoms appeared even after disable material ui just in case.

**Comment by ralinchan** [comment]
So the specific subset of quests that ran into this issue I completed (I needed to progress the game) and i've not run into any other set that has this specific problem. When I do, i'll run this disable test to see what the result is.

For reference, it affected all the post ARR purple unlocks but only those specific ones. Those ones you had to fedex around to unlock the hard mode dungeons.

**Comment by skotlex** [comment]
If so, I'm sorry, but I have no way of talking about this phenomenon anymore. However, what I can talk about is that UI mods cannot affect the phenomenon in any way. The only problem that can be problematic is when the game index is broken. But since you're using penumbra, it can't be a cause.

**Comment by AmenneHolelane** [comment]
That quest is not active in your journal. The map can only track the quests that are displayed in that quest bar on the right hand side of the screen. Please check the box to make the quest active or  complete some of the other quests in your journal. 

This is not a mod issue but rather a game limitation. [See here for another example](https://www.reddit.com/r/ffxiv/comments/3apcp0/quests_missing_from_the_map/)
