### ISSUE TITLE
somwthing wrong with my dialogue box i thought it used to be white?

### ISSUE THREAD

**Issue by Froastyy** [skotlex/ffxiv-material-ui#294]
![image](https://user-images.githubusercontent.com/97296637/148555357-41c1bd1b-27fb-454c-976e-9f525029771a.png)

**Comment by skotlex** [comment]
It seems to be the influence of reshade or gshade. I didn't choose yellow with such high contrast.

**Comment by AmenneHolelane** [comment]
Could be gshade, reshade, or Night Shift in the PC settings. I cannot replicate this issue
