### ISSUE TITLE
Round hotbars and gauges x black theme

### ISSUE THREAD

**Issue by rsigim** [skotlex/ffxiv-material-ui#295]
Its possible to make as optional the round corners from discord into the black 4k theme?
I was just using the discord one because I think the round corners on gauges and hotbars fits better,
and since we got a 4k theme I think is better to have those as optional that wanting a full theme just for this.

Just this three:
icona_frame
parameter_gauge 
jobhudsimple_stack

Thank you!

**Comment by vaultor** [comment]
Yes, I preferred the Discord version because of the rounded corners.
Since you're focusing only on Black version, I'm hoping we can have rounded corners as an option.
Thank you for considering this!

**Comment by skotlex** [comment]
It can be considered later when discord theme is completed. And the round corner has quite a lot of texture as well as that. (ex. window, button etc...) I don't have a plan at the moment, so please understand.

**Comment by rsigim** [comment]
Ah no, I wasnt asking for a full theme just the assets that I mentioned in OP

They are that change this three:
![image](https://user-images.githubusercontent.com/22231296/149451227-68f526f0-71c7-4f24-8c36-e7c164e1f4e2.png)

Back in the FHD theme we could get those options from one theme to another, but with just the black 4k I was looking for those as optionals.

Anyway, Thanks.

**Comment by skotlex** [comment]
I understand what you mean. But what I want to talk about is that if you provide what you requested as an option, other people will ask me to create a specific round option like you. If this happens, the production of discord theme will continue to be delayed, so please understand.

**Comment by rsigim** [comment]
ohh, Sorry! I didn't mean to, for me the only diferences for black to discord was the round corners and the color itself.
I can patiently wait for the full release then. Again, Apologies!
