### ISSUE TITLE
What have I done wrong?

### ISSUE THREAD

**Issue by SavuRMihail** [skotlex/ffxiv-material-ui#296]
Hi, I downloaded the whole zip, extracted it somewhere, then went "ModPacks\OPTIONS 4K\" and started copy pasting mods I like into a folder I made. Then I imported everything from the folder into FF TexTools and all is working except the windows background.
I imported from "0.5 Window" -> "Window Style" -> "0.1 Non-Selected Windows Default..." 

In game my UI is set to 4k. Everything else works.

**Comment by skotlex** [comment]
Please upload a screenshot of your in-game status.

**Comment by SavuRMihail** [comment]
I have solved it. I was stupid - had to have the default thing as well and then the additional stuff from Options 4k...
I am sorry sir.
God like tho thanks for responding.
