### ISSUE TITLE
Teleport Menu Icons with Color

### ISSUE THREAD

**Issue by malspills** [skotlex/ffxiv-material-ui#297]
When I updated to the latest version I noticed that the teleport menu top icons were swapped to a black background version. Would it be possible to make an alternate version for these that have their original color? I'm a simple man and now I keep clicking the wrong ones lol. I'll donate 10$ right now if you say you're willing to think about it 😃 

<img width="470" alt="tele" src="https://user-images.githubusercontent.com/72996151/149857175-441fe827-e433-4a33-8363-23b48d49abd0.png">

**Comment by skotlex** [comment]
I tested it before, but I didn't like it as much as I thought, so it became the current design. If I have time, I will upload a sample separately and provide it to you.

**Comment by skotlex** [comment]
Which do you prefer? Or do you want to suggest something else?

## Sample 1
![화면 캡처 2022-01-23 101730](https://user-images.githubusercontent.com/31692408/150661146-9e361d06-edf9-41ac-8f85-0da98dcd6edf.png)

## Sample 2
![화면 캡처 2022-01-23 104354](https://user-images.githubusercontent.com/31692408/150661424-a92642d9-cfa8-4b9f-84e2-835d56f955de.png)

**Comment by malspills** [comment]
sample1 is perfect!

**Comment by skotlex** [comment]
[Teleport Background Color.zip](https://github.com/skotlex/ffxiv-material-ui/files/7919588/Teleport.Background.Color.zip)
