### ISSUE TITLE
I am having an issue...

### ISSUE THREAD

**Issue by werewolfboy13** [skotlex/ffxiv-material-ui#298]
Since 6.0 have not been able to get the UI installed, is there something I am doing wrong?

![image](https://user-images.githubusercontent.com/43587009/150208860-315edb07-1cf1-43d4-acd9-f61d82b7436d.png)
![image](https://user-images.githubusercontent.com/43587009/150208875-b23617d6-92e2-44e5-971e-fb04c8be070f.png)
![image](https://user-images.githubusercontent.com/43587009/150208982-d6397471-de9a-4304-80a7-43c3790c3b02.png)

I can't do a full screenshot since it is in 4k

**Comment by Caliel666** [comment]
![image](https://user-images.githubusercontent.com/38433434/150209791-5bd4f065-c899-422a-8f7d-8c4581e0148a.png)

**Comment by werewolfboy13** [comment]
Thank you... I feel dumb.
