### ISSUE TITLE
Crafting Efficiency Calculations appears to have a texture glitch

### ISSUE THREAD

**Issue by Felys1998** [skotlex/ffxiv-material-ui#301]
**Screenshots**
![image](https://user-images.githubusercontent.com/2600400/157053981-95174c1c-6b5c-4edf-a6ab-43edaa549530.png)

**Describe the image**
There is a line and gradient that appears out of place and overlaps text in the window

**To Reproduce**
Please explain how you can access the menu:
Start any craft and click on Calculations to open the window

**Additional context**
Penumbra settings: 
![image](https://user-images.githubusercontent.com/2600400/157054367-56c04121-6089-413e-bc82-a6da805774fd.png)

**Comment by skotlex** [comment]
This is probably a problem with penumbra, so you should inquire here. https://github.com/Sevii77/ffxiv_materialui_accent
![화면 캡처 2022-03-13 232426](https://user-images.githubusercontent.com/31692408/158064193-add486e2-d723-4ae4-bf36-0b243a38e527.png)

**Comment by Sevii77** [comment]
Penumbra version has no issues for me, it might be a plugin or corrupted indexes if you used textools before. It's also possible something broke while applying, so try reapplying it to see if that fixes the issue.
![image](https://user-images.githubusercontent.com/20374966/158064418-c745685d-7af9-4699-bfe5-95643339daaa.png)

**Comment by skotlex** [comment]
Please refer to the document below for index issues.
https://github.com/skotlex/ffxiv-material-ui/blob/master/FAQ.md#-icons-are-missing-or-displaying-incorrectly-after-patches

**Comment by Felys1998** [comment]
> Penumbra version has no issues for me, it might be a plugin or corrupted indexes if you used textools before. It's also possible something broke while applying, so try reapplying it to see if that fixes the issue.

never used textools on this install so maybe something didnt apply right when i installed this. I've tried reapplying and it doesn't fix it though so i'm not sure if im doing something wrong.

**Comment by skotlex** [comment]
Is there any problem when you test with vanilla skin without mods?

**Comment by Felys1998** [comment]
yep same issue after reapplying with no mods enabled.

**Comment by skotlex** [comment]
I wonder if the same symptoms occur even when the mods is not applied. If so, it would be an index problem, otherwise I don't know from there. 🤔 There may be a method of completely deleting and reinstalling penumbra and material ui plugin.

**Comment by Felys1998** [comment]
turned off penumbra, hit up the aesthetician, checked that everything looked back to defaults... gonna delete the addon folders and clear everything out and try reinstalling it now.

**Comment by Felys1998** [comment]
will also try with a completely clean plugin slate.

**Comment by Felys1998** [comment]
completely clean of all plugins except penumbra and materialui and the problem is not there. going to try putting mods back on, then reinstall addons to see if the problem resurfaces.

**Comment by Felys1998** [comment]
put all my installed addons back and the textures are still fine. something must've gotten screwed up and remained cached even through the integrity check. I'm very confused, but it seems my problem is resolved??

**Comment by skotlex** [comment]
I'm glad if the problem has been solved. 😅
