### ISSUE TITLE
6.1 Issues

### ISSUE THREAD

**Issue by ibigfire** [skotlex/ffxiv-material-ui#305]
I'm sure you're aware it needs an update for some of the new 6.1 issues, but in case it helps just wanted to point out some errors I found.  The new Adventurer Plates have some buttons missing and the new crafting interface while crafting has an invisible bar for the quality increase.

Thanks very much for the UI theme!

**Comment by skotlex** [comment]
I planning to proceed with the preliminary distribution within this week. Thank you for your opinion 😄

**Comment by ibigfire** [comment]
Sounds great, thank you for all you do!  ^_^

**Comment by nihilistzsche** [comment]
The buttons are missing but you can still mouse over them to see a tooltip and they function when you click on where they should be, so nothing is functionally breaking there.
