### ISSUE TITLE
PvP Profile Issues

### ISSUE THREAD

**Issue by Jake-G8** [skotlex/ffxiv-material-ui#307]
There seems to be some kind of glitch caused by the mod. It makes the PvP Experience bars glitchy and broken. Also, not sure if it's intentional, but the mod also doesn't apply the dark reskin to the PvP profile or the character sheet when in the Wolves Den. 

Open the PvP profile and character sheet in Wolves Den (La Noscea) to reproduce.
![Screenshot (137)](https://user-images.githubusercontent.com/99757239/163698524-00f7711f-a7fc-46ee-8f8f-110270dbe8cf.png)

**Comment by skotlex** [comment]
Is it correct to use 6.1.0 primary version?

**Comment by Jake-G8** [comment]
I reinstalled the preliminary and the bars no longer look glitched. However, it's still not dark mode. Not sure if that's intended.

**Comment by Mokura** [comment]
If I remember from earlier discussions, PVP profile stuff uses light theme textures, and would have text display issues (as you can't change text color without plugins, afaik)

**Comment by Jake-G8** [comment]
I see. Well so far so good. Thanks for your hard work!
