### ISSUE TITLE
Missing icon at the MB (6.1 preliminary)

### ISSUE THREAD

**Issue by Scylune** [skotlex/ffxiv-material-ui#308]
Hi, just to point it in case you missed it. I don't think it's the case, but, well.. ^^

![mb](https://user-images.githubusercontent.com/63762626/164909267-772919dc-5591-4895-ac00-5dc053236f69.jpg)

Ty^^

**Comment by skotlex** [comment]
It will be fix in the complete version
https://github.com/skotlex/ffxiv-material-ui/issues/306
