### ISSUE TITLE
Quality bar (crafting) not updated to materialUI, filling border radius is present, border is ok but not the filling

### ISSUE THREAD

**Issue by Kanubiz** [skotlex/ffxiv-material-ui#309]
**Screenshots**
![image](https://user-images.githubusercontent.com/13062045/164949387-c4bf2561-5c04-4b4a-a9d3-3dbc1fbb2538.png)

**Describe the image**
A clear and Please explain how the image looks wrong.
This is present in all progress colors, as you can see from the progress one, its looking as expected but not the quality one

**To Reproduce**
Please explain how you can access the menu:
1. Craft

**Comment by skotlex** [comment]
![화면 캡처 2022-05-01 011811](https://user-images.githubusercontent.com/31692408/166113654-bf573992-f2df-490a-a099-e7b9937d69d6.png)
