### ISSUE TITLE
Gear Set images for hotbars

### ISSUE THREAD

**Issue by Zandermoonshade** [skotlex/ffxiv-material-ui#311]
![image](https://user-images.githubusercontent.com/69808612/165419986-195535bd-55b5-45bc-8e2a-206c61b2ab31.png)

As a slight replication to issue #271 where certain images of the class models are not shown properly - One to add to it - Hotbar icons.

Confirmed that other icons have been fixed that were the case in issue #271, but the hotbar icons are still set to normal icons unfortunately.
![image](https://user-images.githubusercontent.com/69808612/165420024-ef08a5fc-2324-417d-8e55-096aa7e06b32.png)
![image](https://user-images.githubusercontent.com/69808612/165420044-b338f083-10a7-4ba6-88e6-ebb696328a86.png)

Most recent update I have is from 4/12/22 at 6:00pm (when I downloaded it)-
Material 4K-UI v6.0.2-167-6-0-2-1642338187.

**Comment by skotlex** [comment]
https://github.com/skotlex/ffxiv-material-ui/releases/tag/6.1.0
