### ISSUE TITLE
Black style

### ISSUE THREAD

**Issue by dotAugis** [skotlex/ffxiv-material-ui#312]
First of all, thank you for your amazing work!

I would like to suggest the expansion of black style content (as seen in contents job icons). Would love to see more of these black + gold styled icons used for the interface, especially for party UI and maybe in character classes/jobs tab.

Thank you!

**Comment by skotlex** [comment]
Except for pvp, I understand that most of them are changed styles. Can you give me an example of what you're saying with a screenshot?

**Comment by dotAugis** [comment]
> Except for pvp, I understand that most of them are changed styles. Can you give me an example of what you're saying with a screenshot?

Of course!
I simply love the dark gray + gold icons you've made, and so I would love to see them added into more content, primarily would like to see an option choice for the party UI (first screenshot example)!

![Party example](https://user-images.githubusercontent.com/85735640/168304359-0dccd29a-afaa-4fd2-b826-f9308865d093.jpg)
![DoWDoM example](https://user-images.githubusercontent.com/85735640/168304368-a74b1508-6d21-4f22-b789-7e11fe989a1e.jpg)
.
