### ISSUE TITLE
Chat Dialogue Box Options?

### ISSUE THREAD

**Issue by KazLynx** [skotlex/ffxiv-material-ui#315]
I'm not sure if this is the best way to ask. Is there any plans for allowing us to choose different dialogue boxes or just use the default one? I think the dialogue box looks great with the mod when at 100% scale. I play on my 4K TV and I have to scale mine to around 140% to be able to read the text comfortably.

I think the dialogue box included in the mod is a bit too big at 140% personally. Perhaps a different style would look better? Or even some transparency features for the box?

I'd be fine even with the option to just change the dialogue box color or restore the look of it to the default dialogue box. 

To clarify. I'm specifically talking about the dialogue boxes you read in quests, or main scenario, or when a retainer comes back and has some dialogue before showing you what they got on a venture, etc. I'm not talking about the/say /tell /party etc. chat box.

Thank you for the amazing mod!

**Comment by skotlex** [comment]
Let's add an option to display as the default dialog box at the next patch.
