### ISSUE TITLE
Add Optional Waymark Image Override

### ISSUE THREAD

**Issue by Reag** [skotlex/ffxiv-material-ui#316]
As someone who is dyslexic, I have serious issues reading and understanding the waymark icons in vanilla XIV. Currently, I apply a textools update with some custom sprites every patch to allow me to raid effectively. Would it be possible for some simple sprite overrides to be an optional parameter as part of the UI pack? 

Example:
![image](https://user-images.githubusercontent.com/546108/179349271-cc81b65b-771c-47bd-bb53-b5741943c632.png)

**Comment by skotlex** [comment]
Not exactly, but I remember seeing something similar in Penumbra's option. You need to check it out

**Comment by MajorSquiggles** [comment]
Where do you get those waymarks? They look great!

**Comment by rsigim** [comment]
> Where do you get those waymarks? They look great!
[Better Waymarks](https://www.xivmodarchive.com/modid/40363)
You can load via Penumbra or TexTools
