### ISSUE TITLE
Materia UI not Working Even Though other TextTool Mods are Working.

### ISSUE THREAD

**Issue by Kylletd** [skotlex/ffxiv-material-ui#318]
**Screenshots**
![2022-08-11_11-43-52-299_Neneko_Happy Days  Gameplay](https://user-images.githubusercontent.com/111074113/184174274-47bae789-87b3-471f-895b-6b2134f267e8.png)
I have the Material UI downloaded but the UI has not been working. All my other TextTool mods have been working. This occurred after I had to delete and reinstall my FFXIV local files as the game would crash when I loaded in my alt. The alt issue is fixed but the Materia UI has not functioned since.

**Comment by skotlex** [comment]
Please check your settings

https://github.com/skotlex/ffxiv-material-ui/blob/master/INSTALL-GUIDE.md#textools
https://github.com/skotlex/ffxiv-material-ui/blob/master/INSTALL-GUIDE.md#in-game-settings
