### ISSUE TITLE
Keep getting C0000005problem for the UI mod 

### ISSUE THREAD

**Issue by Necroker** [skotlex/ffxiv-material-ui#321]
Do you know what is the main cause of it? thank you
![2131231231](https://user-images.githubusercontent.com/111634182/185737400-d38ea83c-7cff-4708-be73-b9caf7716cfd.png)

**Comment by Necroker** [comment]
same problem with any other UI MOD. I don't know why

**Comment by Necroker** [comment]
![2](https://user-images.githubusercontent.com/111634182/185738215-116524fd-8dd0-497d-8bb6-cac9a08e84b0.png)

**Comment by skotlex** [comment]
Please check the goat's community for questions about Dalamud.
