### ISSUE TITLE
error when starting game

### ISSUE THREAD

**Issue by DanielWhitman** [skotlex/ffxiv-material-ui#322]
i stopped playing ff14 for a while after 6.1, just started again, deletes all mods, tried to reinstall them (only the main file) and i got errors right before character selection screen. so i was wandering if this is normal due to the new 6.2 patch or did i do something wrong? im using texttolls only, made backup files and started over, all mods were gone from texttools besides the new installed 6.1.1 main file.

i hope someone can help me out, thanks in advance :)

**Comment by skotlex** [comment]
Compare the status of when all modes were removed and executed, and when the game was played after adding the modes one by one. If the mode is a problem, please apply a new version of the mode, not the one you backed up.
