### ISSUE TITLE
Patch 6.2 Support

### ISSUE THREAD

**Issue by skotlex** [skotlex/ffxiv-material-ui#323]
## 🔨 New & Modify Textures
- [x] 061847 (NEW)
- [x] Character
- [x] GatheringCollectable
- [x] HowTo (DXT5 > 4.4.4.4 RGB)
- [x] Inventory
- [x] LFG2 (DXT5 > 8.8.8.8 ARGB)
- [x] LongPressButtonA (DXT5 > 8.8.8.8 ARGB)
- [x] TextInputA (8.8.8.8 > 4.4.4.4 RGB)
- [x] ToggleButton
- [x] TripleTriadApplication2 (8.8.8.8 > 4.4.4.4 RGB)

## 📦 User's Suggestion
- [x] https://github.com/skotlex/ffxiv-material-ui/issues/312
- [x] https://github.com/skotlex/ffxiv-material-ui/issues/315

**Comment by Sevii77** [comment]
`ui/icon/061000/061847_hr1.tex` Found in `/challengelog` > Other. Requires Island Sanctuary to be unlocked.
