### ISSUE TITLE
Duty Support does not match selected option for party list job texture

### ISSUE THREAD

**Issue by AmenneHolelane** [skotlex/ffxiv-material-ui#326]
**Screenshots**
when you queue into a duty with NPCs, the "party list icon" does not apply to them. [Image](https://media.discordapp.net/attachments/838094509128286218/1020667178468528218/unknown.png). the background itself still has the gold rimmed stuff on it.

**Describe the image**
The Job icon itself does change but the background, for lack of a better term, does not. the icon that Urianger uses in that picture is `ui/icon/062000/062572_hr1.tex`. i believe the icons are 062571-062574

**To Reproduce**
Please explain how you can access the menu:
1. Go to Duty > duty support
2. Pick any dungeon, pick your party, and enter
3. look at party screen

**Comment by AmenneHolelane** [comment]
as the duty support pulls their class/job icons from `ui/icon/062000/0620**_hr1`, and the player icons in the party list are from `ui/icon/062000/0621**_hr1` it probably isn't possible to make them match exactly especially if you have different `Party Job Icon` and `Contents job icon` settings. probably a huge hassle to actually fix, maybe remove the gold border and leave it at that? IDK

**Comment by skotlex** [comment]
Because it uses 'contents job icons', it appears like this in the default option, but I don't think there will be a big problem.

![화면 캡처 2023-01-24 220113](https://user-images.githubusercontent.com/31692408/214298869-d7edd864-6bc6-4c1e-9205-ba77f002198f.png)
