### ISSUE TITLE
6.25 Update

### ISSUE THREAD

**Issue by Jaytwo77** [skotlex/ffxiv-material-ui#328]
Since 6.25 i have not been able to get the mod to work...

**Comment by crazyace** [comment]
Have you opened something like FFXIV TexTools to have the skin refreshed?

**Comment by Jaytwo77** [comment]
Yes i have.  When it didnt load i did a fresh install.  Just tried it again and with fresh install and no dice

**Comment by Aratsei** [comment]
Having this same issue. Completely backed up mod pack, uninstalled everything, updated to 6.25, reinstalled from back up, failed. Removed MaterialUI manualy, reinstalled, still nothing.

**Comment by crazyace** [comment]
Are you using 4k or HD package?

**Comment by Aratsei** [comment]
> Are you using 4k or HD package?

...I am now annoyed, angered, thankfull, confused, and relieved. The game defaulted my HUD option for me when it updated and i never noticed

**Comment by Jaytwo77** [comment]
Yes issue solved.  Changed the UI graphics to 4k and everything is working like a champ.  Thanks for the help!
