### ISSUE TITLE
Deep Dungeon and Achievement panels seem to be broken

### ISSUE THREAD

**Issue by brunwe** [skotlex/ffxiv-material-ui#330]
Hello. First off, thank you for your work. It has made my gameplay experience much more enjoyable/aesthetically pleasing. I have been using material UI for the past few months, and it's been relatively bug-free overall. However, after watching some old guide videos and searching up and down for the past few days, I have noticed that a few different panels have reverted to their original states- specifically the entirety of the deep dungeon ui as well as the achievement panel. I've been playing a lot of deep dungeon recently, and the improvement that you made to the panels (increasing visibility) looks substantial. Is there any chance you might fix this in a future release? I use TexTools and downloaded the past 2 or 3 releases to see if I was just missing a file, but none of those seemed to be able to fix the issue. Thanks.

**Comment by skotlex** [comment]
First of all, I don't have a history of modifying Deep Dungeon. You seem to be mistaken for something else mods. The Achievement panels has not been modified since the new UI was applied in SQEX. Because I didn't have the confidence to make it better than that. Here's the current situation.

**Comment by brunwe** [comment]
I see... I might have to look into modifying it myself, since it looks like it would be a nice QoL change. It's understandable if you don't want to try and deal with the achievement panel. I don't know exactly what goes into the process of designing this kind of mod so it's not my place to request you do anything you don't want to. Thank you for responding to my ticket.
