### ISSUE TITLE
Accent Will Not Change Color

### ISSUE THREAD

**Issue by SomebodyAnxious** [skotlex/ffxiv-material-ui#331]
I've tried using both Penumbra and TexTools (not at the same time) to install Material UI. After I installed the plugin, it just never changes the accent out of purple after I hit apply. I've tried restarting the game, but nothing changes.

![image](https://user-images.githubusercontent.com/101953244/209684549-e1a0ec68-0372-4266-a2c7-9d7a95766733.png)

**Comment by skotlex** [comment]
I can't support for Penumbra. Please use the #help-penumbra channel of our discord community.
