### ISSUE TITLE
Gunbreaker and Dancer have different glow

### ISSUE THREAD

**Issue by Nellieh** [skotlex/ffxiv-material-ui#45]
So .. as title says, my gunbreaker and dancer icons have different glow compared to rest making it annoy my eyes really badly :(
![image](https://user-images.githubusercontent.com/39604109/61287899-3b31e680-a7c6-11e9-8f03-479c7c94fd24.png)

**Comment by skotlex** [comment]
@Nellieh I certainly went through the same process, but as you said, there is a slight difference. Most people may not have noticed, but I'll try a little more for you. But I don't think it's going to be perfect, so I hope you understand :(

**Comment by skotlex** [comment]
@Nellieh I tried to make it look as natural as possible. For now, I'd appreciate it if you'd be this satisfied. If you think this is a problem, please don't hesitate to tell me. It's not right now, but I'll make improvements in the future.
## JOB ICON GLOW: GNB
![changelog_01](https://user-images.githubusercontent.com/31692408/61573542-819b8400-aaeb-11e9-995c-2ac22d851352.png)

## JOB ICON GLOW: DNC
![changelog_02](https://user-images.githubusercontent.com/31692408/61573561-ef47b000-aaeb-11e9-96e2-6b535b67a466.png)

**Comment by Nellieh** [comment]
Ye,  this looks good in my eyes, just i saw in another post here that you want to change transparency on windows not active, please make this optional
