### ISSUE TITLE
[Request] Colour the limit break bar similar to original

### ISSUE THREAD

**Issue by insarius** [skotlex/ffxiv-material-ui#46]
The dark purple colour on the LB bar is easy to miss; is it possible to make it brighter/similar to the original color.

**Comment by skotlex** [comment]
Let's think about it. Thank you for your opinion!

**Comment by skotlex** [comment]
I've made it up, but first I'll apply it as it is and watch it.

![changelog_09](https://user-images.githubusercontent.com/31692408/61585634-b5ce7d80-ab9b-11e9-940a-a80a89772523.png)
