### ISSUE TITLE
Background on jobs icon in the desynthesis menu

### ISSUE THREAD

**Issue by Vayhyr** [skotlex/ffxiv-material-ui#47]
**Screenshots**
![Screenshot 1](https://i.imgur.com/0a1VS1o.png)

**Describe the image**
Jobs icons in the desynthesis menu have a black background under it.

**To Reproduce**
Character > Classes/Jobs > DoH/DoL > Click on any DoH

**Comment by skotlex** [comment]
@Vayhyr I think it will be difficult to remove because it will share texture with other menus.
I'll test and answer again what will happen to the existing UI when I remove that.

**Comment by skotlex** [comment]
@Vayhyr I've tested it, and this is what happens.
![주석 2019-07-20 163757](https://user-images.githubusercontent.com/31692408/61575938-e9fb5d00-ab0d-11e9-9a03-b04f8f9c3544.png)

But if you change this, the following texture will also be affected.
:before
![주석 2019-07-20 163408](https://user-images.githubusercontent.com/31692408/61575946-039ca480-ab0e-11e9-8e58-43551e4b3775.png)

:after
![주석 2019-07-20 163736](https://user-images.githubusercontent.com/31692408/61575949-05fefe80-ab0e-11e9-81bb-3728dacaabd3.png)

In addition, most job icon backgrounds are deleted. I am considering whether to add this to the official version or offer it as an option. What's your idea?

**Comment by Vayhyr** [comment]
Yeah, it's better that it stays as an option, some people may not like it.
