### ISSUE TITLE
Iteration Plan for August, 2019 (Black-UI v2.0.0)

### ISSUE THREAD

**Issue by skotlex** [skotlex/ffxiv-material-ui#48]
![icon_24](https://user-images.githubusercontent.com/31692408/61606369-eb9b6100-ac84-11e9-98dc-0f39b62e03b6.gif)
Announcement of the plan for August, 2019.

## <s>Help wanted</s>
<s>I'm not perfect but I've finished making discord-UI and I have to make black-UI, but I have a problem here. Personally, the existing black-UI is so close to the original color that it tries to use a more natural color than the black. 

So I will prepare some layout samples sometime in August and I would like to hear your feedback. If that's the time, I hope to hear your opinion. Thank you.</s>

## Plan 
_※ May change depending on the circumstances_
- [x] **<s>August 11, 2019**: Upload sample layouts</s>
- [x] **<s>August 11-up to 18, 2019**: Gathering opinions</s>
- [x] **August 11, 2019**: Begin development _(Start as soon as gathering opinion is closed)_
- [x] **August 22, 2019**: Endgame done
- [x] **August 24, 2019**: Mod distribution

## Plan item
- [x] Development Alphabet:A to Z
- [x] Making options
- [x] Testing in-game
- [x] Modify bug **(By August 31, 2019)**

**Comment by Chrisnetika** [comment]
Personally, i love the black ui, thinking of going back to it sans shb icon :/

**Comment by alopez7589** [comment]
I LOVE the Black layout. I am looking forward to your iteration.

**Comment by skotlex** [comment]
Hello friends. I've previously uploaded various layouts and listened to your opinions, but I've decided to quit. After testing various colors, I found nothing better than what I used to offer. Please take the following into consideration for sample layout. 
<i>PS.
I hope there will be no misunderstanding since the design is not decided only by referring only to the color.</i>

Unlike discord-ui, black-ui will have a rectangular layout. Thank you

![2-1](https://user-images.githubusercontent.com/31692408/62830324-017ac100-bc48-11e9-9f11-9285dc5a3ed1.png)
![1-1](https://user-images.githubusercontent.com/31692408/62830323-fe7fd080-bc47-11e9-8765-478d33e69633.png)
![주석 2019-08-11 102359](https://user-images.githubusercontent.com/31692408/62830325-02abee00-bc48-11e9-8f48-55b22a4a820f.png)

**Comment by Chrisnetika** [comment]
smexyyy

**Comment by Arokhaerr** [comment]
Would it be possible to add back the square HP, Mana and Limitbreak Bars as an optional? =)

**Comment by skotlex** [comment]
@Arokhaerr If you're talking about discord ui, I can make it an option. If you want to.

**Comment by Arokhaerr** [comment]
That would be awesome, thank you ^^

**Comment by skotlex** [comment]
It's part of the screen that I'm currently working on. 
I'll do my best to make a formal release in September.

![주석 2019-08-18 134321](https://user-images.githubusercontent.com/31692408/63220243-51183a00-c1be-11e9-88cf-3b1ff6a02342.png)
![주석 2019-08-18 133916](https://user-images.githubusercontent.com/31692408/63220245-52e1fd80-c1be-11e9-964e-595824e31dd1.png)
![주석 2019-08-18 133934](https://user-images.githubusercontent.com/31692408/63220247-54132a80-c1be-11e9-9e83-136aafe67e2d.png)
![주석 2019-08-18 133954](https://user-images.githubusercontent.com/31692408/63220249-55dcee00-c1be-11e9-8c1a-41375a0398ea.png)

**Comment by skotlex** [comment]
Deployment completed. If you know the bug, please let me know.

**Comment by Arokhaerr** [comment]
Not a Bug, but the Square Minimap Optional is not in common but in Discord. Is that intended? =)

**Comment by skotlex** [comment]
Because black version already applies square minimap, it is intended.

**Comment by skotlex** [comment]
But from what you said, I think should change that. I'll look at it positively and change it. Thank you

**Comment by exeedz** [comment]
Few ideas for the black UI (Optional):
1. Active/Selected window marker (a small triangle on the bottom left like the tab model should be ok too)
2. Circle Minimap (Old theme minimap)
3. Different color for melee DPS (Orange), physical range DPS (Yellow), caster DPS (Purple)?

**Comment by skotlex** [comment]
1. I don't think it's possible to structure what you've heard as an example. Is it not enough that you already have an option?
2. If it's in the discord version, it's ok.
3. That sounds interesting. I'll make it.

**Comment by exeedz** [comment]
1. the triangle is just example, it can be anything. The idea is to have the active window different from non-active ones.

**Comment by skotlex** [comment]
![preview](https://user-images.githubusercontent.com/31692408/63665208-53554680-c805-11e9-9497-7dee9d084cd7.png)
If it's just for distinction, already offering it as an option. Do you know about this?

**Comment by exeedz** [comment]
oh! forgive my ignorance. i only see the release section (have not applied them yet), and thought it don't have it

**Comment by FXStrato** [comment]
Hey there! Amazing work on the black version, loving every bit of it. Just one small request, would it be possible to have a black version but with the regular blue highlighting instead of the red? Big fan of black/blue, with red being more meh to me.

**Comment by skotlex** [comment]
Hello. In fact, I thought a lot about whether to apply blue or red, but considering the difference between discord-ui, I finally chose red. And I'm careful because it takes a lot of time to change one color. I will consider these inquiries if they are constantly being asked, but I have no intention of changing them at this time. I'm sorry.

**Comment by FXStrato** [comment]
Gotcha, and no worries! Thanks for explaining the reasoning behind it

**Comment by Siiper** [comment]
Is this possible to have an optional to change dialogue box color from bright white to grey-ish or normal color? the dialogue box color at the moment is kinda ways too bright for a black ui skin. 

and a little bug on Minimap, if set it to 60% size the black border on top, will be missing for a reason. 
![vcb1](https://user-images.githubusercontent.com/40589884/63940430-a3e1d380-ca93-11e9-838e-10e5d3ae2192.png)

**Comment by skotlex** [comment]
![주석 2019-08-29 221731](https://user-images.githubusercontent.com/31692408/63943554-dd720900-caaa-11e9-9dc3-7f4a667b004f.png)
If the dialog you are talking about is this, it is difficult to darken it further. Because the letters are gray. And the normal color is brighter yellow than this, but I don't know what that means.

Because the mini-map is a square version of the existing circular image, the inconvenience of reducing the size is very difficult for me to correct. I'm sorry.

**Comment by skotlex** [comment]
@Siiper If you want to modify it, I have to remove the minimap's border. Do you want it?

**Comment by Siiper** [comment]
> 
> 
> @Siiper If you want to modify it, I have to remove the minimap's border. Do you want it?

it's ok, i think just have to resize it to 80% to be able to see the border again.

also about dialog box, i mean this one when you talking with NPC
![vcbd](https://user-images.githubusercontent.com/40589884/63944575-fa531000-ca9b-11e9-92c7-777e200cf077.png)

But yeah overall you did a good job here ʕ•̀ω•́ʔ✧

**Comment by skotlex** [comment]
Its color is adjustable. I'll take the samples during the weekend and answer them again.

**Comment by skotlex** [comment]
@exeedz I've changed the card color of Astrologian. How about this?
![주석 2019-08-30 211856](https://user-images.githubusercontent.com/31692408/64020194-ed055680-cb6b-11e9-839e-5ef96a29b757.png)

**Comment by skotlex** [comment]
@Siiper How about this?
![주석 2019-08-30 213802](https://user-images.githubusercontent.com/31692408/64021272-85043f80-cb6e-11e9-9d52-7c9f143c58f2.png)

**Comment by exeedz** [comment]
hmm, i prefer the physical range and magical range role color also different. if you're going to use AST card scheme, can use dark purple and light purple.

also i always identify blue as some kind of defensive, so using it for melee dps is seems unfit. i like red for melee, and yellow/orange for physical range, purple for caster if using 3 different color, or red for melee, mixed of red+dominant purple for range, purple for caster if going on AST card scheme.

while im at it, i notice some bleeding issue on macro icons, but only on certain scale (i used 90% scale for my macro icon window, and some of the icon has bleeding, and also some bleeding and some good in same icon) but overall they are good for 100% scale so ill just need to get used to it.

**Comment by skotlex** [comment]
@exeedz I've adapted the card concept of Astrologian and I've been to Dungeon, and it's definitely a strange feeling. So I've changed the color like you said, and I think it's natural. I will stop the card concept of Astrologian. Just tell me how you feel about the screenshot I uploaded.
![주석 2019-08-30 222956](https://user-images.githubusercontent.com/31692408/64024794-2c38a500-cb76-11e9-9153-f8490001772b.png)

**Comment by exeedz** [comment]
yes! i like this one better

**Comment by Siiper** [comment]
> 
> 
> @Siiper How about this? If the original is better, tell me.
> ![주석 2019-08-30 213802](https://user-images.githubusercontent.com/31692408/64021272-85043f80-cb6e-11e9-9d52-7c9f143c58f2.png)

Yeah! this one feels a lot better than the original one.
