### ISSUE TITLE
Installing 2.1.6 caused texui 2.0.7 to blow up.

### ISSUE THREAD

**Issue by ajhix36** [skotlex/ffxiv-material-ui#52]
Installing the new version caused a bug window to pop up and then crash texui, and now anytime i try to do anything in texui it completely crashes.

**Comment by skotlex** [comment]
@ajhix36 Can I see the screenshot image of the problem?

**Comment by ajhix36** [comment]
Uhh, cant reproduce the import one anymore, but now the message says


Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: n. Path 'Mods[17871].modPack.name', line 339673, position 26.   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)   at Newtonsoft.Json.JsonTextReader.Read()   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)   at xivModdingFramework.Mods.Modding.<>c__DisplayClass7_0.<TryGetModEntry>b__0()   at System.Threading.Tasks.Task`1.InnerInvoke()   at System.Threading.Tasks.Task.Execute()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at xivModdingFramework.Mods.Modding.<IsModEnabled>d__8.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at FFXIV_TexTools.Views.SimpleModPackImporter.<>c__DisplayClass17_0.<<ImportSimpleModPack>b__0>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at FFXIV_TexTools.Views.SimpleModPackImporter.<ImportSimpleModPack>d__17.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at FFXIV_TexTools.Views.SimpleModPackImporter.<Initialize>d__16.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
--

**Comment by skotlex** [comment]
Is it right to use TexTools 2.0.7? And I wonder if this problem has occurred in v2.1.2.

**Comment by ajhix36** [comment]
oh i meant TexTools 2.0.7

**Comment by ajhix36** [comment]
I think its because I had HD Icon texture pack installed which installed hundreds of thousands of entries into my json, and something got corrupted.

**Comment by skotlex** [comment]
I only know about HDicon Mod. But I don't know if it's a conflict between the Mods. Because I don't use HDicon Mod, and I don't know how it was developed. It is made up of tens of thousands of textures and it will take too much time to find the cause in it. I'm sorry I couldn't help you solve the problem.

**Comment by ajhix36** [comment]
I don't think it's your mod. Just a coincidence. I think installing the HD icon mod corrupted my entries and then when I installed yours it was just wrong place wrong time.
