### ISSUE TITLE
Cast Bar

### ISSUE THREAD

**Issue by AgnarUrthadar** [skotlex/ffxiv-material-ui#53]
Hello, I noticed that in UI mod the cast bar is red, same colour as interruptible one, only difference is it "breathes" yellow, would it be possible to either change the color to original or make breathing effect other color so it's easier to notice?

**Comment by skotlex** [comment]
I ask you questions based on the original.
```
* yellow cast bar: can't interrupt
* red cast bar: can interrupt
```
is that right? If this is true, I have made a very big mistake.

First of all, **disable the entry "PartyList_GaugeCast"** to get this back to original. And I'm going to change this from the next version of the patch to the original, or to a different color.

I'm sorry for the inconvenience I've caused you.

**Comment by AgnarUrthadar** [comment]
[This is normal cast bar.](https://i.imgur.com/9BMFR8B.png) 
[This is new one that you can interrupt.](https://img.finalfantasyxiv.com/t/330f2b280067d69d85b17831c66712a499e97484_56.png?1563272316) 

As I play a tank I often interrupt and I have hard time knowing which one it is with Material UI, I may be the only person with this problem though. Sorry for being a pain about it orz

**Comment by skotlex** [comment]
It's not your fault and I should have been more considerate.
What do you think of this after adjusting the color? I'd like you to be honest with me.
![2](https://user-images.githubusercontent.com/31692408/62011274-259ec280-b1b1-11e9-9fcc-a1d8dd3a770c.gif)

**Comment by skotlex** [comment]
Well, I think the original is better compared to the original. I think that's probably what you see. Please ignore this question. I'll have to figure out if there are any other good colors in the future. Thank you your opinion

**Comment by AgnarUrthadar** [comment]
That colour would be perfect for uninteruptible one.

**Comment by skotlex** [comment]
I think it's OK in terms of readability, but I don't think it's good in terms of the combination of colors. For example, the combination is not good for these parts because the letter is yellow and the background is gray. What do you think of this part?

**Comment by AgnarUrthadar** [comment]
Seems fine for me, although some would say it'd be better to make the outer line of cast bar golden instead of grey?

**Comment by skotlex** [comment]
If you want use this mod, I can offer it as a separate option. Would you like that?

**Comment by AgnarUrthadar** [comment]
Sure, thanks :)

**Comment by skotlex** [comment]
You can apply this. I'll test this a little bit more and decide whether to offer it as an option or put it in the official version.
[gaugecast_gray_color.zip](https://github.com/skotlex/ffxiv-material-ui/files/3439727/gaugecast_gray_color.zip)
