### ISSUE TITLE
The Character (PVP) Tab is White Still in dark mode.

### ISSUE THREAD

**Issue by ajhix36** [skotlex/ffxiv-material-ui#54]
Can you please add a replacement for the Character (PVP) sheet? Go to Wolve's Den Pier and open your Character sheet to see what I mean.

**Comment by ajhix36** [comment]
Can you do the PVP Profile as well too please?

**Comment by skotlex** [comment]
I can't control the ui color of the pvp. Because pvp is fixed in the opposite color of other ordinary ui.
