### ISSUE TITLE
Limit break purple UI

### ISSUE THREAD

**Issue by Kalastarfoulabobzermishos** [skotlex/ffxiv-material-ui#55]
Hey,

Could you add the former limit break bars UI (the purple one) in the option package?

**Comment by skotlex** [comment]
checked it. I will be included in the new patch this weekend.

**Comment by skotlex** [comment]
![changelog_option_01](https://user-images.githubusercontent.com/31692408/62824414-3a7b4d00-bbd8-11e9-9508-9007ee7ecd09.png)
I'll include it in the distribution of the official version.
