### ISSUE TITLE
Distinguished between active and inactive window

### ISSUE THREAD

**Issue by exeedz** [skotlex/ffxiv-material-ui#60]
Is it possible to make the differentiation more distinguished between active window and inactive ones? At the moment they are very look alike/same, i can use the optional transparent window for the inactive one but prefer a more distinguished looks for active or inactive window to make them more differentiated. Like darker for active and lighter for inactive (like the current tab features).

**Comment by skotlex** [comment]
If transparency is not sufficient for the disabled window, then what remains is to apply the border to the activated window. As if there is a yellow border in the base UI. What do you think about this?

**Comment by exeedz** [comment]
yes, that could also work.

**Comment by skotlex** [comment]
I'll make a sample tomorrow (KST).

**Comment by skotlex** [comment]
How do you feel about this image?
![주석 2019-08-15 110249](https://user-images.githubusercontent.com/31692408/63067983-5f5f1f80-bf4c-11e9-958d-abd22b626a74.png)

**Comment by exeedz** [comment]
ahh yes, much better! also it fit the theme

**Comment by skotlex** [comment]
I'll distribute it within the weekend. Thank you :)

**Comment by skotlex** [comment]
Sorry I'm late. Please download this.
[selected-window-border.zip](https://github.com/skotlex/ffxiv-material-ui/files/3512919/selected-window-border.zip)

**Comment by exeedz** [comment]
lovely! thank you very much!
