### ISSUE TITLE
color cast bar

### ISSUE THREAD

**Issue by Oxi-onGit** [skotlex/ffxiv-material-ui#61]
Hello,
would it be possible to add a different color area on the end of the cast bar?
Because it will allow you to move before the end of the cast without breaking the skill without grid.

**Comment by skotlex** [comment]
I'll think about it.

**Comment by skotlex** [comment]
If I separate color area at the end of the cast bar, it applies not only to the cast bar but also to the MP/CP/GP/Job simple gauge bar. I don't recommend this to hurt the beauty of other UI. What do you think of this?

**Comment by Oxi-onGit** [comment]
I understand, we can change the color of the cast bar when it reaches the right percentage. where then use the new system that is used for attacks ( the blinking)

**Comment by skotlex** [comment]
I don't know what your answer is for. For your information, it is not possible to have a blink effect.

**Comment by Oxi-onGit** [comment]
Otherwise, modify the frame and simply add a line?

**Comment by skotlex** [comment]
It is possible but I can't think of how to express it. Could you make a sample for me, at least roughly?

**Comment by Oxi-onGit** [comment]
![image](https://user-images.githubusercontent.com/14092883/63112704-2b5a1d80-bf91-11e9-8c45-dc254cab1a24.png)
That is one example. There are 2 bars because if it's a short cast you can move earlier, if it's a long cast it's a little longer

**Comment by skotlex** [comment]
Thank you for the detailed example. First of all, I will make my own example and upload some samples on the weekend. However, as I said before, touching the cast bar will affect the MP/CP/GP/Job simple Gauge at the same time, so that area must be inconvenienced.

**Comment by skotlex** [comment]
But I have a question. Is the cast bar you are currently using the image below?
![제목 없음](https://user-images.githubusercontent.com/31692408/63134521-c04a2e80-c004-11e9-877c-0dcecf4da4e6.png)

**Comment by Oxi-onGit** [comment]
not the bars of the previous version but if you use it is bar ok for me

**Comment by skotlex** [comment]
It looks like the last bar I made in the 4.x version. That is not currently supported, so I will make it based on the texture above.

**Comment by Oxi-onGit** [comment]
Okay, thanks to you.

**Comment by skotlex** [comment]
First of all, I want to say I'm sorry first. I offered to hand you the samples by the end of the week, but I don't think I can keep them. I'm currently working on a black version of the material UI, and I think I need to focus on it this week. I'll try to handle your request as much as possible, but I'd like to ask you to excuse me for being late.

**Comment by Oxi-onGit** [comment]
no worries I am also looking forward to seeing the black ui and thank you for kindly processing our request

**Comment by skotlex** [comment]
I'm sorry it's too late. I made simple samples.
:grey
![주석 2019-08-24 022650](https://user-images.githubusercontent.com/31692408/63611423-d2d0f300-c616-11e9-8b4f-cdcd5957c219.png)
:red
![주석 2019-08-24 021908](https://user-images.githubusercontent.com/31692408/63611525-fdbb4700-c616-11e9-84ef-b86756a7201f.png)

And as I said before, there is a downside to this texture
![주석 2019-08-24 022723](https://user-images.githubusercontent.com/31692408/63611600-2fcca900-c617-11e9-8ceb-446f18b5df95.png)

Everything related to the gauge changes like this. I will not include this as a formal option for this reason. Please tell me if you are lacking, or if you like one of them.

**Comment by Oxi-onGit** [comment]
I prefer the grey mode, but it's a real shame it's everywhere... Is it possible to change the color to a certain percentage of the bar?

**Comment by skotlex** [comment]
I don't think it's meaningful because it affects all the gauges.

**Comment by Oxi-onGit** [comment]
I meant changing the color of the caste gauge to a certain percentage and not the background

**Comment by skotlex** [comment]
The color of cast bar is the same as the background. Just as the background in the image above affects all gauge bars, cast bar is the same. Changing one will affect the whole thing.

**Comment by Oxi-onGit** [comment]
I have a question how did you manage to change the color of the caste bars if changing one changes them all?
![image](https://user-images.githubusercontent.com/14092883/63650314-981ba780-c749-11e9-8a79-b2f568839126.png)

**Comment by skotlex** [comment]
![Untitled-1](https://user-images.githubusercontent.com/31692408/63651587-4434b100-c791-11e9-80d9-054a9408e2ed.jpg)
Above image is [cast bar color] and [bar background] texture (image / alpha map)

The process of determining the color of cast bar is as follows.
1. Each cast bar has its own color. / ex. hp(green), mp(pink), cp(purple), gp(blue)
2. Mix the colors specified in texture above / ex. red gradation
3. The color of each cast bar is output.

The image above is the result of a mixture of these colors. You may think I can determine cast bar each color, but it's not.
- hp(green+red gradation)
- mp(pink+red gradation)
- cp(purple+red gradation)
- gp(blue+red gradation)

That means I can only adjust which color I want to mix more from the basic color. It is impossible for me to change the basic color of the cast bar. That's why the gp is so dark.

**Comment by Oxi-onGit** [comment]
Ah okay, sorry to have wasted your time, I pence that my request is not viable, good day to you.

**Comment by skotlex** [comment]
I'm glad you understand what I'm saying. Have a good day.
