### ISSUE TITLE
White line appearing above MP bar

### ISSUE THREAD

**Issue by Vayhyr** [skotlex/ffxiv-material-ui#84]
**Screenshots**
Party list at 200%
![200% size](https://vayhyr.s-ul.eu/3B0hiEBr "Image 1 - 200%")
Party list at 110%
![110% size](https://vayhyr.s-ul.eu/4YXlcNNO "Image 2 - 110%")
Party list at 100%
![100% size](https://vayhyr.s-ul.eu/IQtv0OCb "Image 3 - 100%")

**Describe the image**
A fine white line appears above MP bar.

**To Reproduce**
1. Set "party list" element size to any value other than 60%, 80% or 100%.

**Additional context**
This problem doesn't seem to appear at 80%/60% (probably because it's too small).

**Comment by skotlex** [comment]
fixed it
![changelog_02](https://user-images.githubusercontent.com/31692408/63599764-377f5400-c5fd-11e9-9056-46d60e91593b.png)
