### ISSUE TITLE
White line on PLD simplified gauge

### ISSUE THREAD

**Issue by Vayhyr** [skotlex/ffxiv-material-ui#85]
**Screenshots**
![Image 1](https://vayhyr.s-ul.eu/5VQjL5ZQ)
![Image 2](https://vayhyr.s-ul.eu/JVb7gH7P)

**Describe the image**
A fine white line appears on the left side of the PLD gauge.

**To Reproduce**
1. Go on PLD
2. Set PLG gauge to simplified

**Additional context**
Similar to #84

**Comment by skotlex** [comment]
Unlike #84, I can't see the white line in the screen shot you posted this time. I need a little more detail.

**Comment by exeedz** [comment]
the horizontal white line is very thin (like 1px wide), notice-able at 200% oath gauge 1080p resolution (can be overlooked due to its thinness)

**Comment by skotlex** [comment]
Oh, I checked. That's been in that place. Thank you

**Comment by skotlex** [comment]
This is actually an FF14 official team's mistake, but the error has been corrected.

![changelog_01](https://user-images.githubusercontent.com/31692408/63598424-81b30600-c5fa-11e9-82cb-d8e5de84b801.png)
