### ISSUE TITLE
Small issue on Aetheryte Earring.

### ISSUE THREAD

**Issue by jofist** [skotlex/ffxiv-material-ui#87]
Aetheryte Earrings not properly cut on BLACK UI.
![earrings](https://user-images.githubusercontent.com/28004887/63690536-4fb0c800-c7e3-11e9-9295-8d644dbe4f6b.PNG)
Same does not apply to BLUE quality earrings.
![Capture](https://user-images.githubusercontent.com/28004887/63690648-9ef6f880-c7e3-11e9-992e-1cf677b78f2b.PNG)
Neither it applies to WHITE quality earrings, only Aetheryte Earrings as far as I know.
![Capture2](https://user-images.githubusercontent.com/28004887/63690727-cc43a680-c7e3-11e9-8a1b-a419d02243a5.PNG)

**Comment by skotlex** [comment]
Thank you for reporting.

**Comment by jofist** [comment]
It doesn't apply to unequipped aetheryte earrings.
![Untitled](https://user-images.githubusercontent.com/28004887/63691292-301a9f00-c7e5-11e9-93ff-56dea731e61a.png)

**Comment by skotlex** [comment]
I'll close the issue when it's over.

**Comment by jofist** [comment]
Excited to see a v2.0, thank you for the mod.

**Comment by skotlex** [comment]
fixed it.
![주석 2019-08-31 002445](https://user-images.githubusercontent.com/31692408/64076406-7dc06b80-ccff-11e9-8dbd-f985488ef113.png)
