### ISSUE TITLE
Can't change target cast bar back to red

### ISSUE THREAD

**Issue by Kaeshya123** [skotlex/ffxiv-material-ui#88]
![image](https://user-images.githubusercontent.com/54636930/63874892-f4eeba80-c9f4-11e9-8991-5e869844fadd.png)

I installed the black version of the UI then realised that I prefer the discord version. After uninstalling black and reinstalling the discord version, my target info progress bar (I'm using the "Display target info independently" setting in my hud UI) still remains black. For someone as blind as I am, I can't "see" the target info progress bar if it's not glowing red. Am I able to revert the cast bar to red?

Awesome UI btw :)

**Comment by skotlex** [comment]
This item has been changed due to #53 of v2.1.8. I changed this because it was difficult to distinguish between the interrupt cast bar, but since you want the previous version, I will offer it as an option. :3c

**Comment by Kaeshya123** [comment]
Okay, I can definitely see why this was implemented. Having an option to revert it would really help. Thank you so much!

**Comment by skotlex** [comment]
![preview](https://user-images.githubusercontent.com/31692408/64076850-1a393c80-cd05-11e9-8491-56194d11bdaa.png)
