### ISSUE TITLE
Controller Mode Implementation

### ISSUE THREAD

**Issue by darktakayanagi** [skotlex/ffxiv-material-ui#90]
Hey, found out about your mod and decided to give it a try. Looks nice.
Found 2 "bugs" so far, both controller/gamepad reladed.
The Main Menu (pressing Start in-game using a controller),
and the Skill Names on the Cross HotBar.
Are you planning on including them in the mod, if possible? (or the way they are is intentional?)
![image](https://user-images.githubusercontent.com/1959620/64219176-48ad4800-cebc-11e9-9d57-9644f9f08a0e.png)
![image](https://user-images.githubusercontent.com/1959620/64219376-2ec03500-cebd-11e9-8bf0-cf4be513481d.png)

**Comment by skotlex** [comment]
I'm not a pad user, so I don't know what's wrong with your screenshot. 
Can you explain the difference between not applying mod?
I know it's annoying, but if you can compare it with the screenshot, thank you very much.

**Comment by darktakayanagi** [comment]
yea, sorry for not being clear enough xD
what I mean is, your mod didn't touch on the controller's main menu (start button) files.
They are still the vanilla UI, thats why I posted, I figured you might have not noticed them.

A & D - Turn this red? (like you did in the map view, the last pic)
B & C - the vanilla yellow/blue color combo feel out of place when used with the mod black/red combo
![image](https://user-images.githubusercontent.com/1959620/64220246-94fa8700-cec0-11e9-9e64-7f9879affcfd.png)
![image](https://user-images.githubusercontent.com/1959620/64220285-c1160800-cec0-11e9-9ab1-026a320785ba.png)

![image](https://user-images.githubusercontent.com/1959620/64220392-2bc74380-cec1-11e9-8f71-df28d8ca873f.png)

**Comment by darktakayanagi** [comment]
found another one (assuming the blue tint should be changed to red, ignore this if it is intentional)

![image](https://user-images.githubusercontent.com/1959620/64222543-5cf74200-cec8-11e9-9e47-cc0a7bbde9da.png)

**Comment by darktakayanagi** [comment]
when changing controller Hotbar set, there are a few inconsistencies.

A- The letter "T" from Set is different depending on wich set number I have.
sets 1-3 seem to be good, sets 4-8 have those weird pixels behind.
perhaps it is related with sets 1-3 not having the background color while sets 4-8 have the background square
![image](https://user-images.githubusercontent.com/1959620/64222848-84024380-cec9-11e9-8882-3016b353a8b3.png)
![image](https://user-images.githubusercontent.com/1959620/64222880-9ed4b800-cec9-11e9-8a77-cec75e30c610.png)
![image](https://user-images.githubusercontent.com/1959620/64222906-b57b0f00-cec9-11e9-909a-fc46b477fbc9.png)
![image](https://user-images.githubusercontent.com/1959620/64222918-c297fe00-cec9-11e9-9eb5-47ee1579a9b7.png)



another minor detail,
while showing the set selection window (pic below)
![image](https://user-images.githubusercontent.com/1959620/64223078-684b6d00-ceca-11e9-8b47-d1b3f98acead.png)

both set 3 and set 7, while selected have the left side of the selection square line a bug, looks like the vertical line is thicker on the bottom half
![image](https://user-images.githubusercontent.com/1959620/64223181-c8421380-ceca-11e9-9bae-86a34af163d2.png) ![image](https://user-images.githubusercontent.com/1959620/64223222-e90a6900-ceca-11e9-8179-a0ab4e928db5.png) (those have the bug)

![OIApbAhUwY](https://user-images.githubusercontent.com/1959620/64223297-4999a600-cecb-11e9-9754-6cf1c4451556.gif) (gif showing them all)

**Comment by skotlex** [comment]
Thank you for your explanation. First of all, I can't control the font color. But I'll see if I can change the background color. The background of the pad number is probably influenced by changing other things. This requires an experiment.

**Comment by skotlex** [comment]
> ![image](https://user-images.githubusercontent.com/1959620/64220246-94fa8700-cec0-11e9-9e64-7f9879affcfd.png)
> ![image](https://user-images.githubusercontent.com/1959620/64222543-5cf74200-cec8-11e9-9e47-cc0a7bbde9da.png)

Do you know how users who do not use pads can see screens?

**Comment by darktakayanagi** [comment]
The "main menu" is viewable with the keyboard. go in the character config (K by default), enable gamepad mode, otherwise, it won't open the gamepad version of the main menu, then press "+" on the NUMPAD. (if you want to change the keybind for it, see pic below)
the "edit hotbar thing", i couldnt find a way to open it with keyboard. it may be a screen available with gamepad input only.

![image](https://user-images.githubusercontent.com/1959620/64273646-a5027d00-cf39-11e9-9a0a-cc6316276b80.png)

**Comment by skotlex** [comment]
Thank you for your information.

**Comment by darktakayanagi** [comment]
> ![image](https://user-images.githubusercontent.com/1959620/64222906-b57b0f00-cec9-11e9-909a-fc46b477fbc9.png)
> ![image](https://user-images.githubusercontent.com/1959620/64222918-c297fe00-cec9-11e9-9eb5-47ee1579a9b7.png)
> 
> 
> ![OIApbAhUwY](https://user-images.githubusercontent.com/1959620/64223297-4999a600-cecb-11e9-9754-6cf1c4451556.gif)

These only happen with GShade On, so please disregard them. sorry again.

**Comment by skotlex** [comment]
okay thank you :3c

**Comment by skotlex** [comment]
![image](https://user-images.githubusercontent.com/1959620/64220285-c1160800-cec0-11e9-9ab1-026a320785ba.png)
![image](https://user-images.githubusercontent.com/1959620/64222543-5cf74200-cec8-11e9-9e47-cc0a7bbde9da.png)

I think these are the only two things I can modify. 
The rest is not supported by the textool.

But since I have no way of verifying the modified part without the pad, can you apply this and let me know the result?
[pad_background.zip](https://github.com/skotlex/ffxiv-material-ui/files/3586819/pad_background.zip)

**Comment by darktakayanagi** [comment]
yup, it works
![image](https://user-images.githubusercontent.com/1959620/64481708-119ba700-d1da-11e9-86f3-0dad081913aa.png)

(btw would it be too much to ask for a dark gray/ black version?)

**Comment by skotlex** [comment]
I want you to test this and let me know the results.
[pad_background_fix2.zip](https://github.com/skotlex/ffxiv-material-ui/files/3587213/pad_background_fix2.zip)

**Comment by darktakayanagi** [comment]
works perfectly, thank you very much!
![image](https://user-images.githubusercontent.com/1959620/64481838-1dd53380-d1dd-11e9-8057-d57e93bd330f.png)

**Comment by skotlex** [comment]
I'll add this to the next version. Thank you.

**Comment by darktakayanagi** [comment]
sorry to bother you once again.
when I was installing your gamepad fixes
I noticed that there is a "MainCross" in the vanilla HUD files which I guess refers to this screen:
> ![image](https://user-images.githubusercontent.com/1959620/64220246-94fa8700-cec0-11e9-9e64-7f9879affcfd.png)
this is the texture:
![image](https://user-images.githubusercontent.com/1959620/64482049-cdaca000-d1e1-11e9-8a41-023ef25badba.png)

by logic:
the blue circle is the unfocused tabs (C)
gold circle is the focused tab
blue bit is the background-color (A)
"?" is the same one on top of the menu describing what we have selected
brown blur is the background for the option we have selected (B)

**Comment by skotlex** [comment]
Oh I didn't know this existed. But since I can't change the color of the letters, I hesitate to change the color of these. Please let me know if there is a recommended combination of colors. I'll try do this
