### ISSUE TITLE
"Glow" on the hotbar icons

### ISSUE THREAD

**Issue by Aireil** [skotlex/ffxiv-material-ui#92]
Hello,

I'm loving the mod, thank you for your work.

I just find the hotbar buttons a bit weird, it feels like the top got cut off, probably because the icons are usually darker at the top (I'm using the Black version).
I tried modifying the IconA_Frame texture to get the ["glow"](https://i.imgur.com/rkz5Gf8.png) from the default texture, without success. It seems like as soon as I put the black background, the "glow" disappears, so here's my question: Is it possible to get the glow from the default texture while keeping the "darker" background? If I use the texture of the game, the background is too bright (in the inventory etc).

Thank you again!

**Comment by Aireil** [comment]
I just tried the frames from the Discord version and if it's not possible to bring the "glow" back in the Black version, is it possible to remove [this "glow" from the Discord version](https://i.imgur.com/6jvQJeB.png)? (Sorry sure using "glow" so much, not sure how to call these ^^") I just changed the hover texture.

**Comment by skotlex** [comment]
What do you want is the content below?
(1). Currently, key pressed(=hovered) texture(iconA_frame.dds) of discord-ui is applied.
(2). You want to erase the glow effect in texture at (1)

I am sorry that I do not understand English well. 
If there are any differences, please tell me.

**Comment by Aireil** [comment]
Sorry, I'm not expressing myself clearly, please ignore my previous messages.
I changed the key pressed texture of the Discord version with the Black version ([Here's my icona_frame.dds](https://i.imgur.com/s18yl4T.png)). But I wish the erase the glow effect outside of the silver border ([this](https://i.imgur.com/T9CgRp4.png)). Is it possible?

**Comment by skotlex** [comment]
It is possible, but first you must give the dds file instead of the png file. 
Drag the dds file to textbox and upload it.

**Comment by Aireil** [comment]
I didn't give you the dds file because something is wrong with my file format. When I modify the dds and add it to TexTools, then enter the duty "The Praetorium", my games [crashes](https://i.imgur.com/I0eMjA7.png) and I have to reset everything.

Here's my .dds, but it's for sure not the right format/file ^^".
[icona_frame.zip](https://github.com/skotlex/ffxiv-material-ui/files/3584085/icona_frame.zip)

**Comment by skotlex** [comment]
When you look at texture, maybe what you want is an icon frame of discord-ui + a key pressed image of black-ui. If this is correct, I will upload the sample tomorrow.

**Comment by Aireil** [comment]
Yes, that'd be perfect! Thank you very much! :-)

**Comment by skotlex** [comment]
Get this and apply it.
[icona_frame.zip](https://github.com/skotlex/ffxiv-material-ui/files/3586210/icona_frame.zip)

And this option will not be included in the release version. 
Please excuse me.

**Comment by Aireil** [comment]
Perfect, this is awesome! And yes, I'll keep the texture to apply it separately, it's totally understandable :).

감사합니다!
