### ISSUE TITLE
Missing Duty Action Image

### ISSUE THREAD

**Issue by darktakayanagi** [skotlex/ffxiv-material-ui#93]
sorry to bother you again.
just noticed that the Duty Action 1 icon is missing in your mod.
can you confirm that its not a problem on my end? I disabled all mods, and then I only enabled the UI mod and the problem persists
![ffxiv_dx11_qcoZJMAwrF](https://user-images.githubusercontent.com/1959620/64481781-93400480-d1db-11e9-9ead-323f15d88ad8.png)
![ffxiv_dx11_ZP8CxI5yPV](https://user-images.githubusercontent.com/1959620/64481782-9509c800-d1db-11e9-9c29-dcdb484394a0.png)

**Comment by skotlex** [comment]
This has been removed intentionally, but I'll add it again in the next version. 
There's nothing wrong with the play in the actual dungeon, so I'd appreciate it if you could wait.

**Comment by darktakayanagi** [comment]
since I didn't find any mention of it, I thought you might have missed it.
problem solved then :p
