### ISSUE TITLE
Cleaner Minimap

### ISSUE THREAD

**Issue by ajhix36** [skotlex/ffxiv-material-ui#94]
Hi! Thank you so much for your UI, I don't know how I played without it!
Is there any way to make the minimap UI not have the NSEW cardinal directions? That would be the biggest improvement for me. The rotating sun part too could go too and I wouldnt miss it, but the NSEW is the biggest nuisance. Thank you!

**Comment by skotlex** [comment]
Is that ok?
![주석 2019-09-14 170812](https://user-images.githubusercontent.com/31692408/64905374-4fd12300-d712-11e9-844a-dc2932b4ca41.png)

**Comment by ajhix36** [comment]
Yeah that looks awesome! Does it come in square too? Thank you!!

**Comment by skotlex** [comment]
![주석 2019-09-15 204936](https://user-images.githubusercontent.com/31692408/64921194-16c0ad80-d7fb-11e9-9b99-7fffa42a3af5.png)
[minimap-remove-NSEW.zip](https://github.com/skotlex/ffxiv-material-ui/files/3613723/minimap-remove-NSEW.zip)

There's both of them, so please download them.

**Comment by ajhix36** [comment]
Thank you so much, it turned out absolutely perfect!
