### ISSUE TITLE
앞으로의 운영 방향 (Future operations direction)

### ISSUE THREAD

**Issue by skotlex** [skotlex/ffxiv-material-ui#95]
![icon_24](https://user-images.githubusercontent.com/31692408/64903314-218f1b80-d6f1-11e9-95c2-898dcb19985f.gif)

[한국어]
현재 기존에 구현하고자 하는 부분들을 대부분 만들었고, 앞으로는 최소한의 유지보수만 이어나갈 생각입니다
1. 잘못된 이미지 수정
2. (가능한 선에서) 사용자들의 옵션 추가 요청

사용자 요청의 옵션은 대상 사용자에게 1주일 이내로 전달, 그리고 매월 1일에 전체 사용자에게 배포합니다
저의 모드(Mod)를 사용해 주셔서 감사합니다

**_이 곳은 건의 글을 작성하는 스레드가 아닙니다! 
우측 상단의 New Issue 버튼을 이용해 글을 작성해 주세요 :>_**

![icon_40](https://user-images.githubusercontent.com/31692408/64903316-2784fc80-d6f1-11e9-9a8c-691a7b1bb96a.gif)

[English]
I've made most of the parts I'd like to implement, and I'm going to do the minimum maintenance in the future.
1. Correct the wrong image
2. Requesting additional options from users (as far as possible)

Options for user requests are delivered to the target user within one week and distributed to the entire user on the first day of each month.
Thank you for using my mods

**_This is not a thread for writing suggestions! 
Please write using the "New Issue" button at the top right :>_**

**Comment by zhouhuichen741** [comment]
There are also some small buttons in the chat bar that turn black or red 「X.」

**Comment by zhouhuichen741** [comment]
Client in China

**Comment by skotlex** [comment]
I don't know what you mean. Can you show me by screenshot?

**Comment by Arokhaerr** [comment]
For "Requesting additional options from users (as far as possible)"

Would it be possible to change backgrounds for PotD / HoH from the transparent blue to basically non-existant so it clutters the screen less?

Somewhere I once had an almost 90% transparent black background. I don't know if it was from your UImod earlier or rien_dolls minimal_ui, but it was awesome.

**Comment by skotlex** [comment]
@Arokhaerr Can you tell me what PotD / HoH is? I don't know any abbreviations. I'm sorry :3c

**Comment by Arokhaerr** [comment]
Oh sure sorry. It is Palace of the dead / Heaven on High.

Most commonly used to level up with a run of 10 floors ^^

**Comment by skotlex** [comment]
@Arokhaerr It seems to be talking about DeepDungeon. But I didn't do that content, and I don't know what you're talking about. If you don't mind, I'd appreciate it if you could write about the new issue with your screenshot.

**Comment by Arokhaerr** [comment]
Okay i'll open an issue specific to that topic along with screenshots when I get home. :)
