### ISSUE TITLE
Button Problem on Chinese Client

### ISSUE THREAD

**Issue by zhouhuichen741** [skotlex/ffxiv-material-ui#96]
There are also some small buttons in the chat bar that turn black or red 「X」.
![QQ截图20190915065030](https://user-images.githubusercontent.com/50648819/64914502-ec80d880-d785-11e9-923b-849558a03113.png)
![QQ截图20190915065103](https://user-images.githubusercontent.com/50648819/64914503-ef7bc900-d785-11e9-96ce-39c771738f0b.png)
![QQ截图20190915065125](https://user-images.githubusercontent.com/50648819/64914505-f3a7e680-d785-11e9-8f6f-62d09fb503da.png)
![QQ截图20190915065134](https://user-images.githubusercontent.com/50648819/64914506-f4d91380-d785-11e9-9063-52c528cd50d1.png)
![QQ截图20190915065153](https://user-images.githubusercontent.com/50648819/64914509-f6a2d700-d785-11e9-8f60-32cc5cb37a5a.png)
![QQ截图20190915065205](https://user-images.githubusercontent.com/50648819/64914510-f9053100-d785-11e9-904e-d58a58d77896.png)
![QQ截图20190915065233](https://user-images.githubusercontent.com/50648819/64914511-fb678b00-d785-11e9-8e94-22040a834e6c.png)
![QQ截图20190915065239](https://user-images.githubusercontent.com/50648819/64914512-fc98b800-d785-11e9-8dbb-9d291ba036bc.png)
![QQ截图20190915065327](https://user-images.githubusercontent.com/50648819/64914513-fdc9e500-d785-11e9-93a9-832ddc5700cc.png)
![QQ截图20190915065409](https://user-images.githubusercontent.com/50648819/64914514-fefb1200-d785-11e9-8e33-335e7ef02bd4.png)
![QQ截图20190915065431](https://user-images.githubusercontent.com/50648819/64914515-ff93a880-d785-11e9-8dbe-ec31f30dade8.png)

**Comment by zhouhuichen741** [comment]
![QQ图片20190915072948](https://user-images.githubusercontent.com/50648819/64914772-a11cf900-d78a-11e9-969a-338b3626999e.png)

**Comment by zhouhuichen741** [comment]
![QQ截图20190915073243](https://user-images.githubusercontent.com/50648819/64914792-0ffa5200-d78b-11e9-9b00-e7b2575f30fe.png)

**Comment by skotlex** [comment]
Oh, I understand. Come to think of it, China is not SHB (5.0). My mod operates normally in 5.0 and does not fit into SB (4.0). Unfortunately, I would appreciate it if you could apply it after the SHB patch.

**Comment by zhouhuichen741** [comment]
thanks
