### ISSUE TITLE
Black lines when above 100% scaling

### ISSUE THREAD

**Issue by Kasamir** [skotlex/ffxiv-material-ui#97]
![image](https://user-images.githubusercontent.com/55703562/65435190-aa752800-de52-11e9-9f2e-b43fe20483e9.png)

![image](https://user-images.githubusercontent.com/55703562/65435324-eb6d3c80-de52-11e9-82c1-4a8e64a788bc.png)

![image](https://user-images.githubusercontent.com/55703562/65435374-03dd5700-de53-11e9-9535-730414fb30b7.png)

![image](https://user-images.githubusercontent.com/55703562/65435579-51f25a80-de53-11e9-806a-a6ebeeec998c.png)

This seems to only happen on this UI mod and when scaling above 100%

**Comment by skotlex** [comment]
I'll fix it within this weekend. Thank you for the report :)

**Comment by skotlex** [comment]
![changelog_01](https://user-images.githubusercontent.com/31692408/65829734-59968100-e2e3-11e9-80b3-1eb0cb71913f.png)
fixed it :p
[journal_detail.zip](https://github.com/skotlex/ffxiv-material-ui/files/3666552/journal_detail.zip)
