### ISSUE TITLE
Bard simple jobhud soul voice bar

### ISSUE THREAD

**Issue by ffxivziff** [skotlex/ffxiv-material-ui#98]
**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/56092167/66076436-185dd580-e55e-11e9-9fa3-0a2bdd76153f.jpg)

**Describe the image**
Soul Voice Bar of bards simple jobhud Looks different form the rest. No round edges, different (ugly) colour. :P

I use Discord-UI version

**Comment by skotlex** [comment]
![3](https://user-images.githubusercontent.com/31692408/66449391-e255af80-ea8f-11e9-9453-32e101054353.png)
![4](https://user-images.githubusercontent.com/31692408/66449395-e41f7300-ea8f-11e9-88eb-cedaf3d27535.png)

Sorry too late. Please download this:
[parameter_gauge.zip](https://github.com/skotlex/ffxiv-material-ui/files/3705465/parameter_gauge.zip)

**Comment by ffxivziff** [comment]
Working wonderfull. You are the best man. Thanks for working so quick. ♥
