### ISSUE TITLE
Simplied Job Gauge Pips

### ISSUE THREAD

**Issue by bonermobile** [skotlex/ffxiv-material-ui#99]
Hi, is there any chance the pips for charges/stacks on the simplified job gauges could be skinned? I personally think the default ones clash too much with the rest of the modified assets.

![2019-10-04_22-19-08](https://user-images.githubusercontent.com/12283328/66249239-a28c7200-e6f5-11e9-8185-143454d925b2.png)
![2019-10-04_22-21-29](https://user-images.githubusercontent.com/12283328/66249241-af10ca80-e6f5-11e9-99f8-22e0c33a5403.png)
![2019-10-04_22-16-27](https://user-images.githubusercontent.com/12283328/66249243-b20bbb00-e6f5-11e9-81bc-977828f4e670.png)
![2019-10-04_22-17-53](https://user-images.githubusercontent.com/12283328/66249244-b3d57e80-e6f5-11e9-946d-880157c7bf38.png)

**Comment by skotlex** [comment]
It's possible, but it's gonna take a while. 
It's difficult right now, but I'll improve it in order.

**Comment by skotlex** [comment]
![jobhud](https://user-images.githubusercontent.com/31692408/66711253-3bd91980-edc3-11e9-8fab-09ec010072be.png)
I hope you like it :3c
※ The gauge bar in the image is black ver, but the compressed zip file is based on discord.
[jobhud_simple(discord).zip](https://github.com/skotlex/ffxiv-material-ui/files/3721444/jobhud_simple.discord.zip)

**Comment by bonermobile** [comment]
This looks great, thank you very much!
